// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

#ifndef PROTOBUF_control_2eproto__INCLUDED
#define PROTOBUF_control_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace controlData {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_control_2eproto();
void protobuf_AssignDesc_control_2eproto();
void protobuf_ShutdownFile_control_2eproto();

class ChassisInfo;
class ControlCMD;

// ===================================================================

class ControlCMD : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:controlData.ControlCMD) */ {
 public:
  ControlCMD();
  virtual ~ControlCMD();

  ControlCMD(const ControlCMD& from);

  inline ControlCMD& operator=(const ControlCMD& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ControlCMD& default_instance();

  void Swap(ControlCMD* other);

  // implements Message ----------------------------------------------

  inline ControlCMD* New() const { return New(NULL); }

  ControlCMD* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ControlCMD& from);
  void MergeFrom(const ControlCMD& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ControlCMD* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float targetSteeringAngle = 1;
  void clear_targetsteeringangle();
  static const int kTargetSteeringAngleFieldNumber = 1;
  float targetsteeringangle() const;
  void set_targetsteeringangle(float value);

  // optional float targetSpeed = 2;
  void clear_targetspeed();
  static const int kTargetSpeedFieldNumber = 2;
  float targetspeed() const;
  void set_targetspeed(float value);

  // @@protoc_insertion_point(class_scope:controlData.ControlCMD)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float targetsteeringangle_;
  float targetspeed_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_control_2eproto();
  friend void protobuf_AssignDesc_control_2eproto();
  friend void protobuf_ShutdownFile_control_2eproto();

  void InitAsDefaultInstance();
  static ControlCMD* default_instance_;
};
// -------------------------------------------------------------------

class ChassisInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:controlData.ChassisInfo) */ {
 public:
  ChassisInfo();
  virtual ~ChassisInfo();

  ChassisInfo(const ChassisInfo& from);

  inline ChassisInfo& operator=(const ChassisInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ChassisInfo& default_instance();

  void Swap(ChassisInfo* other);

  // implements Message ----------------------------------------------

  inline ChassisInfo* New() const { return New(NULL); }

  ChassisInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChassisInfo& from);
  void MergeFrom(const ChassisInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ChassisInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float speed = 1;
  void clear_speed();
  static const int kSpeedFieldNumber = 1;
  float speed() const;
  void set_speed(float value);

  // optional float steeringAngle = 2;
  void clear_steeringangle();
  static const int kSteeringAngleFieldNumber = 2;
  float steeringangle() const;
  void set_steeringangle(float value);

  // optional int32 mode = 3;
  void clear_mode();
  static const int kModeFieldNumber = 3;
  ::google::protobuf::int32 mode() const;
  void set_mode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:controlData.ChassisInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  float speed_;
  float steeringangle_;
  ::google::protobuf::int32 mode_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_control_2eproto();
  friend void protobuf_AssignDesc_control_2eproto();
  friend void protobuf_ShutdownFile_control_2eproto();

  void InitAsDefaultInstance();
  static ChassisInfo* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ControlCMD

// optional float targetSteeringAngle = 1;
inline void ControlCMD::clear_targetsteeringangle() {
  targetsteeringangle_ = 0;
}
inline float ControlCMD::targetsteeringangle() const {
  // @@protoc_insertion_point(field_get:controlData.ControlCMD.targetSteeringAngle)
  return targetsteeringangle_;
}
inline void ControlCMD::set_targetsteeringangle(float value) {
  
  targetsteeringangle_ = value;
  // @@protoc_insertion_point(field_set:controlData.ControlCMD.targetSteeringAngle)
}

// optional float targetSpeed = 2;
inline void ControlCMD::clear_targetspeed() {
  targetspeed_ = 0;
}
inline float ControlCMD::targetspeed() const {
  // @@protoc_insertion_point(field_get:controlData.ControlCMD.targetSpeed)
  return targetspeed_;
}
inline void ControlCMD::set_targetspeed(float value) {
  
  targetspeed_ = value;
  // @@protoc_insertion_point(field_set:controlData.ControlCMD.targetSpeed)
}

// -------------------------------------------------------------------

// ChassisInfo

// optional float speed = 1;
inline void ChassisInfo::clear_speed() {
  speed_ = 0;
}
inline float ChassisInfo::speed() const {
  // @@protoc_insertion_point(field_get:controlData.ChassisInfo.speed)
  return speed_;
}
inline void ChassisInfo::set_speed(float value) {
  
  speed_ = value;
  // @@protoc_insertion_point(field_set:controlData.ChassisInfo.speed)
}

// optional float steeringAngle = 2;
inline void ChassisInfo::clear_steeringangle() {
  steeringangle_ = 0;
}
inline float ChassisInfo::steeringangle() const {
  // @@protoc_insertion_point(field_get:controlData.ChassisInfo.steeringAngle)
  return steeringangle_;
}
inline void ChassisInfo::set_steeringangle(float value) {
  
  steeringangle_ = value;
  // @@protoc_insertion_point(field_set:controlData.ChassisInfo.steeringAngle)
}

// optional int32 mode = 3;
inline void ChassisInfo::clear_mode() {
  mode_ = 0;
}
inline ::google::protobuf::int32 ChassisInfo::mode() const {
  // @@protoc_insertion_point(field_get:controlData.ChassisInfo.mode)
  return mode_;
}
inline void ChassisInfo::set_mode(::google::protobuf::int32 value) {
  
  mode_ = value;
  // @@protoc_insertion_point(field_set:controlData.ChassisInfo.mode)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace controlData

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_control_2eproto__INCLUDED
