// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imu.proto

#ifndef PROTOBUF_imu_2eproto__INCLUDED
#define PROTOBUF_imu_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace IMU {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_imu_2eproto();
void protobuf_AssignDesc_imu_2eproto();
void protobuf_ShutdownFile_imu_2eproto();

class Imu;

// ===================================================================

class Imu : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:IMU.Imu) */ {
 public:
  Imu();
  virtual ~Imu();

  Imu(const Imu& from);

  inline Imu& operator=(const Imu& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Imu& default_instance();

  void Swap(Imu* other);

  // implements Message ----------------------------------------------

  inline Imu* New() const { return New(NULL); }

  Imu* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Imu& from);
  void MergeFrom(const Imu& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Imu* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double longitude = 1;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 1;
  double longitude() const;
  void set_longitude(double value);

  // optional double latitude = 2;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 2;
  double latitude() const;
  void set_latitude(double value);

  // optional double gaussX = 3;
  void clear_gaussx();
  static const int kGaussXFieldNumber = 3;
  double gaussx() const;
  void set_gaussx(double value);

  // optional double gaussY = 4;
  void clear_gaussy();
  static const int kGaussYFieldNumber = 4;
  double gaussy() const;
  void set_gaussy(double value);

  // optional int32 gpsValid = 5;
  void clear_gpsvalid();
  static const int kGpsValidFieldNumber = 5;
  ::google::protobuf::int32 gpsvalid() const;
  void set_gpsvalid(::google::protobuf::int32 value);

  // optional double time = 6;
  void clear_time();
  static const int kTimeFieldNumber = 6;
  double time() const;
  void set_time(double value);

  // optional double velocity = 7;
  void clear_velocity();
  static const int kVelocityFieldNumber = 7;
  double velocity() const;
  void set_velocity(double value);

  // optional double yaw = 8;
  void clear_yaw();
  static const int kYawFieldNumber = 8;
  double yaw() const;
  void set_yaw(double value);

  // @@protoc_insertion_point(class_scope:IMU.Imu)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double longitude_;
  double latitude_;
  double gaussx_;
  double gaussy_;
  double time_;
  double velocity_;
  double yaw_;
  ::google::protobuf::int32 gpsvalid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_imu_2eproto();
  friend void protobuf_AssignDesc_imu_2eproto();
  friend void protobuf_ShutdownFile_imu_2eproto();

  void InitAsDefaultInstance();
  static Imu* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Imu

// optional double longitude = 1;
inline void Imu::clear_longitude() {
  longitude_ = 0;
}
inline double Imu::longitude() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.longitude)
  return longitude_;
}
inline void Imu::set_longitude(double value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.longitude)
}

// optional double latitude = 2;
inline void Imu::clear_latitude() {
  latitude_ = 0;
}
inline double Imu::latitude() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.latitude)
  return latitude_;
}
inline void Imu::set_latitude(double value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.latitude)
}

// optional double gaussX = 3;
inline void Imu::clear_gaussx() {
  gaussx_ = 0;
}
inline double Imu::gaussx() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.gaussX)
  return gaussx_;
}
inline void Imu::set_gaussx(double value) {
  
  gaussx_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.gaussX)
}

// optional double gaussY = 4;
inline void Imu::clear_gaussy() {
  gaussy_ = 0;
}
inline double Imu::gaussy() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.gaussY)
  return gaussy_;
}
inline void Imu::set_gaussy(double value) {
  
  gaussy_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.gaussY)
}

// optional int32 gpsValid = 5;
inline void Imu::clear_gpsvalid() {
  gpsvalid_ = 0;
}
inline ::google::protobuf::int32 Imu::gpsvalid() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.gpsValid)
  return gpsvalid_;
}
inline void Imu::set_gpsvalid(::google::protobuf::int32 value) {
  
  gpsvalid_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.gpsValid)
}

// optional double time = 6;
inline void Imu::clear_time() {
  time_ = 0;
}
inline double Imu::time() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.time)
  return time_;
}
inline void Imu::set_time(double value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.time)
}

// optional double velocity = 7;
inline void Imu::clear_velocity() {
  velocity_ = 0;
}
inline double Imu::velocity() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.velocity)
  return velocity_;
}
inline void Imu::set_velocity(double value) {
  
  velocity_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.velocity)
}

// optional double yaw = 8;
inline void Imu::clear_yaw() {
  yaw_ = 0;
}
inline double Imu::yaw() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.yaw)
  return yaw_;
}
inline void Imu::set_yaw(double value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.yaw)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace IMU

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_imu_2eproto__INCLUDED
