// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlanningMsg.proto

#ifndef PROTOBUF_PlanningMsg_2eproto__INCLUDED
#define PROTOBUF_PlanningMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Planning {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_PlanningMsg_2eproto();
void protobuf_AssignDesc_PlanningMsg_2eproto();
void protobuf_ShutdownFile_PlanningMsg_2eproto();

class ObjectsProtoForUnity;
class TrafficLightForUnity;
class TrajectoryPoint;
class TrajectoryPointVec;

// ===================================================================

class TrajectoryPoint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Planning.TrajectoryPoint) */ {
 public:
  TrajectoryPoint();
  virtual ~TrajectoryPoint();

  TrajectoryPoint(const TrajectoryPoint& from);

  inline TrajectoryPoint& operator=(const TrajectoryPoint& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrajectoryPoint& default_instance();

  void Swap(TrajectoryPoint* other);

  // implements Message ----------------------------------------------

  inline TrajectoryPoint* New() const { return New(NULL); }

  TrajectoryPoint* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TrajectoryPoint& from);
  void MergeFrom(const TrajectoryPoint& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TrajectoryPoint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double X = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // optional double Y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // optional double Theta = 3;
  void clear_theta();
  static const int kThetaFieldNumber = 3;
  double theta() const;
  void set_theta(double value);

  // optional double Speed = 4;
  void clear_speed();
  static const int kSpeedFieldNumber = 4;
  double speed() const;
  void set_speed(double value);

  // optional double Curvature = 5;
  void clear_curvature();
  static const int kCurvatureFieldNumber = 5;
  double curvature() const;
  void set_curvature(double value);

  // optional double S = 6;
  void clear_s();
  static const int kSFieldNumber = 6;
  double s() const;
  void set_s(double value);

  // optional double obstacleDistance = 7;
  void clear_obstacledistance();
  static const int kObstacleDistanceFieldNumber = 7;
  double obstacledistance() const;
  void set_obstacledistance(double value);

  // @@protoc_insertion_point(class_scope:Planning.TrajectoryPoint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double x_;
  double y_;
  double theta_;
  double speed_;
  double curvature_;
  double s_;
  double obstacledistance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PlanningMsg_2eproto();
  friend void protobuf_AssignDesc_PlanningMsg_2eproto();
  friend void protobuf_ShutdownFile_PlanningMsg_2eproto();

  void InitAsDefaultInstance();
  static TrajectoryPoint* default_instance_;
};
// -------------------------------------------------------------------

class ObjectsProtoForUnity : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Planning.ObjectsProtoForUnity) */ {
 public:
  ObjectsProtoForUnity();
  virtual ~ObjectsProtoForUnity();

  ObjectsProtoForUnity(const ObjectsProtoForUnity& from);

  inline ObjectsProtoForUnity& operator=(const ObjectsProtoForUnity& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectsProtoForUnity& default_instance();

  void Swap(ObjectsProtoForUnity* other);

  // implements Message ----------------------------------------------

  inline ObjectsProtoForUnity* New() const { return New(NULL); }

  ObjectsProtoForUnity* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObjectsProtoForUnity& from);
  void MergeFrom(const ObjectsProtoForUnity& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ObjectsProtoForUnity* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // optional int32 objectid = 2;
  void clear_objectid();
  static const int kObjectidFieldNumber = 2;
  ::google::protobuf::int32 objectid() const;
  void set_objectid(::google::protobuf::int32 value);

  // optional double lat = 3;
  void clear_lat();
  static const int kLatFieldNumber = 3;
  double lat() const;
  void set_lat(double value);

  // optional double lon = 4;
  void clear_lon();
  static const int kLonFieldNumber = 4;
  double lon() const;
  void set_lon(double value);

  // optional double yaw = 5;
  void clear_yaw();
  static const int kYawFieldNumber = 5;
  double yaw() const;
  void set_yaw(double value);

  // optional double velocity = 6;
  void clear_velocity();
  static const int kVelocityFieldNumber = 6;
  double velocity() const;
  void set_velocity(double value);

  // optional int32 len = 7;
  void clear_len();
  static const int kLenFieldNumber = 7;
  ::google::protobuf::int32 len() const;
  void set_len(::google::protobuf::int32 value);

  // optional int32 width = 8;
  void clear_width();
  static const int kWidthFieldNumber = 8;
  ::google::protobuf::int32 width() const;
  void set_width(::google::protobuf::int32 value);

  // optional int32 height = 9;
  void clear_height();
  static const int kHeightFieldNumber = 9;
  ::google::protobuf::int32 height() const;
  void set_height(::google::protobuf::int32 value);

  // optional int64 timestamp = 10;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 10;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // optional int32 status = 11;
  void clear_status();
  static const int kStatusFieldNumber = 11;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // optional int32 vctype = 12;
  void clear_vctype();
  static const int kVctypeFieldNumber = 12;
  ::google::protobuf::int32 vctype() const;
  void set_vctype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Planning.ObjectsProtoForUnity)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 objectid_;
  double lat_;
  double lon_;
  double yaw_;
  double velocity_;
  ::google::protobuf::int32 len_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int64 timestamp_;
  ::google::protobuf::int32 height_;
  ::google::protobuf::int32 status_;
  ::google::protobuf::int32 vctype_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PlanningMsg_2eproto();
  friend void protobuf_AssignDesc_PlanningMsg_2eproto();
  friend void protobuf_ShutdownFile_PlanningMsg_2eproto();

  void InitAsDefaultInstance();
  static ObjectsProtoForUnity* default_instance_;
};
// -------------------------------------------------------------------

class TrafficLightForUnity : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Planning.TrafficLightForUnity) */ {
 public:
  TrafficLightForUnity();
  virtual ~TrafficLightForUnity();

  TrafficLightForUnity(const TrafficLightForUnity& from);

  inline TrafficLightForUnity& operator=(const TrafficLightForUnity& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrafficLightForUnity& default_instance();

  void Swap(TrafficLightForUnity* other);

  // implements Message ----------------------------------------------

  inline TrafficLightForUnity* New() const { return New(NULL); }

  TrafficLightForUnity* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TrafficLightForUnity& from);
  void MergeFrom(const TrafficLightForUnity& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TrafficLightForUnity* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 state = 1;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // optional int32 lightDirerction = 2;
  void clear_lightdirerction();
  static const int kLightDirerctionFieldNumber = 2;
  ::google::protobuf::int32 lightdirerction() const;
  void set_lightdirerction(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Planning.TrafficLightForUnity)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 lightdirerction_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PlanningMsg_2eproto();
  friend void protobuf_AssignDesc_PlanningMsg_2eproto();
  friend void protobuf_ShutdownFile_PlanningMsg_2eproto();

  void InitAsDefaultInstance();
  static TrafficLightForUnity* default_instance_;
};
// -------------------------------------------------------------------

class TrajectoryPointVec : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Planning.TrajectoryPointVec) */ {
 public:
  TrajectoryPointVec();
  virtual ~TrajectoryPointVec();

  TrajectoryPointVec(const TrajectoryPointVec& from);

  inline TrajectoryPointVec& operator=(const TrajectoryPointVec& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrajectoryPointVec& default_instance();

  void Swap(TrajectoryPointVec* other);

  // implements Message ----------------------------------------------

  inline TrajectoryPointVec* New() const { return New(NULL); }

  TrajectoryPointVec* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TrajectoryPointVec& from);
  void MergeFrom(const TrajectoryPointVec& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TrajectoryPointVec* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Planning.TrajectoryPoint TrajectoryPoints = 1;
  int trajectorypoints_size() const;
  void clear_trajectorypoints();
  static const int kTrajectoryPointsFieldNumber = 1;
  const ::Planning::TrajectoryPoint& trajectorypoints(int index) const;
  ::Planning::TrajectoryPoint* mutable_trajectorypoints(int index);
  ::Planning::TrajectoryPoint* add_trajectorypoints();
  ::google::protobuf::RepeatedPtrField< ::Planning::TrajectoryPoint >*
      mutable_trajectorypoints();
  const ::google::protobuf::RepeatedPtrField< ::Planning::TrajectoryPoint >&
      trajectorypoints() const;

  // repeated .Planning.ObjectsProtoForUnity objectsForUnity = 2;
  int objectsforunity_size() const;
  void clear_objectsforunity();
  static const int kObjectsForUnityFieldNumber = 2;
  const ::Planning::ObjectsProtoForUnity& objectsforunity(int index) const;
  ::Planning::ObjectsProtoForUnity* mutable_objectsforunity(int index);
  ::Planning::ObjectsProtoForUnity* add_objectsforunity();
  ::google::protobuf::RepeatedPtrField< ::Planning::ObjectsProtoForUnity >*
      mutable_objectsforunity();
  const ::google::protobuf::RepeatedPtrField< ::Planning::ObjectsProtoForUnity >&
      objectsforunity() const;

  // optional .Planning.TrafficLightForUnity trafficLightForUnity = 3;
  bool has_trafficlightforunity() const;
  void clear_trafficlightforunity();
  static const int kTrafficLightForUnityFieldNumber = 3;
  const ::Planning::TrafficLightForUnity& trafficlightforunity() const;
  ::Planning::TrafficLightForUnity* mutable_trafficlightforunity();
  ::Planning::TrafficLightForUnity* release_trafficlightforunity();
  void set_allocated_trafficlightforunity(::Planning::TrafficLightForUnity* trafficlightforunity);

  // repeated int32 roadForUnity = 4;
  int roadforunity_size() const;
  void clear_roadforunity();
  static const int kRoadForUnityFieldNumber = 4;
  ::google::protobuf::int32 roadforunity(int index) const;
  void set_roadforunity(int index, ::google::protobuf::int32 value);
  void add_roadforunity(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      roadforunity() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_roadforunity();

  // optional double stopGaussX = 5;
  void clear_stopgaussx();
  static const int kStopGaussXFieldNumber = 5;
  double stopgaussx() const;
  void set_stopgaussx(double value);

  // optional double stopGaussY = 6;
  void clear_stopgaussy();
  static const int kStopGaussYFieldNumber = 6;
  double stopgaussy() const;
  void set_stopgaussy(double value);

  // optional double distanceToStop = 7;
  void clear_distancetostop();
  static const int kDistanceToStopFieldNumber = 7;
  double distancetostop() const;
  void set_distancetostop(double value);

  // @@protoc_insertion_point(class_scope:Planning.TrajectoryPointVec)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::Planning::TrajectoryPoint > trajectorypoints_;
  ::google::protobuf::RepeatedPtrField< ::Planning::ObjectsProtoForUnity > objectsforunity_;
  ::Planning::TrafficLightForUnity* trafficlightforunity_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > roadforunity_;
  mutable int _roadforunity_cached_byte_size_;
  double stopgaussx_;
  double stopgaussy_;
  double distancetostop_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PlanningMsg_2eproto();
  friend void protobuf_AssignDesc_PlanningMsg_2eproto();
  friend void protobuf_ShutdownFile_PlanningMsg_2eproto();

  void InitAsDefaultInstance();
  static TrajectoryPointVec* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TrajectoryPoint

// optional double X = 1;
inline void TrajectoryPoint::clear_x() {
  x_ = 0;
}
inline double TrajectoryPoint::x() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.X)
  return x_;
}
inline void TrajectoryPoint::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.X)
}

// optional double Y = 2;
inline void TrajectoryPoint::clear_y() {
  y_ = 0;
}
inline double TrajectoryPoint::y() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.Y)
  return y_;
}
inline void TrajectoryPoint::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.Y)
}

// optional double Theta = 3;
inline void TrajectoryPoint::clear_theta() {
  theta_ = 0;
}
inline double TrajectoryPoint::theta() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.Theta)
  return theta_;
}
inline void TrajectoryPoint::set_theta(double value) {
  
  theta_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.Theta)
}

// optional double Speed = 4;
inline void TrajectoryPoint::clear_speed() {
  speed_ = 0;
}
inline double TrajectoryPoint::speed() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.Speed)
  return speed_;
}
inline void TrajectoryPoint::set_speed(double value) {
  
  speed_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.Speed)
}

// optional double Curvature = 5;
inline void TrajectoryPoint::clear_curvature() {
  curvature_ = 0;
}
inline double TrajectoryPoint::curvature() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.Curvature)
  return curvature_;
}
inline void TrajectoryPoint::set_curvature(double value) {
  
  curvature_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.Curvature)
}

// optional double S = 6;
inline void TrajectoryPoint::clear_s() {
  s_ = 0;
}
inline double TrajectoryPoint::s() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.S)
  return s_;
}
inline void TrajectoryPoint::set_s(double value) {
  
  s_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.S)
}

// optional double obstacleDistance = 7;
inline void TrajectoryPoint::clear_obstacledistance() {
  obstacledistance_ = 0;
}
inline double TrajectoryPoint::obstacledistance() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.obstacleDistance)
  return obstacledistance_;
}
inline void TrajectoryPoint::set_obstacledistance(double value) {
  
  obstacledistance_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.obstacleDistance)
}

// -------------------------------------------------------------------

// ObjectsProtoForUnity

// optional int32 type = 1;
inline void ObjectsProtoForUnity::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 ObjectsProtoForUnity::type() const {
  // @@protoc_insertion_point(field_get:Planning.ObjectsProtoForUnity.type)
  return type_;
}
inline void ObjectsProtoForUnity::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:Planning.ObjectsProtoForUnity.type)
}

// optional int32 objectid = 2;
inline void ObjectsProtoForUnity::clear_objectid() {
  objectid_ = 0;
}
inline ::google::protobuf::int32 ObjectsProtoForUnity::objectid() const {
  // @@protoc_insertion_point(field_get:Planning.ObjectsProtoForUnity.objectid)
  return objectid_;
}
inline void ObjectsProtoForUnity::set_objectid(::google::protobuf::int32 value) {
  
  objectid_ = value;
  // @@protoc_insertion_point(field_set:Planning.ObjectsProtoForUnity.objectid)
}

// optional double lat = 3;
inline void ObjectsProtoForUnity::clear_lat() {
  lat_ = 0;
}
inline double ObjectsProtoForUnity::lat() const {
  // @@protoc_insertion_point(field_get:Planning.ObjectsProtoForUnity.lat)
  return lat_;
}
inline void ObjectsProtoForUnity::set_lat(double value) {
  
  lat_ = value;
  // @@protoc_insertion_point(field_set:Planning.ObjectsProtoForUnity.lat)
}

// optional double lon = 4;
inline void ObjectsProtoForUnity::clear_lon() {
  lon_ = 0;
}
inline double ObjectsProtoForUnity::lon() const {
  // @@protoc_insertion_point(field_get:Planning.ObjectsProtoForUnity.lon)
  return lon_;
}
inline void ObjectsProtoForUnity::set_lon(double value) {
  
  lon_ = value;
  // @@protoc_insertion_point(field_set:Planning.ObjectsProtoForUnity.lon)
}

// optional double yaw = 5;
inline void ObjectsProtoForUnity::clear_yaw() {
  yaw_ = 0;
}
inline double ObjectsProtoForUnity::yaw() const {
  // @@protoc_insertion_point(field_get:Planning.ObjectsProtoForUnity.yaw)
  return yaw_;
}
inline void ObjectsProtoForUnity::set_yaw(double value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:Planning.ObjectsProtoForUnity.yaw)
}

// optional double velocity = 6;
inline void ObjectsProtoForUnity::clear_velocity() {
  velocity_ = 0;
}
inline double ObjectsProtoForUnity::velocity() const {
  // @@protoc_insertion_point(field_get:Planning.ObjectsProtoForUnity.velocity)
  return velocity_;
}
inline void ObjectsProtoForUnity::set_velocity(double value) {
  
  velocity_ = value;
  // @@protoc_insertion_point(field_set:Planning.ObjectsProtoForUnity.velocity)
}

// optional int32 len = 7;
inline void ObjectsProtoForUnity::clear_len() {
  len_ = 0;
}
inline ::google::protobuf::int32 ObjectsProtoForUnity::len() const {
  // @@protoc_insertion_point(field_get:Planning.ObjectsProtoForUnity.len)
  return len_;
}
inline void ObjectsProtoForUnity::set_len(::google::protobuf::int32 value) {
  
  len_ = value;
  // @@protoc_insertion_point(field_set:Planning.ObjectsProtoForUnity.len)
}

// optional int32 width = 8;
inline void ObjectsProtoForUnity::clear_width() {
  width_ = 0;
}
inline ::google::protobuf::int32 ObjectsProtoForUnity::width() const {
  // @@protoc_insertion_point(field_get:Planning.ObjectsProtoForUnity.width)
  return width_;
}
inline void ObjectsProtoForUnity::set_width(::google::protobuf::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:Planning.ObjectsProtoForUnity.width)
}

// optional int32 height = 9;
inline void ObjectsProtoForUnity::clear_height() {
  height_ = 0;
}
inline ::google::protobuf::int32 ObjectsProtoForUnity::height() const {
  // @@protoc_insertion_point(field_get:Planning.ObjectsProtoForUnity.height)
  return height_;
}
inline void ObjectsProtoForUnity::set_height(::google::protobuf::int32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:Planning.ObjectsProtoForUnity.height)
}

// optional int64 timestamp = 10;
inline void ObjectsProtoForUnity::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ObjectsProtoForUnity::timestamp() const {
  // @@protoc_insertion_point(field_get:Planning.ObjectsProtoForUnity.timestamp)
  return timestamp_;
}
inline void ObjectsProtoForUnity::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:Planning.ObjectsProtoForUnity.timestamp)
}

// optional int32 status = 11;
inline void ObjectsProtoForUnity::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 ObjectsProtoForUnity::status() const {
  // @@protoc_insertion_point(field_get:Planning.ObjectsProtoForUnity.status)
  return status_;
}
inline void ObjectsProtoForUnity::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:Planning.ObjectsProtoForUnity.status)
}

// optional int32 vctype = 12;
inline void ObjectsProtoForUnity::clear_vctype() {
  vctype_ = 0;
}
inline ::google::protobuf::int32 ObjectsProtoForUnity::vctype() const {
  // @@protoc_insertion_point(field_get:Planning.ObjectsProtoForUnity.vctype)
  return vctype_;
}
inline void ObjectsProtoForUnity::set_vctype(::google::protobuf::int32 value) {
  
  vctype_ = value;
  // @@protoc_insertion_point(field_set:Planning.ObjectsProtoForUnity.vctype)
}

// -------------------------------------------------------------------

// TrafficLightForUnity

// optional int32 state = 1;
inline void TrafficLightForUnity::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 TrafficLightForUnity::state() const {
  // @@protoc_insertion_point(field_get:Planning.TrafficLightForUnity.state)
  return state_;
}
inline void TrafficLightForUnity::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrafficLightForUnity.state)
}

// optional int32 lightDirerction = 2;
inline void TrafficLightForUnity::clear_lightdirerction() {
  lightdirerction_ = 0;
}
inline ::google::protobuf::int32 TrafficLightForUnity::lightdirerction() const {
  // @@protoc_insertion_point(field_get:Planning.TrafficLightForUnity.lightDirerction)
  return lightdirerction_;
}
inline void TrafficLightForUnity::set_lightdirerction(::google::protobuf::int32 value) {
  
  lightdirerction_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrafficLightForUnity.lightDirerction)
}

// -------------------------------------------------------------------

// TrajectoryPointVec

// repeated .Planning.TrajectoryPoint TrajectoryPoints = 1;
inline int TrajectoryPointVec::trajectorypoints_size() const {
  return trajectorypoints_.size();
}
inline void TrajectoryPointVec::clear_trajectorypoints() {
  trajectorypoints_.Clear();
}
inline const ::Planning::TrajectoryPoint& TrajectoryPointVec::trajectorypoints(int index) const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPointVec.TrajectoryPoints)
  return trajectorypoints_.Get(index);
}
inline ::Planning::TrajectoryPoint* TrajectoryPointVec::mutable_trajectorypoints(int index) {
  // @@protoc_insertion_point(field_mutable:Planning.TrajectoryPointVec.TrajectoryPoints)
  return trajectorypoints_.Mutable(index);
}
inline ::Planning::TrajectoryPoint* TrajectoryPointVec::add_trajectorypoints() {
  // @@protoc_insertion_point(field_add:Planning.TrajectoryPointVec.TrajectoryPoints)
  return trajectorypoints_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Planning::TrajectoryPoint >*
TrajectoryPointVec::mutable_trajectorypoints() {
  // @@protoc_insertion_point(field_mutable_list:Planning.TrajectoryPointVec.TrajectoryPoints)
  return &trajectorypoints_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Planning::TrajectoryPoint >&
TrajectoryPointVec::trajectorypoints() const {
  // @@protoc_insertion_point(field_list:Planning.TrajectoryPointVec.TrajectoryPoints)
  return trajectorypoints_;
}

// repeated .Planning.ObjectsProtoForUnity objectsForUnity = 2;
inline int TrajectoryPointVec::objectsforunity_size() const {
  return objectsforunity_.size();
}
inline void TrajectoryPointVec::clear_objectsforunity() {
  objectsforunity_.Clear();
}
inline const ::Planning::ObjectsProtoForUnity& TrajectoryPointVec::objectsforunity(int index) const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPointVec.objectsForUnity)
  return objectsforunity_.Get(index);
}
inline ::Planning::ObjectsProtoForUnity* TrajectoryPointVec::mutable_objectsforunity(int index) {
  // @@protoc_insertion_point(field_mutable:Planning.TrajectoryPointVec.objectsForUnity)
  return objectsforunity_.Mutable(index);
}
inline ::Planning::ObjectsProtoForUnity* TrajectoryPointVec::add_objectsforunity() {
  // @@protoc_insertion_point(field_add:Planning.TrajectoryPointVec.objectsForUnity)
  return objectsforunity_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Planning::ObjectsProtoForUnity >*
TrajectoryPointVec::mutable_objectsforunity() {
  // @@protoc_insertion_point(field_mutable_list:Planning.TrajectoryPointVec.objectsForUnity)
  return &objectsforunity_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Planning::ObjectsProtoForUnity >&
TrajectoryPointVec::objectsforunity() const {
  // @@protoc_insertion_point(field_list:Planning.TrajectoryPointVec.objectsForUnity)
  return objectsforunity_;
}

// optional .Planning.TrafficLightForUnity trafficLightForUnity = 3;
inline bool TrajectoryPointVec::has_trafficlightforunity() const {
  return !_is_default_instance_ && trafficlightforunity_ != NULL;
}
inline void TrajectoryPointVec::clear_trafficlightforunity() {
  if (GetArenaNoVirtual() == NULL && trafficlightforunity_ != NULL) delete trafficlightforunity_;
  trafficlightforunity_ = NULL;
}
inline const ::Planning::TrafficLightForUnity& TrajectoryPointVec::trafficlightforunity() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPointVec.trafficLightForUnity)
  return trafficlightforunity_ != NULL ? *trafficlightforunity_ : *default_instance_->trafficlightforunity_;
}
inline ::Planning::TrafficLightForUnity* TrajectoryPointVec::mutable_trafficlightforunity() {
  
  if (trafficlightforunity_ == NULL) {
    trafficlightforunity_ = new ::Planning::TrafficLightForUnity;
  }
  // @@protoc_insertion_point(field_mutable:Planning.TrajectoryPointVec.trafficLightForUnity)
  return trafficlightforunity_;
}
inline ::Planning::TrafficLightForUnity* TrajectoryPointVec::release_trafficlightforunity() {
  // @@protoc_insertion_point(field_release:Planning.TrajectoryPointVec.trafficLightForUnity)
  
  ::Planning::TrafficLightForUnity* temp = trafficlightforunity_;
  trafficlightforunity_ = NULL;
  return temp;
}
inline void TrajectoryPointVec::set_allocated_trafficlightforunity(::Planning::TrafficLightForUnity* trafficlightforunity) {
  delete trafficlightforunity_;
  trafficlightforunity_ = trafficlightforunity;
  if (trafficlightforunity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Planning.TrajectoryPointVec.trafficLightForUnity)
}

// repeated int32 roadForUnity = 4;
inline int TrajectoryPointVec::roadforunity_size() const {
  return roadforunity_.size();
}
inline void TrajectoryPointVec::clear_roadforunity() {
  roadforunity_.Clear();
}
inline ::google::protobuf::int32 TrajectoryPointVec::roadforunity(int index) const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPointVec.roadForUnity)
  return roadforunity_.Get(index);
}
inline void TrajectoryPointVec::set_roadforunity(int index, ::google::protobuf::int32 value) {
  roadforunity_.Set(index, value);
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPointVec.roadForUnity)
}
inline void TrajectoryPointVec::add_roadforunity(::google::protobuf::int32 value) {
  roadforunity_.Add(value);
  // @@protoc_insertion_point(field_add:Planning.TrajectoryPointVec.roadForUnity)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
TrajectoryPointVec::roadforunity() const {
  // @@protoc_insertion_point(field_list:Planning.TrajectoryPointVec.roadForUnity)
  return roadforunity_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
TrajectoryPointVec::mutable_roadforunity() {
  // @@protoc_insertion_point(field_mutable_list:Planning.TrajectoryPointVec.roadForUnity)
  return &roadforunity_;
}

// optional double stopGaussX = 5;
inline void TrajectoryPointVec::clear_stopgaussx() {
  stopgaussx_ = 0;
}
inline double TrajectoryPointVec::stopgaussx() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPointVec.stopGaussX)
  return stopgaussx_;
}
inline void TrajectoryPointVec::set_stopgaussx(double value) {
  
  stopgaussx_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPointVec.stopGaussX)
}

// optional double stopGaussY = 6;
inline void TrajectoryPointVec::clear_stopgaussy() {
  stopgaussy_ = 0;
}
inline double TrajectoryPointVec::stopgaussy() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPointVec.stopGaussY)
  return stopgaussy_;
}
inline void TrajectoryPointVec::set_stopgaussy(double value) {
  
  stopgaussy_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPointVec.stopGaussY)
}

// optional double distanceToStop = 7;
inline void TrajectoryPointVec::clear_distancetostop() {
  distancetostop_ = 0;
}
inline double TrajectoryPointVec::distancetostop() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPointVec.distanceToStop)
  return distancetostop_;
}
inline void TrajectoryPointVec::set_distancetostop(double value) {
  
  distancetostop_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPointVec.distanceToStop)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Planning

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PlanningMsg_2eproto__INCLUDED
