// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: decision.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "decision.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace infopack {

namespace {

const ::google::protobuf::Descriptor* DispatchProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DispatchProto_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_decision_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_decision_2eproto() {
  protobuf_AddDesc_decision_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "decision.proto");
  GOOGLE_CHECK(file != NULL);
  DispatchProto_descriptor_ = file->message_type(0);
  static const int DispatchProto_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DispatchProto, vehicleid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DispatchProto, desx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DispatchProto, desy_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DispatchProto, road_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DispatchProto, stopx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DispatchProto, stopy_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DispatchProto, ispassenger_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DispatchProto, curstatus_),
  };
  DispatchProto_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      DispatchProto_descriptor_,
      DispatchProto::default_instance_,
      DispatchProto_offsets_,
      -1,
      -1,
      -1,
      sizeof(DispatchProto),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DispatchProto, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DispatchProto, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_decision_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      DispatchProto_descriptor_, &DispatchProto::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_decision_2eproto() {
  delete DispatchProto::default_instance_;
  delete DispatchProto_reflection_;
}

void protobuf_AddDesc_decision_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_decision_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016decision.proto\022\010infopack\"\222\001\n\rDispatchP"
    "roto\022\021\n\tvehicleid\030\001 \001(\005\022\014\n\004desx\030\002 \001(\001\022\014\n"
    "\004desy\030\003 \001(\001\022\014\n\004road\030\004 \003(\005\022\r\n\005stopx\030\005 \003(\005"
    "\022\r\n\005stopy\030\006 \003(\005\022\023\n\013ispassenger\030\007 \001(\005\022\021\n\t"
    "curstatus\030\010 \001(\005b\006proto3", 183);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "decision.proto", &protobuf_RegisterTypes);
  DispatchProto::default_instance_ = new DispatchProto();
  DispatchProto::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_decision_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_decision_2eproto {
  StaticDescriptorInitializer_decision_2eproto() {
    protobuf_AddDesc_decision_2eproto();
  }
} static_descriptor_initializer_decision_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DispatchProto::kVehicleidFieldNumber;
const int DispatchProto::kDesxFieldNumber;
const int DispatchProto::kDesyFieldNumber;
const int DispatchProto::kRoadFieldNumber;
const int DispatchProto::kStopxFieldNumber;
const int DispatchProto::kStopyFieldNumber;
const int DispatchProto::kIspassengerFieldNumber;
const int DispatchProto::kCurstatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DispatchProto::DispatchProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:infopack.DispatchProto)
}

void DispatchProto::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

DispatchProto::DispatchProto(const DispatchProto& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:infopack.DispatchProto)
}

void DispatchProto::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  vehicleid_ = 0;
  desx_ = 0;
  desy_ = 0;
  ispassenger_ = 0;
  curstatus_ = 0;
}

DispatchProto::~DispatchProto() {
  // @@protoc_insertion_point(destructor:infopack.DispatchProto)
  SharedDtor();
}

void DispatchProto::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DispatchProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DispatchProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DispatchProto_descriptor_;
}

const DispatchProto& DispatchProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_decision_2eproto();
  return *default_instance_;
}

DispatchProto* DispatchProto::default_instance_ = NULL;

DispatchProto* DispatchProto::New(::google::protobuf::Arena* arena) const {
  DispatchProto* n = new DispatchProto;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DispatchProto::Clear() {
// @@protoc_insertion_point(message_clear_start:infopack.DispatchProto)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(DispatchProto, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<DispatchProto*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(desx_, desy_);
  ZR_(vehicleid_, ispassenger_);
  curstatus_ = 0;

#undef ZR_HELPER_
#undef ZR_

  road_.Clear();
  stopx_.Clear();
  stopy_.Clear();
}

bool DispatchProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:infopack.DispatchProto)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 vehicleid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &vehicleid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_desx;
        break;
      }

      // optional double desx = 2;
      case 2: {
        if (tag == 17) {
         parse_desx:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &desx_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_desy;
        break;
      }

      // optional double desy = 3;
      case 3: {
        if (tag == 25) {
         parse_desy:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &desy_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_road;
        break;
      }

      // repeated int32 road = 4;
      case 4: {
        if (tag == 34) {
         parse_road:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_road())));
        } else if (tag == 32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 34, input, this->mutable_road())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_stopx;
        break;
      }

      // repeated int32 stopx = 5;
      case 5: {
        if (tag == 42) {
         parse_stopx:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_stopx())));
        } else if (tag == 40) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 42, input, this->mutable_stopx())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_stopy;
        break;
      }

      // repeated int32 stopy = 6;
      case 6: {
        if (tag == 50) {
         parse_stopy:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_stopy())));
        } else if (tag == 48) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 50, input, this->mutable_stopy())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_ispassenger;
        break;
      }

      // optional int32 ispassenger = 7;
      case 7: {
        if (tag == 56) {
         parse_ispassenger:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ispassenger_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_curstatus;
        break;
      }

      // optional int32 curstatus = 8;
      case 8: {
        if (tag == 64) {
         parse_curstatus:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &curstatus_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:infopack.DispatchProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:infopack.DispatchProto)
  return false;
#undef DO_
}

void DispatchProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:infopack.DispatchProto)
  // optional int32 vehicleid = 1;
  if (this->vehicleid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->vehicleid(), output);
  }

  // optional double desx = 2;
  if (this->desx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->desx(), output);
  }

  // optional double desy = 3;
  if (this->desy() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->desy(), output);
  }

  // repeated int32 road = 4;
  if (this->road_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_road_cached_byte_size_);
  }
  for (int i = 0; i < this->road_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->road(i), output);
  }

  // repeated int32 stopx = 5;
  if (this->stopx_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(5, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_stopx_cached_byte_size_);
  }
  for (int i = 0; i < this->stopx_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->stopx(i), output);
  }

  // repeated int32 stopy = 6;
  if (this->stopy_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(6, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_stopy_cached_byte_size_);
  }
  for (int i = 0; i < this->stopy_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->stopy(i), output);
  }

  // optional int32 ispassenger = 7;
  if (this->ispassenger() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->ispassenger(), output);
  }

  // optional int32 curstatus = 8;
  if (this->curstatus() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->curstatus(), output);
  }

  // @@protoc_insertion_point(serialize_end:infopack.DispatchProto)
}

::google::protobuf::uint8* DispatchProto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:infopack.DispatchProto)
  // optional int32 vehicleid = 1;
  if (this->vehicleid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->vehicleid(), target);
  }

  // optional double desx = 2;
  if (this->desx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->desx(), target);
  }

  // optional double desy = 3;
  if (this->desy() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->desy(), target);
  }

  // repeated int32 road = 4;
  if (this->road_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _road_cached_byte_size_, target);
  }
  for (int i = 0; i < this->road_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->road(i), target);
  }

  // repeated int32 stopx = 5;
  if (this->stopx_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      5,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _stopx_cached_byte_size_, target);
  }
  for (int i = 0; i < this->stopx_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->stopx(i), target);
  }

  // repeated int32 stopy = 6;
  if (this->stopy_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      6,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _stopy_cached_byte_size_, target);
  }
  for (int i = 0; i < this->stopy_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->stopy(i), target);
  }

  // optional int32 ispassenger = 7;
  if (this->ispassenger() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->ispassenger(), target);
  }

  // optional int32 curstatus = 8;
  if (this->curstatus() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->curstatus(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:infopack.DispatchProto)
  return target;
}

int DispatchProto::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:infopack.DispatchProto)
  int total_size = 0;

  // optional int32 vehicleid = 1;
  if (this->vehicleid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->vehicleid());
  }

  // optional double desx = 2;
  if (this->desx() != 0) {
    total_size += 1 + 8;
  }

  // optional double desy = 3;
  if (this->desy() != 0) {
    total_size += 1 + 8;
  }

  // optional int32 ispassenger = 7;
  if (this->ispassenger() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->ispassenger());
  }

  // optional int32 curstatus = 8;
  if (this->curstatus() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->curstatus());
  }

  // repeated int32 road = 4;
  {
    int data_size = 0;
    for (int i = 0; i < this->road_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->road(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _road_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated int32 stopx = 5;
  {
    int data_size = 0;
    for (int i = 0; i < this->stopx_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->stopx(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _stopx_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated int32 stopy = 6;
  {
    int data_size = 0;
    for (int i = 0; i < this->stopy_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->stopy(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _stopy_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DispatchProto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:infopack.DispatchProto)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const DispatchProto* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const DispatchProto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:infopack.DispatchProto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:infopack.DispatchProto)
    MergeFrom(*source);
  }
}

void DispatchProto::MergeFrom(const DispatchProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:infopack.DispatchProto)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  road_.MergeFrom(from.road_);
  stopx_.MergeFrom(from.stopx_);
  stopy_.MergeFrom(from.stopy_);
  if (from.vehicleid() != 0) {
    set_vehicleid(from.vehicleid());
  }
  if (from.desx() != 0) {
    set_desx(from.desx());
  }
  if (from.desy() != 0) {
    set_desy(from.desy());
  }
  if (from.ispassenger() != 0) {
    set_ispassenger(from.ispassenger());
  }
  if (from.curstatus() != 0) {
    set_curstatus(from.curstatus());
  }
}

void DispatchProto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:infopack.DispatchProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DispatchProto::CopyFrom(const DispatchProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:infopack.DispatchProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DispatchProto::IsInitialized() const {

  return true;
}

void DispatchProto::Swap(DispatchProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DispatchProto::InternalSwap(DispatchProto* other) {
  std::swap(vehicleid_, other->vehicleid_);
  std::swap(desx_, other->desx_);
  std::swap(desy_, other->desy_);
  road_.UnsafeArenaSwap(&other->road_);
  stopx_.UnsafeArenaSwap(&other->stopx_);
  stopy_.UnsafeArenaSwap(&other->stopy_);
  std::swap(ispassenger_, other->ispassenger_);
  std::swap(curstatus_, other->curstatus_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DispatchProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DispatchProto_descriptor_;
  metadata.reflection = DispatchProto_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DispatchProto

// optional int32 vehicleid = 1;
void DispatchProto::clear_vehicleid() {
  vehicleid_ = 0;
}
 ::google::protobuf::int32 DispatchProto::vehicleid() const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.vehicleid)
  return vehicleid_;
}
 void DispatchProto::set_vehicleid(::google::protobuf::int32 value) {
  
  vehicleid_ = value;
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.vehicleid)
}

// optional double desx = 2;
void DispatchProto::clear_desx() {
  desx_ = 0;
}
 double DispatchProto::desx() const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.desx)
  return desx_;
}
 void DispatchProto::set_desx(double value) {
  
  desx_ = value;
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.desx)
}

// optional double desy = 3;
void DispatchProto::clear_desy() {
  desy_ = 0;
}
 double DispatchProto::desy() const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.desy)
  return desy_;
}
 void DispatchProto::set_desy(double value) {
  
  desy_ = value;
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.desy)
}

// repeated int32 road = 4;
int DispatchProto::road_size() const {
  return road_.size();
}
void DispatchProto::clear_road() {
  road_.Clear();
}
 ::google::protobuf::int32 DispatchProto::road(int index) const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.road)
  return road_.Get(index);
}
 void DispatchProto::set_road(int index, ::google::protobuf::int32 value) {
  road_.Set(index, value);
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.road)
}
 void DispatchProto::add_road(::google::protobuf::int32 value) {
  road_.Add(value);
  // @@protoc_insertion_point(field_add:infopack.DispatchProto.road)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
DispatchProto::road() const {
  // @@protoc_insertion_point(field_list:infopack.DispatchProto.road)
  return road_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
DispatchProto::mutable_road() {
  // @@protoc_insertion_point(field_mutable_list:infopack.DispatchProto.road)
  return &road_;
}

// repeated int32 stopx = 5;
int DispatchProto::stopx_size() const {
  return stopx_.size();
}
void DispatchProto::clear_stopx() {
  stopx_.Clear();
}
 ::google::protobuf::int32 DispatchProto::stopx(int index) const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.stopx)
  return stopx_.Get(index);
}
 void DispatchProto::set_stopx(int index, ::google::protobuf::int32 value) {
  stopx_.Set(index, value);
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.stopx)
}
 void DispatchProto::add_stopx(::google::protobuf::int32 value) {
  stopx_.Add(value);
  // @@protoc_insertion_point(field_add:infopack.DispatchProto.stopx)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
DispatchProto::stopx() const {
  // @@protoc_insertion_point(field_list:infopack.DispatchProto.stopx)
  return stopx_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
DispatchProto::mutable_stopx() {
  // @@protoc_insertion_point(field_mutable_list:infopack.DispatchProto.stopx)
  return &stopx_;
}

// repeated int32 stopy = 6;
int DispatchProto::stopy_size() const {
  return stopy_.size();
}
void DispatchProto::clear_stopy() {
  stopy_.Clear();
}
 ::google::protobuf::int32 DispatchProto::stopy(int index) const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.stopy)
  return stopy_.Get(index);
}
 void DispatchProto::set_stopy(int index, ::google::protobuf::int32 value) {
  stopy_.Set(index, value);
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.stopy)
}
 void DispatchProto::add_stopy(::google::protobuf::int32 value) {
  stopy_.Add(value);
  // @@protoc_insertion_point(field_add:infopack.DispatchProto.stopy)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
DispatchProto::stopy() const {
  // @@protoc_insertion_point(field_list:infopack.DispatchProto.stopy)
  return stopy_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
DispatchProto::mutable_stopy() {
  // @@protoc_insertion_point(field_mutable_list:infopack.DispatchProto.stopy)
  return &stopy_;
}

// optional int32 ispassenger = 7;
void DispatchProto::clear_ispassenger() {
  ispassenger_ = 0;
}
 ::google::protobuf::int32 DispatchProto::ispassenger() const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.ispassenger)
  return ispassenger_;
}
 void DispatchProto::set_ispassenger(::google::protobuf::int32 value) {
  
  ispassenger_ = value;
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.ispassenger)
}

// optional int32 curstatus = 8;
void DispatchProto::clear_curstatus() {
  curstatus_ = 0;
}
 ::google::protobuf::int32 DispatchProto::curstatus() const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.curstatus)
  return curstatus_;
}
 void DispatchProto::set_curstatus(::google::protobuf::int32 value) {
  
  curstatus_ = value;
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.curstatus)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace infopack

// @@protoc_insertion_point(global_scope)
