// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: decision.proto

#ifndef PROTOBUF_decision_2eproto__INCLUDED
#define PROTOBUF_decision_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace infopack {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_decision_2eproto();
void protobuf_AssignDesc_decision_2eproto();
void protobuf_ShutdownFile_decision_2eproto();

class DispatchProto;

// ===================================================================

class DispatchProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:infopack.DispatchProto) */ {
 public:
  DispatchProto();
  virtual ~DispatchProto();

  DispatchProto(const DispatchProto& from);

  inline DispatchProto& operator=(const DispatchProto& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DispatchProto& default_instance();

  void Swap(DispatchProto* other);

  // implements Message ----------------------------------------------

  inline DispatchProto* New() const { return New(NULL); }

  DispatchProto* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DispatchProto& from);
  void MergeFrom(const DispatchProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DispatchProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 vehicleid = 1;
  void clear_vehicleid();
  static const int kVehicleidFieldNumber = 1;
  ::google::protobuf::int32 vehicleid() const;
  void set_vehicleid(::google::protobuf::int32 value);

  // optional double desx = 2;
  void clear_desx();
  static const int kDesxFieldNumber = 2;
  double desx() const;
  void set_desx(double value);

  // optional double desy = 3;
  void clear_desy();
  static const int kDesyFieldNumber = 3;
  double desy() const;
  void set_desy(double value);

  // repeated int32 road = 4;
  int road_size() const;
  void clear_road();
  static const int kRoadFieldNumber = 4;
  ::google::protobuf::int32 road(int index) const;
  void set_road(int index, ::google::protobuf::int32 value);
  void add_road(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      road() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_road();

  // repeated int32 stopx = 5;
  int stopx_size() const;
  void clear_stopx();
  static const int kStopxFieldNumber = 5;
  ::google::protobuf::int32 stopx(int index) const;
  void set_stopx(int index, ::google::protobuf::int32 value);
  void add_stopx(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      stopx() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_stopx();

  // repeated int32 stopy = 6;
  int stopy_size() const;
  void clear_stopy();
  static const int kStopyFieldNumber = 6;
  ::google::protobuf::int32 stopy(int index) const;
  void set_stopy(int index, ::google::protobuf::int32 value);
  void add_stopy(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      stopy() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_stopy();

  // optional int32 ispassenger = 7;
  void clear_ispassenger();
  static const int kIspassengerFieldNumber = 7;
  ::google::protobuf::int32 ispassenger() const;
  void set_ispassenger(::google::protobuf::int32 value);

  // optional int32 curstatus = 8;
  void clear_curstatus();
  static const int kCurstatusFieldNumber = 8;
  ::google::protobuf::int32 curstatus() const;
  void set_curstatus(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:infopack.DispatchProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double desx_;
  double desy_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > road_;
  mutable int _road_cached_byte_size_;
  ::google::protobuf::int32 vehicleid_;
  ::google::protobuf::int32 ispassenger_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > stopx_;
  mutable int _stopx_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > stopy_;
  mutable int _stopy_cached_byte_size_;
  ::google::protobuf::int32 curstatus_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_decision_2eproto();
  friend void protobuf_AssignDesc_decision_2eproto();
  friend void protobuf_ShutdownFile_decision_2eproto();

  void InitAsDefaultInstance();
  static DispatchProto* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// DispatchProto

// optional int32 vehicleid = 1;
inline void DispatchProto::clear_vehicleid() {
  vehicleid_ = 0;
}
inline ::google::protobuf::int32 DispatchProto::vehicleid() const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.vehicleid)
  return vehicleid_;
}
inline void DispatchProto::set_vehicleid(::google::protobuf::int32 value) {
  
  vehicleid_ = value;
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.vehicleid)
}

// optional double desx = 2;
inline void DispatchProto::clear_desx() {
  desx_ = 0;
}
inline double DispatchProto::desx() const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.desx)
  return desx_;
}
inline void DispatchProto::set_desx(double value) {
  
  desx_ = value;
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.desx)
}

// optional double desy = 3;
inline void DispatchProto::clear_desy() {
  desy_ = 0;
}
inline double DispatchProto::desy() const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.desy)
  return desy_;
}
inline void DispatchProto::set_desy(double value) {
  
  desy_ = value;
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.desy)
}

// repeated int32 road = 4;
inline int DispatchProto::road_size() const {
  return road_.size();
}
inline void DispatchProto::clear_road() {
  road_.Clear();
}
inline ::google::protobuf::int32 DispatchProto::road(int index) const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.road)
  return road_.Get(index);
}
inline void DispatchProto::set_road(int index, ::google::protobuf::int32 value) {
  road_.Set(index, value);
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.road)
}
inline void DispatchProto::add_road(::google::protobuf::int32 value) {
  road_.Add(value);
  // @@protoc_insertion_point(field_add:infopack.DispatchProto.road)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
DispatchProto::road() const {
  // @@protoc_insertion_point(field_list:infopack.DispatchProto.road)
  return road_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
DispatchProto::mutable_road() {
  // @@protoc_insertion_point(field_mutable_list:infopack.DispatchProto.road)
  return &road_;
}

// repeated int32 stopx = 5;
inline int DispatchProto::stopx_size() const {
  return stopx_.size();
}
inline void DispatchProto::clear_stopx() {
  stopx_.Clear();
}
inline ::google::protobuf::int32 DispatchProto::stopx(int index) const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.stopx)
  return stopx_.Get(index);
}
inline void DispatchProto::set_stopx(int index, ::google::protobuf::int32 value) {
  stopx_.Set(index, value);
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.stopx)
}
inline void DispatchProto::add_stopx(::google::protobuf::int32 value) {
  stopx_.Add(value);
  // @@protoc_insertion_point(field_add:infopack.DispatchProto.stopx)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
DispatchProto::stopx() const {
  // @@protoc_insertion_point(field_list:infopack.DispatchProto.stopx)
  return stopx_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
DispatchProto::mutable_stopx() {
  // @@protoc_insertion_point(field_mutable_list:infopack.DispatchProto.stopx)
  return &stopx_;
}

// repeated int32 stopy = 6;
inline int DispatchProto::stopy_size() const {
  return stopy_.size();
}
inline void DispatchProto::clear_stopy() {
  stopy_.Clear();
}
inline ::google::protobuf::int32 DispatchProto::stopy(int index) const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.stopy)
  return stopy_.Get(index);
}
inline void DispatchProto::set_stopy(int index, ::google::protobuf::int32 value) {
  stopy_.Set(index, value);
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.stopy)
}
inline void DispatchProto::add_stopy(::google::protobuf::int32 value) {
  stopy_.Add(value);
  // @@protoc_insertion_point(field_add:infopack.DispatchProto.stopy)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
DispatchProto::stopy() const {
  // @@protoc_insertion_point(field_list:infopack.DispatchProto.stopy)
  return stopy_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
DispatchProto::mutable_stopy() {
  // @@protoc_insertion_point(field_mutable_list:infopack.DispatchProto.stopy)
  return &stopy_;
}

// optional int32 ispassenger = 7;
inline void DispatchProto::clear_ispassenger() {
  ispassenger_ = 0;
}
inline ::google::protobuf::int32 DispatchProto::ispassenger() const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.ispassenger)
  return ispassenger_;
}
inline void DispatchProto::set_ispassenger(::google::protobuf::int32 value) {
  
  ispassenger_ = value;
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.ispassenger)
}

// optional int32 curstatus = 8;
inline void DispatchProto::clear_curstatus() {
  curstatus_ = 0;
}
inline ::google::protobuf::int32 DispatchProto::curstatus() const {
  // @@protoc_insertion_point(field_get:infopack.DispatchProto.curstatus)
  return curstatus_;
}
inline void DispatchProto::set_curstatus(::google::protobuf::int32 value) {
  
  curstatus_ = value;
  // @@protoc_insertion_point(field_set:infopack.DispatchProto.curstatus)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace infopack

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_decision_2eproto__INCLUDED
