// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg2vehicle.proto

#ifndef PROTOBUF_msg2vehicle_2eproto__INCLUDED
#define PROTOBUF_msg2vehicle_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "objects.pb.h"
#include "decision.pb.h"
// @@protoc_insertion_point(includes)

namespace infopack {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_msg2vehicle_2eproto();
void protobuf_AssignDesc_msg2vehicle_2eproto();
void protobuf_ShutdownFile_msg2vehicle_2eproto();

class DecisionsListProto;

// ===================================================================

class DecisionsListProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:infopack.DecisionsListProto) */ {
 public:
  DecisionsListProto();
  virtual ~DecisionsListProto();

  DecisionsListProto(const DecisionsListProto& from);

  inline DecisionsListProto& operator=(const DecisionsListProto& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DecisionsListProto& default_instance();

  void Swap(DecisionsListProto* other);

  // implements Message ----------------------------------------------

  inline DecisionsListProto* New() const { return New(NULL); }

  DecisionsListProto* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DecisionsListProto& from);
  void MergeFrom(const DecisionsListProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DecisionsListProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .infopack.DispatchProto dispatch = 1;
  int dispatch_size() const;
  void clear_dispatch();
  static const int kDispatchFieldNumber = 1;
  const ::infopack::DispatchProto& dispatch(int index) const;
  ::infopack::DispatchProto* mutable_dispatch(int index);
  ::infopack::DispatchProto* add_dispatch();
  ::google::protobuf::RepeatedPtrField< ::infopack::DispatchProto >*
      mutable_dispatch();
  const ::google::protobuf::RepeatedPtrField< ::infopack::DispatchProto >&
      dispatch() const;

  // repeated .infopack.ObjectsProto objects = 2;
  int objects_size() const;
  void clear_objects();
  static const int kObjectsFieldNumber = 2;
  const ::infopack::ObjectsProto& objects(int index) const;
  ::infopack::ObjectsProto* mutable_objects(int index);
  ::infopack::ObjectsProto* add_objects();
  ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >*
      mutable_objects();
  const ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >&
      objects() const;

  // @@protoc_insertion_point(class_scope:infopack.DecisionsListProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::infopack::DispatchProto > dispatch_;
  ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto > objects_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_msg2vehicle_2eproto();
  friend void protobuf_AssignDesc_msg2vehicle_2eproto();
  friend void protobuf_ShutdownFile_msg2vehicle_2eproto();

  void InitAsDefaultInstance();
  static DecisionsListProto* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// DecisionsListProto

// repeated .infopack.DispatchProto dispatch = 1;
inline int DecisionsListProto::dispatch_size() const {
  return dispatch_.size();
}
inline void DecisionsListProto::clear_dispatch() {
  dispatch_.Clear();
}
inline const ::infopack::DispatchProto& DecisionsListProto::dispatch(int index) const {
  // @@protoc_insertion_point(field_get:infopack.DecisionsListProto.dispatch)
  return dispatch_.Get(index);
}
inline ::infopack::DispatchProto* DecisionsListProto::mutable_dispatch(int index) {
  // @@protoc_insertion_point(field_mutable:infopack.DecisionsListProto.dispatch)
  return dispatch_.Mutable(index);
}
inline ::infopack::DispatchProto* DecisionsListProto::add_dispatch() {
  // @@protoc_insertion_point(field_add:infopack.DecisionsListProto.dispatch)
  return dispatch_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::infopack::DispatchProto >*
DecisionsListProto::mutable_dispatch() {
  // @@protoc_insertion_point(field_mutable_list:infopack.DecisionsListProto.dispatch)
  return &dispatch_;
}
inline const ::google::protobuf::RepeatedPtrField< ::infopack::DispatchProto >&
DecisionsListProto::dispatch() const {
  // @@protoc_insertion_point(field_list:infopack.DecisionsListProto.dispatch)
  return dispatch_;
}

// repeated .infopack.ObjectsProto objects = 2;
inline int DecisionsListProto::objects_size() const {
  return objects_.size();
}
inline void DecisionsListProto::clear_objects() {
  objects_.Clear();
}
inline const ::infopack::ObjectsProto& DecisionsListProto::objects(int index) const {
  // @@protoc_insertion_point(field_get:infopack.DecisionsListProto.objects)
  return objects_.Get(index);
}
inline ::infopack::ObjectsProto* DecisionsListProto::mutable_objects(int index) {
  // @@protoc_insertion_point(field_mutable:infopack.DecisionsListProto.objects)
  return objects_.Mutable(index);
}
inline ::infopack::ObjectsProto* DecisionsListProto::add_objects() {
  // @@protoc_insertion_point(field_add:infopack.DecisionsListProto.objects)
  return objects_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >*
DecisionsListProto::mutable_objects() {
  // @@protoc_insertion_point(field_mutable_list:infopack.DecisionsListProto.objects)
  return &objects_;
}
inline const ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >&
DecisionsListProto::objects() const {
  // @@protoc_insertion_point(field_list:infopack.DecisionsListProto.objects)
  return objects_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace infopack

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg2vehicle_2eproto__INCLUDED
