// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg2vehicle.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msg2vehicle.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace infopack {

namespace {

const ::google::protobuf::Descriptor* DecisionsListProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DecisionsListProto_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msg2vehicle_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_msg2vehicle_2eproto() {
  protobuf_AddDesc_msg2vehicle_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msg2vehicle.proto");
  GOOGLE_CHECK(file != NULL);
  DecisionsListProto_descriptor_ = file->message_type(0);
  static const int DecisionsListProto_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DecisionsListProto, dispatch_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DecisionsListProto, objects_),
  };
  DecisionsListProto_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      DecisionsListProto_descriptor_,
      DecisionsListProto::default_instance_,
      DecisionsListProto_offsets_,
      -1,
      -1,
      -1,
      sizeof(DecisionsListProto),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DecisionsListProto, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DecisionsListProto, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msg2vehicle_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      DecisionsListProto_descriptor_, &DecisionsListProto::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msg2vehicle_2eproto() {
  delete DecisionsListProto::default_instance_;
  delete DecisionsListProto_reflection_;
}

void protobuf_AddDesc_msg2vehicle_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_msg2vehicle_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::infopack::protobuf_AddDesc_objects_2eproto();
  ::infopack::protobuf_AddDesc_decision_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021msg2vehicle.proto\022\010infopack\032\robjects.p"
    "roto\032\016decision.proto\"h\n\022DecisionsListPro"
    "to\022)\n\010dispatch\030\001 \003(\0132\027.infopack.Dispatch"
    "Proto\022\'\n\007objects\030\002 \003(\0132\026.infopack.Object"
    "sProtob\006proto3", 174);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg2vehicle.proto", &protobuf_RegisterTypes);
  DecisionsListProto::default_instance_ = new DecisionsListProto();
  DecisionsListProto::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msg2vehicle_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msg2vehicle_2eproto {
  StaticDescriptorInitializer_msg2vehicle_2eproto() {
    protobuf_AddDesc_msg2vehicle_2eproto();
  }
} static_descriptor_initializer_msg2vehicle_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DecisionsListProto::kDispatchFieldNumber;
const int DecisionsListProto::kObjectsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DecisionsListProto::DecisionsListProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:infopack.DecisionsListProto)
}

void DecisionsListProto::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

DecisionsListProto::DecisionsListProto(const DecisionsListProto& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:infopack.DecisionsListProto)
}

void DecisionsListProto::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

DecisionsListProto::~DecisionsListProto() {
  // @@protoc_insertion_point(destructor:infopack.DecisionsListProto)
  SharedDtor();
}

void DecisionsListProto::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DecisionsListProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DecisionsListProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DecisionsListProto_descriptor_;
}

const DecisionsListProto& DecisionsListProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg2vehicle_2eproto();
  return *default_instance_;
}

DecisionsListProto* DecisionsListProto::default_instance_ = NULL;

DecisionsListProto* DecisionsListProto::New(::google::protobuf::Arena* arena) const {
  DecisionsListProto* n = new DecisionsListProto;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DecisionsListProto::Clear() {
// @@protoc_insertion_point(message_clear_start:infopack.DecisionsListProto)
  dispatch_.Clear();
  objects_.Clear();
}

bool DecisionsListProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:infopack.DecisionsListProto)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .infopack.DispatchProto dispatch = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_dispatch:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_dispatch()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_dispatch;
        if (input->ExpectTag(18)) goto parse_loop_objects;
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .infopack.ObjectsProto objects = 2;
      case 2: {
        if (tag == 18) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_objects:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_objects()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_objects;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:infopack.DecisionsListProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:infopack.DecisionsListProto)
  return false;
#undef DO_
}

void DecisionsListProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:infopack.DecisionsListProto)
  // repeated .infopack.DispatchProto dispatch = 1;
  for (unsigned int i = 0, n = this->dispatch_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->dispatch(i), output);
  }

  // repeated .infopack.ObjectsProto objects = 2;
  for (unsigned int i = 0, n = this->objects_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->objects(i), output);
  }

  // @@protoc_insertion_point(serialize_end:infopack.DecisionsListProto)
}

::google::protobuf::uint8* DecisionsListProto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:infopack.DecisionsListProto)
  // repeated .infopack.DispatchProto dispatch = 1;
  for (unsigned int i = 0, n = this->dispatch_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->dispatch(i), false, target);
  }

  // repeated .infopack.ObjectsProto objects = 2;
  for (unsigned int i = 0, n = this->objects_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->objects(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:infopack.DecisionsListProto)
  return target;
}

int DecisionsListProto::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:infopack.DecisionsListProto)
  int total_size = 0;

  // repeated .infopack.DispatchProto dispatch = 1;
  total_size += 1 * this->dispatch_size();
  for (int i = 0; i < this->dispatch_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->dispatch(i));
  }

  // repeated .infopack.ObjectsProto objects = 2;
  total_size += 1 * this->objects_size();
  for (int i = 0; i < this->objects_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->objects(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DecisionsListProto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:infopack.DecisionsListProto)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const DecisionsListProto* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const DecisionsListProto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:infopack.DecisionsListProto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:infopack.DecisionsListProto)
    MergeFrom(*source);
  }
}

void DecisionsListProto::MergeFrom(const DecisionsListProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:infopack.DecisionsListProto)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  dispatch_.MergeFrom(from.dispatch_);
  objects_.MergeFrom(from.objects_);
}

void DecisionsListProto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:infopack.DecisionsListProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DecisionsListProto::CopyFrom(const DecisionsListProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:infopack.DecisionsListProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DecisionsListProto::IsInitialized() const {

  return true;
}

void DecisionsListProto::Swap(DecisionsListProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DecisionsListProto::InternalSwap(DecisionsListProto* other) {
  dispatch_.UnsafeArenaSwap(&other->dispatch_);
  objects_.UnsafeArenaSwap(&other->objects_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DecisionsListProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DecisionsListProto_descriptor_;
  metadata.reflection = DecisionsListProto_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DecisionsListProto

// repeated .infopack.DispatchProto dispatch = 1;
int DecisionsListProto::dispatch_size() const {
  return dispatch_.size();
}
void DecisionsListProto::clear_dispatch() {
  dispatch_.Clear();
}
const ::infopack::DispatchProto& DecisionsListProto::dispatch(int index) const {
  // @@protoc_insertion_point(field_get:infopack.DecisionsListProto.dispatch)
  return dispatch_.Get(index);
}
::infopack::DispatchProto* DecisionsListProto::mutable_dispatch(int index) {
  // @@protoc_insertion_point(field_mutable:infopack.DecisionsListProto.dispatch)
  return dispatch_.Mutable(index);
}
::infopack::DispatchProto* DecisionsListProto::add_dispatch() {
  // @@protoc_insertion_point(field_add:infopack.DecisionsListProto.dispatch)
  return dispatch_.Add();
}
::google::protobuf::RepeatedPtrField< ::infopack::DispatchProto >*
DecisionsListProto::mutable_dispatch() {
  // @@protoc_insertion_point(field_mutable_list:infopack.DecisionsListProto.dispatch)
  return &dispatch_;
}
const ::google::protobuf::RepeatedPtrField< ::infopack::DispatchProto >&
DecisionsListProto::dispatch() const {
  // @@protoc_insertion_point(field_list:infopack.DecisionsListProto.dispatch)
  return dispatch_;
}

// repeated .infopack.ObjectsProto objects = 2;
int DecisionsListProto::objects_size() const {
  return objects_.size();
}
void DecisionsListProto::clear_objects() {
  objects_.Clear();
}
const ::infopack::ObjectsProto& DecisionsListProto::objects(int index) const {
  // @@protoc_insertion_point(field_get:infopack.DecisionsListProto.objects)
  return objects_.Get(index);
}
::infopack::ObjectsProto* DecisionsListProto::mutable_objects(int index) {
  // @@protoc_insertion_point(field_mutable:infopack.DecisionsListProto.objects)
  return objects_.Mutable(index);
}
::infopack::ObjectsProto* DecisionsListProto::add_objects() {
  // @@protoc_insertion_point(field_add:infopack.DecisionsListProto.objects)
  return objects_.Add();
}
::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >*
DecisionsListProto::mutable_objects() {
  // @@protoc_insertion_point(field_mutable_list:infopack.DecisionsListProto.objects)
  return &objects_;
}
const ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >&
DecisionsListProto::objects() const {
  // @@protoc_insertion_point(field_list:infopack.DecisionsListProto.objects)
  return objects_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace infopack

// @@protoc_insertion_point(global_scope)
