// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: objects.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "objects.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace infopack {

namespace {

const ::google::protobuf::Descriptor* ObjectsProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ObjectsProto_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_objects_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_objects_2eproto() {
  protobuf_AddDesc_objects_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "objects.proto");
  GOOGLE_CHECK(file != NULL);
  ObjectsProto_descriptor_ = file->message_type(0);
  static const int ObjectsProto_offsets_[16] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, objectid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, lat_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, lon_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, yaw_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, velocity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, power_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, finish_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, len_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, height_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, vctype_),
  };
  ObjectsProto_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ObjectsProto_descriptor_,
      ObjectsProto::default_instance_,
      ObjectsProto_offsets_,
      -1,
      -1,
      -1,
      sizeof(ObjectsProto),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsProto, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_objects_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ObjectsProto_descriptor_, &ObjectsProto::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_objects_2eproto() {
  delete ObjectsProto::default_instance_;
  delete ObjectsProto_reflection_;
}

void protobuf_AddDesc_objects_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_objects_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\robjects.proto\022\010infopack\"\373\001\n\014ObjectsPro"
    "to\022\014\n\004type\030\001 \001(\005\022\020\n\010objectid\030\002 \001(\005\022\013\n\003la"
    "t\030\003 \001(\001\022\013\n\003lon\030\004 \001(\001\022\t\n\001x\030\005 \001(\001\022\t\n\001y\030\006 \001"
    "(\001\022\013\n\003yaw\030\007 \001(\001\022\020\n\010velocity\030\010 \001(\001\022\r\n\005pow"
    "er\030\t \001(\001\022\016\n\006finish\030\n \001(\010\022\013\n\003len\030\013 \001(\005\022\r\n"
    "\005width\030\014 \001(\005\022\016\n\006height\030\r \001(\005\022\021\n\ttimestam"
    "p\030\016 \001(\003\022\016\n\006status\030\017 \001(\005\022\016\n\006vctype\030\020 \001(\005b"
    "\006proto3", 287);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "objects.proto", &protobuf_RegisterTypes);
  ObjectsProto::default_instance_ = new ObjectsProto();
  ObjectsProto::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_objects_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_objects_2eproto {
  StaticDescriptorInitializer_objects_2eproto() {
    protobuf_AddDesc_objects_2eproto();
  }
} static_descriptor_initializer_objects_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ObjectsProto::kTypeFieldNumber;
const int ObjectsProto::kObjectidFieldNumber;
const int ObjectsProto::kLatFieldNumber;
const int ObjectsProto::kLonFieldNumber;
const int ObjectsProto::kXFieldNumber;
const int ObjectsProto::kYFieldNumber;
const int ObjectsProto::kYawFieldNumber;
const int ObjectsProto::kVelocityFieldNumber;
const int ObjectsProto::kPowerFieldNumber;
const int ObjectsProto::kFinishFieldNumber;
const int ObjectsProto::kLenFieldNumber;
const int ObjectsProto::kWidthFieldNumber;
const int ObjectsProto::kHeightFieldNumber;
const int ObjectsProto::kTimestampFieldNumber;
const int ObjectsProto::kStatusFieldNumber;
const int ObjectsProto::kVctypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ObjectsProto::ObjectsProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:infopack.ObjectsProto)
}

void ObjectsProto::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ObjectsProto::ObjectsProto(const ObjectsProto& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:infopack.ObjectsProto)
}

void ObjectsProto::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  type_ = 0;
  objectid_ = 0;
  lat_ = 0;
  lon_ = 0;
  x_ = 0;
  y_ = 0;
  yaw_ = 0;
  velocity_ = 0;
  power_ = 0;
  finish_ = false;
  len_ = 0;
  width_ = 0;
  height_ = 0;
  timestamp_ = GOOGLE_LONGLONG(0);
  status_ = 0;
  vctype_ = 0;
}

ObjectsProto::~ObjectsProto() {
  // @@protoc_insertion_point(destructor:infopack.ObjectsProto)
  SharedDtor();
}

void ObjectsProto::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ObjectsProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ObjectsProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ObjectsProto_descriptor_;
}

const ObjectsProto& ObjectsProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_objects_2eproto();
  return *default_instance_;
}

ObjectsProto* ObjectsProto::default_instance_ = NULL;

ObjectsProto* ObjectsProto::New(::google::protobuf::Arena* arena) const {
  ObjectsProto* n = new ObjectsProto;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ObjectsProto::Clear() {
// @@protoc_insertion_point(message_clear_start:infopack.ObjectsProto)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(ObjectsProto, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<ObjectsProto*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(type_, velocity_);
  ZR_(power_, vctype_);

#undef ZR_HELPER_
#undef ZR_

}

bool ObjectsProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:infopack.ObjectsProto)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 type = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_objectid;
        break;
      }

      // optional int32 objectid = 2;
      case 2: {
        if (tag == 16) {
         parse_objectid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &objectid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_lat;
        break;
      }

      // optional double lat = 3;
      case 3: {
        if (tag == 25) {
         parse_lat:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &lat_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_lon;
        break;
      }

      // optional double lon = 4;
      case 4: {
        if (tag == 33) {
         parse_lon:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &lon_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(41)) goto parse_x;
        break;
      }

      // optional double x = 5;
      case 5: {
        if (tag == 41) {
         parse_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(49)) goto parse_y;
        break;
      }

      // optional double y = 6;
      case 6: {
        if (tag == 49) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(57)) goto parse_yaw;
        break;
      }

      // optional double yaw = 7;
      case 7: {
        if (tag == 57) {
         parse_yaw:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &yaw_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(65)) goto parse_velocity;
        break;
      }

      // optional double velocity = 8;
      case 8: {
        if (tag == 65) {
         parse_velocity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &velocity_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(73)) goto parse_power;
        break;
      }

      // optional double power = 9;
      case 9: {
        if (tag == 73) {
         parse_power:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &power_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(80)) goto parse_finish;
        break;
      }

      // optional bool finish = 10;
      case 10: {
        if (tag == 80) {
         parse_finish:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &finish_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(88)) goto parse_len;
        break;
      }

      // optional int32 len = 11;
      case 11: {
        if (tag == 88) {
         parse_len:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &len_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(96)) goto parse_width;
        break;
      }

      // optional int32 width = 12;
      case 12: {
        if (tag == 96) {
         parse_width:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &width_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(104)) goto parse_height;
        break;
      }

      // optional int32 height = 13;
      case 13: {
        if (tag == 104) {
         parse_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &height_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(112)) goto parse_timestamp;
        break;
      }

      // optional int64 timestamp = 14;
      case 14: {
        if (tag == 112) {
         parse_timestamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &timestamp_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(120)) goto parse_status;
        break;
      }

      // optional int32 status = 15;
      case 15: {
        if (tag == 120) {
         parse_status:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &status_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(128)) goto parse_vctype;
        break;
      }

      // optional int32 vctype = 16;
      case 16: {
        if (tag == 128) {
         parse_vctype:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &vctype_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:infopack.ObjectsProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:infopack.ObjectsProto)
  return false;
#undef DO_
}

void ObjectsProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:infopack.ObjectsProto)
  // optional int32 type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->type(), output);
  }

  // optional int32 objectid = 2;
  if (this->objectid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->objectid(), output);
  }

  // optional double lat = 3;
  if (this->lat() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->lat(), output);
  }

  // optional double lon = 4;
  if (this->lon() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->lon(), output);
  }

  // optional double x = 5;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->x(), output);
  }

  // optional double y = 6;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->y(), output);
  }

  // optional double yaw = 7;
  if (this->yaw() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->yaw(), output);
  }

  // optional double velocity = 8;
  if (this->velocity() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->velocity(), output);
  }

  // optional double power = 9;
  if (this->power() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->power(), output);
  }

  // optional bool finish = 10;
  if (this->finish() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(10, this->finish(), output);
  }

  // optional int32 len = 11;
  if (this->len() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(11, this->len(), output);
  }

  // optional int32 width = 12;
  if (this->width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(12, this->width(), output);
  }

  // optional int32 height = 13;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(13, this->height(), output);
  }

  // optional int64 timestamp = 14;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(14, this->timestamp(), output);
  }

  // optional int32 status = 15;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(15, this->status(), output);
  }

  // optional int32 vctype = 16;
  if (this->vctype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(16, this->vctype(), output);
  }

  // @@protoc_insertion_point(serialize_end:infopack.ObjectsProto)
}

::google::protobuf::uint8* ObjectsProto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:infopack.ObjectsProto)
  // optional int32 type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->type(), target);
  }

  // optional int32 objectid = 2;
  if (this->objectid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->objectid(), target);
  }

  // optional double lat = 3;
  if (this->lat() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->lat(), target);
  }

  // optional double lon = 4;
  if (this->lon() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->lon(), target);
  }

  // optional double x = 5;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->x(), target);
  }

  // optional double y = 6;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->y(), target);
  }

  // optional double yaw = 7;
  if (this->yaw() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->yaw(), target);
  }

  // optional double velocity = 8;
  if (this->velocity() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->velocity(), target);
  }

  // optional double power = 9;
  if (this->power() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->power(), target);
  }

  // optional bool finish = 10;
  if (this->finish() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(10, this->finish(), target);
  }

  // optional int32 len = 11;
  if (this->len() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(11, this->len(), target);
  }

  // optional int32 width = 12;
  if (this->width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(12, this->width(), target);
  }

  // optional int32 height = 13;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(13, this->height(), target);
  }

  // optional int64 timestamp = 14;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(14, this->timestamp(), target);
  }

  // optional int32 status = 15;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(15, this->status(), target);
  }

  // optional int32 vctype = 16;
  if (this->vctype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(16, this->vctype(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:infopack.ObjectsProto)
  return target;
}

int ObjectsProto::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:infopack.ObjectsProto)
  int total_size = 0;

  // optional int32 type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->type());
  }

  // optional int32 objectid = 2;
  if (this->objectid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->objectid());
  }

  // optional double lat = 3;
  if (this->lat() != 0) {
    total_size += 1 + 8;
  }

  // optional double lon = 4;
  if (this->lon() != 0) {
    total_size += 1 + 8;
  }

  // optional double x = 5;
  if (this->x() != 0) {
    total_size += 1 + 8;
  }

  // optional double y = 6;
  if (this->y() != 0) {
    total_size += 1 + 8;
  }

  // optional double yaw = 7;
  if (this->yaw() != 0) {
    total_size += 1 + 8;
  }

  // optional double velocity = 8;
  if (this->velocity() != 0) {
    total_size += 1 + 8;
  }

  // optional double power = 9;
  if (this->power() != 0) {
    total_size += 1 + 8;
  }

  // optional bool finish = 10;
  if (this->finish() != 0) {
    total_size += 1 + 1;
  }

  // optional int32 len = 11;
  if (this->len() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->len());
  }

  // optional int32 width = 12;
  if (this->width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->width());
  }

  // optional int32 height = 13;
  if (this->height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->height());
  }

  // optional int64 timestamp = 14;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->timestamp());
  }

  // optional int32 status = 15;
  if (this->status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->status());
  }

  // optional int32 vctype = 16;
  if (this->vctype() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->vctype());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ObjectsProto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:infopack.ObjectsProto)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ObjectsProto* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ObjectsProto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:infopack.ObjectsProto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:infopack.ObjectsProto)
    MergeFrom(*source);
  }
}

void ObjectsProto::MergeFrom(const ObjectsProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:infopack.ObjectsProto)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.objectid() != 0) {
    set_objectid(from.objectid());
  }
  if (from.lat() != 0) {
    set_lat(from.lat());
  }
  if (from.lon() != 0) {
    set_lon(from.lon());
  }
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.yaw() != 0) {
    set_yaw(from.yaw());
  }
  if (from.velocity() != 0) {
    set_velocity(from.velocity());
  }
  if (from.power() != 0) {
    set_power(from.power());
  }
  if (from.finish() != 0) {
    set_finish(from.finish());
  }
  if (from.len() != 0) {
    set_len(from.len());
  }
  if (from.width() != 0) {
    set_width(from.width());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
  if (from.status() != 0) {
    set_status(from.status());
  }
  if (from.vctype() != 0) {
    set_vctype(from.vctype());
  }
}

void ObjectsProto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:infopack.ObjectsProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObjectsProto::CopyFrom(const ObjectsProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:infopack.ObjectsProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObjectsProto::IsInitialized() const {

  return true;
}

void ObjectsProto::Swap(ObjectsProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ObjectsProto::InternalSwap(ObjectsProto* other) {
  std::swap(type_, other->type_);
  std::swap(objectid_, other->objectid_);
  std::swap(lat_, other->lat_);
  std::swap(lon_, other->lon_);
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(yaw_, other->yaw_);
  std::swap(velocity_, other->velocity_);
  std::swap(power_, other->power_);
  std::swap(finish_, other->finish_);
  std::swap(len_, other->len_);
  std::swap(width_, other->width_);
  std::swap(height_, other->height_);
  std::swap(timestamp_, other->timestamp_);
  std::swap(status_, other->status_);
  std::swap(vctype_, other->vctype_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ObjectsProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ObjectsProto_descriptor_;
  metadata.reflection = ObjectsProto_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ObjectsProto

// optional int32 type = 1;
void ObjectsProto::clear_type() {
  type_ = 0;
}
 ::google::protobuf::int32 ObjectsProto::type() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.type)
  return type_;
}
 void ObjectsProto::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.type)
}

// optional int32 objectid = 2;
void ObjectsProto::clear_objectid() {
  objectid_ = 0;
}
 ::google::protobuf::int32 ObjectsProto::objectid() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.objectid)
  return objectid_;
}
 void ObjectsProto::set_objectid(::google::protobuf::int32 value) {
  
  objectid_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.objectid)
}

// optional double lat = 3;
void ObjectsProto::clear_lat() {
  lat_ = 0;
}
 double ObjectsProto::lat() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.lat)
  return lat_;
}
 void ObjectsProto::set_lat(double value) {
  
  lat_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.lat)
}

// optional double lon = 4;
void ObjectsProto::clear_lon() {
  lon_ = 0;
}
 double ObjectsProto::lon() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.lon)
  return lon_;
}
 void ObjectsProto::set_lon(double value) {
  
  lon_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.lon)
}

// optional double x = 5;
void ObjectsProto::clear_x() {
  x_ = 0;
}
 double ObjectsProto::x() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.x)
  return x_;
}
 void ObjectsProto::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.x)
}

// optional double y = 6;
void ObjectsProto::clear_y() {
  y_ = 0;
}
 double ObjectsProto::y() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.y)
  return y_;
}
 void ObjectsProto::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.y)
}

// optional double yaw = 7;
void ObjectsProto::clear_yaw() {
  yaw_ = 0;
}
 double ObjectsProto::yaw() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.yaw)
  return yaw_;
}
 void ObjectsProto::set_yaw(double value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.yaw)
}

// optional double velocity = 8;
void ObjectsProto::clear_velocity() {
  velocity_ = 0;
}
 double ObjectsProto::velocity() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.velocity)
  return velocity_;
}
 void ObjectsProto::set_velocity(double value) {
  
  velocity_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.velocity)
}

// optional double power = 9;
void ObjectsProto::clear_power() {
  power_ = 0;
}
 double ObjectsProto::power() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.power)
  return power_;
}
 void ObjectsProto::set_power(double value) {
  
  power_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.power)
}

// optional bool finish = 10;
void ObjectsProto::clear_finish() {
  finish_ = false;
}
 bool ObjectsProto::finish() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.finish)
  return finish_;
}
 void ObjectsProto::set_finish(bool value) {
  
  finish_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.finish)
}

// optional int32 len = 11;
void ObjectsProto::clear_len() {
  len_ = 0;
}
 ::google::protobuf::int32 ObjectsProto::len() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.len)
  return len_;
}
 void ObjectsProto::set_len(::google::protobuf::int32 value) {
  
  len_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.len)
}

// optional int32 width = 12;
void ObjectsProto::clear_width() {
  width_ = 0;
}
 ::google::protobuf::int32 ObjectsProto::width() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.width)
  return width_;
}
 void ObjectsProto::set_width(::google::protobuf::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.width)
}

// optional int32 height = 13;
void ObjectsProto::clear_height() {
  height_ = 0;
}
 ::google::protobuf::int32 ObjectsProto::height() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.height)
  return height_;
}
 void ObjectsProto::set_height(::google::protobuf::int32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.height)
}

// optional int64 timestamp = 14;
void ObjectsProto::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 ObjectsProto::timestamp() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.timestamp)
  return timestamp_;
}
 void ObjectsProto::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.timestamp)
}

// optional int32 status = 15;
void ObjectsProto::clear_status() {
  status_ = 0;
}
 ::google::protobuf::int32 ObjectsProto::status() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.status)
  return status_;
}
 void ObjectsProto::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.status)
}

// optional int32 vctype = 16;
void ObjectsProto::clear_vctype() {
  vctype_ = 0;
}
 ::google::protobuf::int32 ObjectsProto::vctype() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.vctype)
  return vctype_;
}
 void ObjectsProto::set_vctype(::google::protobuf::int32 value) {
  
  vctype_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.vctype)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace infopack

// @@protoc_insertion_point(global_scope)
