// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: objects.proto

#ifndef PROTOBUF_objects_2eproto__INCLUDED
#define PROTOBUF_objects_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace infopack {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_objects_2eproto();
void protobuf_AssignDesc_objects_2eproto();
void protobuf_ShutdownFile_objects_2eproto();

class ObjectsProto;

// ===================================================================

class ObjectsProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:infopack.ObjectsProto) */ {
 public:
  ObjectsProto();
  virtual ~ObjectsProto();

  ObjectsProto(const ObjectsProto& from);

  inline ObjectsProto& operator=(const ObjectsProto& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectsProto& default_instance();

  void Swap(ObjectsProto* other);

  // implements Message ----------------------------------------------

  inline ObjectsProto* New() const { return New(NULL); }

  ObjectsProto* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObjectsProto& from);
  void MergeFrom(const ObjectsProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ObjectsProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // optional int32 objectid = 2;
  void clear_objectid();
  static const int kObjectidFieldNumber = 2;
  ::google::protobuf::int32 objectid() const;
  void set_objectid(::google::protobuf::int32 value);

  // optional double lat = 3;
  void clear_lat();
  static const int kLatFieldNumber = 3;
  double lat() const;
  void set_lat(double value);

  // optional double lon = 4;
  void clear_lon();
  static const int kLonFieldNumber = 4;
  double lon() const;
  void set_lon(double value);

  // optional double x = 5;
  void clear_x();
  static const int kXFieldNumber = 5;
  double x() const;
  void set_x(double value);

  // optional double y = 6;
  void clear_y();
  static const int kYFieldNumber = 6;
  double y() const;
  void set_y(double value);

  // optional double yaw = 7;
  void clear_yaw();
  static const int kYawFieldNumber = 7;
  double yaw() const;
  void set_yaw(double value);

  // optional double velocity = 8;
  void clear_velocity();
  static const int kVelocityFieldNumber = 8;
  double velocity() const;
  void set_velocity(double value);

  // optional double power = 9;
  void clear_power();
  static const int kPowerFieldNumber = 9;
  double power() const;
  void set_power(double value);

  // optional bool finish = 10;
  void clear_finish();
  static const int kFinishFieldNumber = 10;
  bool finish() const;
  void set_finish(bool value);

  // optional int32 len = 11;
  void clear_len();
  static const int kLenFieldNumber = 11;
  ::google::protobuf::int32 len() const;
  void set_len(::google::protobuf::int32 value);

  // optional int32 width = 12;
  void clear_width();
  static const int kWidthFieldNumber = 12;
  ::google::protobuf::int32 width() const;
  void set_width(::google::protobuf::int32 value);

  // optional int32 height = 13;
  void clear_height();
  static const int kHeightFieldNumber = 13;
  ::google::protobuf::int32 height() const;
  void set_height(::google::protobuf::int32 value);

  // optional int64 timestamp = 14;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 14;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // optional int32 status = 15;
  void clear_status();
  static const int kStatusFieldNumber = 15;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // optional int32 vctype = 16;
  void clear_vctype();
  static const int kVctypeFieldNumber = 16;
  ::google::protobuf::int32 vctype() const;
  void set_vctype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:infopack.ObjectsProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 objectid_;
  double lat_;
  double lon_;
  double x_;
  double y_;
  double yaw_;
  double velocity_;
  double power_;
  bool finish_;
  ::google::protobuf::int32 len_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;
  ::google::protobuf::int64 timestamp_;
  ::google::protobuf::int32 status_;
  ::google::protobuf::int32 vctype_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_objects_2eproto();
  friend void protobuf_AssignDesc_objects_2eproto();
  friend void protobuf_ShutdownFile_objects_2eproto();

  void InitAsDefaultInstance();
  static ObjectsProto* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ObjectsProto

// optional int32 type = 1;
inline void ObjectsProto::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 ObjectsProto::type() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.type)
  return type_;
}
inline void ObjectsProto::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.type)
}

// optional int32 objectid = 2;
inline void ObjectsProto::clear_objectid() {
  objectid_ = 0;
}
inline ::google::protobuf::int32 ObjectsProto::objectid() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.objectid)
  return objectid_;
}
inline void ObjectsProto::set_objectid(::google::protobuf::int32 value) {
  
  objectid_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.objectid)
}

// optional double lat = 3;
inline void ObjectsProto::clear_lat() {
  lat_ = 0;
}
inline double ObjectsProto::lat() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.lat)
  return lat_;
}
inline void ObjectsProto::set_lat(double value) {
  
  lat_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.lat)
}

// optional double lon = 4;
inline void ObjectsProto::clear_lon() {
  lon_ = 0;
}
inline double ObjectsProto::lon() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.lon)
  return lon_;
}
inline void ObjectsProto::set_lon(double value) {
  
  lon_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.lon)
}

// optional double x = 5;
inline void ObjectsProto::clear_x() {
  x_ = 0;
}
inline double ObjectsProto::x() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.x)
  return x_;
}
inline void ObjectsProto::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.x)
}

// optional double y = 6;
inline void ObjectsProto::clear_y() {
  y_ = 0;
}
inline double ObjectsProto::y() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.y)
  return y_;
}
inline void ObjectsProto::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.y)
}

// optional double yaw = 7;
inline void ObjectsProto::clear_yaw() {
  yaw_ = 0;
}
inline double ObjectsProto::yaw() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.yaw)
  return yaw_;
}
inline void ObjectsProto::set_yaw(double value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.yaw)
}

// optional double velocity = 8;
inline void ObjectsProto::clear_velocity() {
  velocity_ = 0;
}
inline double ObjectsProto::velocity() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.velocity)
  return velocity_;
}
inline void ObjectsProto::set_velocity(double value) {
  
  velocity_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.velocity)
}

// optional double power = 9;
inline void ObjectsProto::clear_power() {
  power_ = 0;
}
inline double ObjectsProto::power() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.power)
  return power_;
}
inline void ObjectsProto::set_power(double value) {
  
  power_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.power)
}

// optional bool finish = 10;
inline void ObjectsProto::clear_finish() {
  finish_ = false;
}
inline bool ObjectsProto::finish() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.finish)
  return finish_;
}
inline void ObjectsProto::set_finish(bool value) {
  
  finish_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.finish)
}

// optional int32 len = 11;
inline void ObjectsProto::clear_len() {
  len_ = 0;
}
inline ::google::protobuf::int32 ObjectsProto::len() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.len)
  return len_;
}
inline void ObjectsProto::set_len(::google::protobuf::int32 value) {
  
  len_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.len)
}

// optional int32 width = 12;
inline void ObjectsProto::clear_width() {
  width_ = 0;
}
inline ::google::protobuf::int32 ObjectsProto::width() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.width)
  return width_;
}
inline void ObjectsProto::set_width(::google::protobuf::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.width)
}

// optional int32 height = 13;
inline void ObjectsProto::clear_height() {
  height_ = 0;
}
inline ::google::protobuf::int32 ObjectsProto::height() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.height)
  return height_;
}
inline void ObjectsProto::set_height(::google::protobuf::int32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.height)
}

// optional int64 timestamp = 14;
inline void ObjectsProto::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ObjectsProto::timestamp() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.timestamp)
  return timestamp_;
}
inline void ObjectsProto::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.timestamp)
}

// optional int32 status = 15;
inline void ObjectsProto::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 ObjectsProto::status() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.status)
  return status_;
}
inline void ObjectsProto::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.status)
}

// optional int32 vctype = 16;
inline void ObjectsProto::clear_vctype() {
  vctype_ = 0;
}
inline ::google::protobuf::int32 ObjectsProto::vctype() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsProto.vctype)
  return vctype_;
}
inline void ObjectsProto::set_vctype(::google::protobuf::int32 value) {
  
  vctype_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsProto.vctype)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace infopack

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_objects_2eproto__INCLUDED
