// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: objectsvec.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "objectsvec.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace infopack {

namespace {

const ::google::protobuf::Descriptor* ObjectsVec_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ObjectsVec_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_objectsvec_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_objectsvec_2eproto() {
  protobuf_AddDesc_objectsvec_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "objectsvec.proto");
  GOOGLE_CHECK(file != NULL);
  ObjectsVec_descriptor_ = file->message_type(0);
  static const int ObjectsVec_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsVec, objmsg_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsVec, sensorid_),
  };
  ObjectsVec_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ObjectsVec_descriptor_,
      ObjectsVec::default_instance_,
      ObjectsVec_offsets_,
      -1,
      -1,
      -1,
      sizeof(ObjectsVec),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsVec, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectsVec, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_objectsvec_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ObjectsVec_descriptor_, &ObjectsVec::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_objectsvec_2eproto() {
  delete ObjectsVec::default_instance_;
  delete ObjectsVec_reflection_;
}

void protobuf_AddDesc_objectsvec_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_objectsvec_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::infopack::protobuf_AddDesc_objects_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020objectsvec.proto\022\010infopack\032\robjects.pr"
    "oto\"F\n\nObjectsVec\022&\n\006objMsg\030\001 \003(\0132\026.info"
    "pack.ObjectsProto\022\020\n\010sensorid\030\002 \001(\005b\006pro"
    "to3", 123);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "objectsvec.proto", &protobuf_RegisterTypes);
  ObjectsVec::default_instance_ = new ObjectsVec();
  ObjectsVec::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_objectsvec_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_objectsvec_2eproto {
  StaticDescriptorInitializer_objectsvec_2eproto() {
    protobuf_AddDesc_objectsvec_2eproto();
  }
} static_descriptor_initializer_objectsvec_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ObjectsVec::kObjMsgFieldNumber;
const int ObjectsVec::kSensoridFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ObjectsVec::ObjectsVec()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:infopack.ObjectsVec)
}

void ObjectsVec::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ObjectsVec::ObjectsVec(const ObjectsVec& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:infopack.ObjectsVec)
}

void ObjectsVec::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  sensorid_ = 0;
}

ObjectsVec::~ObjectsVec() {
  // @@protoc_insertion_point(destructor:infopack.ObjectsVec)
  SharedDtor();
}

void ObjectsVec::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ObjectsVec::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ObjectsVec::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ObjectsVec_descriptor_;
}

const ObjectsVec& ObjectsVec::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_objectsvec_2eproto();
  return *default_instance_;
}

ObjectsVec* ObjectsVec::default_instance_ = NULL;

ObjectsVec* ObjectsVec::New(::google::protobuf::Arena* arena) const {
  ObjectsVec* n = new ObjectsVec;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ObjectsVec::Clear() {
// @@protoc_insertion_point(message_clear_start:infopack.ObjectsVec)
  sensorid_ = 0;
  objmsg_.Clear();
}

bool ObjectsVec::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:infopack.ObjectsVec)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .infopack.ObjectsProto objMsg = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_objMsg:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_objmsg()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_objMsg;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(16)) goto parse_sensorid;
        break;
      }

      // optional int32 sensorid = 2;
      case 2: {
        if (tag == 16) {
         parse_sensorid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sensorid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:infopack.ObjectsVec)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:infopack.ObjectsVec)
  return false;
#undef DO_
}

void ObjectsVec::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:infopack.ObjectsVec)
  // repeated .infopack.ObjectsProto objMsg = 1;
  for (unsigned int i = 0, n = this->objmsg_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->objmsg(i), output);
  }

  // optional int32 sensorid = 2;
  if (this->sensorid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->sensorid(), output);
  }

  // @@protoc_insertion_point(serialize_end:infopack.ObjectsVec)
}

::google::protobuf::uint8* ObjectsVec::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:infopack.ObjectsVec)
  // repeated .infopack.ObjectsProto objMsg = 1;
  for (unsigned int i = 0, n = this->objmsg_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->objmsg(i), false, target);
  }

  // optional int32 sensorid = 2;
  if (this->sensorid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->sensorid(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:infopack.ObjectsVec)
  return target;
}

int ObjectsVec::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:infopack.ObjectsVec)
  int total_size = 0;

  // optional int32 sensorid = 2;
  if (this->sensorid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sensorid());
  }

  // repeated .infopack.ObjectsProto objMsg = 1;
  total_size += 1 * this->objmsg_size();
  for (int i = 0; i < this->objmsg_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->objmsg(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ObjectsVec::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:infopack.ObjectsVec)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ObjectsVec* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ObjectsVec>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:infopack.ObjectsVec)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:infopack.ObjectsVec)
    MergeFrom(*source);
  }
}

void ObjectsVec::MergeFrom(const ObjectsVec& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:infopack.ObjectsVec)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  objmsg_.MergeFrom(from.objmsg_);
  if (from.sensorid() != 0) {
    set_sensorid(from.sensorid());
  }
}

void ObjectsVec::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:infopack.ObjectsVec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObjectsVec::CopyFrom(const ObjectsVec& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:infopack.ObjectsVec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObjectsVec::IsInitialized() const {

  return true;
}

void ObjectsVec::Swap(ObjectsVec* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ObjectsVec::InternalSwap(ObjectsVec* other) {
  objmsg_.UnsafeArenaSwap(&other->objmsg_);
  std::swap(sensorid_, other->sensorid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ObjectsVec::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ObjectsVec_descriptor_;
  metadata.reflection = ObjectsVec_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ObjectsVec

// repeated .infopack.ObjectsProto objMsg = 1;
int ObjectsVec::objmsg_size() const {
  return objmsg_.size();
}
void ObjectsVec::clear_objmsg() {
  objmsg_.Clear();
}
const ::infopack::ObjectsProto& ObjectsVec::objmsg(int index) const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsVec.objMsg)
  return objmsg_.Get(index);
}
::infopack::ObjectsProto* ObjectsVec::mutable_objmsg(int index) {
  // @@protoc_insertion_point(field_mutable:infopack.ObjectsVec.objMsg)
  return objmsg_.Mutable(index);
}
::infopack::ObjectsProto* ObjectsVec::add_objmsg() {
  // @@protoc_insertion_point(field_add:infopack.ObjectsVec.objMsg)
  return objmsg_.Add();
}
::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >*
ObjectsVec::mutable_objmsg() {
  // @@protoc_insertion_point(field_mutable_list:infopack.ObjectsVec.objMsg)
  return &objmsg_;
}
const ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >&
ObjectsVec::objmsg() const {
  // @@protoc_insertion_point(field_list:infopack.ObjectsVec.objMsg)
  return objmsg_;
}

// optional int32 sensorid = 2;
void ObjectsVec::clear_sensorid() {
  sensorid_ = 0;
}
 ::google::protobuf::int32 ObjectsVec::sensorid() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsVec.sensorid)
  return sensorid_;
}
 void ObjectsVec::set_sensorid(::google::protobuf::int32 value) {
  
  sensorid_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsVec.sensorid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace infopack

// @@protoc_insertion_point(global_scope)
