// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: objectsvec.proto

#ifndef PROTOBUF_objectsvec_2eproto__INCLUDED
#define PROTOBUF_objectsvec_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "objects.pb.h"
// @@protoc_insertion_point(includes)

namespace infopack {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_objectsvec_2eproto();
void protobuf_AssignDesc_objectsvec_2eproto();
void protobuf_ShutdownFile_objectsvec_2eproto();

class ObjectsVec;

// ===================================================================

class ObjectsVec : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:infopack.ObjectsVec) */ {
 public:
  ObjectsVec();
  virtual ~ObjectsVec();

  ObjectsVec(const ObjectsVec& from);

  inline ObjectsVec& operator=(const ObjectsVec& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectsVec& default_instance();

  void Swap(ObjectsVec* other);

  // implements Message ----------------------------------------------

  inline ObjectsVec* New() const { return New(NULL); }

  ObjectsVec* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObjectsVec& from);
  void MergeFrom(const ObjectsVec& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ObjectsVec* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .infopack.ObjectsProto objMsg = 1;
  int objmsg_size() const;
  void clear_objmsg();
  static const int kObjMsgFieldNumber = 1;
  const ::infopack::ObjectsProto& objmsg(int index) const;
  ::infopack::ObjectsProto* mutable_objmsg(int index);
  ::infopack::ObjectsProto* add_objmsg();
  ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >*
      mutable_objmsg();
  const ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >&
      objmsg() const;

  // optional int32 sensorid = 2;
  void clear_sensorid();
  static const int kSensoridFieldNumber = 2;
  ::google::protobuf::int32 sensorid() const;
  void set_sensorid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:infopack.ObjectsVec)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto > objmsg_;
  ::google::protobuf::int32 sensorid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_objectsvec_2eproto();
  friend void protobuf_AssignDesc_objectsvec_2eproto();
  friend void protobuf_ShutdownFile_objectsvec_2eproto();

  void InitAsDefaultInstance();
  static ObjectsVec* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ObjectsVec

// repeated .infopack.ObjectsProto objMsg = 1;
inline int ObjectsVec::objmsg_size() const {
  return objmsg_.size();
}
inline void ObjectsVec::clear_objmsg() {
  objmsg_.Clear();
}
inline const ::infopack::ObjectsProto& ObjectsVec::objmsg(int index) const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsVec.objMsg)
  return objmsg_.Get(index);
}
inline ::infopack::ObjectsProto* ObjectsVec::mutable_objmsg(int index) {
  // @@protoc_insertion_point(field_mutable:infopack.ObjectsVec.objMsg)
  return objmsg_.Mutable(index);
}
inline ::infopack::ObjectsProto* ObjectsVec::add_objmsg() {
  // @@protoc_insertion_point(field_add:infopack.ObjectsVec.objMsg)
  return objmsg_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >*
ObjectsVec::mutable_objmsg() {
  // @@protoc_insertion_point(field_mutable_list:infopack.ObjectsVec.objMsg)
  return &objmsg_;
}
inline const ::google::protobuf::RepeatedPtrField< ::infopack::ObjectsProto >&
ObjectsVec::objmsg() const {
  // @@protoc_insertion_point(field_list:infopack.ObjectsVec.objMsg)
  return objmsg_;
}

// optional int32 sensorid = 2;
inline void ObjectsVec::clear_sensorid() {
  sensorid_ = 0;
}
inline ::google::protobuf::int32 ObjectsVec::sensorid() const {
  // @@protoc_insertion_point(field_get:infopack.ObjectsVec.sensorid)
  return sensorid_;
}
inline void ObjectsVec::set_sensorid(::google::protobuf::int32 value) {
  
  sensorid_ = value;
  // @@protoc_insertion_point(field_set:infopack.ObjectsVec.sensorid)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace infopack

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_objectsvec_2eproto__INCLUDED
