// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic_light.proto

#ifndef PROTOBUF_traffic_5flight_2eproto__INCLUDED
#define PROTOBUF_traffic_5flight_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace infopack {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_traffic_5flight_2eproto();
void protobuf_AssignDesc_traffic_5flight_2eproto();
void protobuf_ShutdownFile_traffic_5flight_2eproto();

class TrafficLight;

enum TrafficLight_State {
  TrafficLight_State_RED_LIGHT = 0,
  TrafficLight_State_YELLOW_LIGHT = 1,
  TrafficLight_State_GREEN_LIGHT = 2,
  TrafficLight_State_TrafficLight_State_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  TrafficLight_State_TrafficLight_State_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool TrafficLight_State_IsValid(int value);
const TrafficLight_State TrafficLight_State_State_MIN = TrafficLight_State_RED_LIGHT;
const TrafficLight_State TrafficLight_State_State_MAX = TrafficLight_State_GREEN_LIGHT;
const int TrafficLight_State_State_ARRAYSIZE = TrafficLight_State_State_MAX + 1;

const ::google::protobuf::EnumDescriptor* TrafficLight_State_descriptor();
inline const ::std::string& TrafficLight_State_Name(TrafficLight_State value) {
  return ::google::protobuf::internal::NameOfEnum(
    TrafficLight_State_descriptor(), value);
}
inline bool TrafficLight_State_Parse(
    const ::std::string& name, TrafficLight_State* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TrafficLight_State>(
    TrafficLight_State_descriptor(), name, value);
}
// ===================================================================

class TrafficLight : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:infopack.TrafficLight) */ {
 public:
  TrafficLight();
  virtual ~TrafficLight();

  TrafficLight(const TrafficLight& from);

  inline TrafficLight& operator=(const TrafficLight& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrafficLight& default_instance();

  void Swap(TrafficLight* other);

  // implements Message ----------------------------------------------

  inline TrafficLight* New() const { return New(NULL); }

  TrafficLight* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TrafficLight& from);
  void MergeFrom(const TrafficLight& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TrafficLight* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef TrafficLight_State State;
  static const State RED_LIGHT =
    TrafficLight_State_RED_LIGHT;
  static const State YELLOW_LIGHT =
    TrafficLight_State_YELLOW_LIGHT;
  static const State GREEN_LIGHT =
    TrafficLight_State_GREEN_LIGHT;
  static inline bool State_IsValid(int value) {
    return TrafficLight_State_IsValid(value);
  }
  static const State State_MIN =
    TrafficLight_State_State_MIN;
  static const State State_MAX =
    TrafficLight_State_State_MAX;
  static const int State_ARRAYSIZE =
    TrafficLight_State_State_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  State_descriptor() {
    return TrafficLight_State_descriptor();
  }
  static inline const ::std::string& State_Name(State value) {
    return TrafficLight_State_Name(value);
  }
  static inline bool State_Parse(const ::std::string& name,
      State* value) {
    return TrafficLight_State_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional bool active = 1;
  void clear_active();
  static const int kActiveFieldNumber = 1;
  bool active() const;
  void set_active(bool value);

  // optional .infopack.TrafficLight.State state = 2;
  void clear_state();
  static const int kStateFieldNumber = 2;
  ::infopack::TrafficLight_State state() const;
  void set_state(::infopack::TrafficLight_State value);

  // optional double remaining_time = 3;
  void clear_remaining_time();
  static const int kRemainingTimeFieldNumber = 3;
  double remaining_time() const;
  void set_remaining_time(double value);

  // optional double lane_length_before_intersection = 4;
  void clear_lane_length_before_intersection();
  static const int kLaneLengthBeforeIntersectionFieldNumber = 4;
  double lane_length_before_intersection() const;
  void set_lane_length_before_intersection(double value);

  // @@protoc_insertion_point(class_scope:infopack.TrafficLight)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  bool active_;
  int state_;
  double remaining_time_;
  double lane_length_before_intersection_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_traffic_5flight_2eproto();
  friend void protobuf_AssignDesc_traffic_5flight_2eproto();
  friend void protobuf_ShutdownFile_traffic_5flight_2eproto();

  void InitAsDefaultInstance();
  static TrafficLight* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TrafficLight

// optional bool active = 1;
inline void TrafficLight::clear_active() {
  active_ = false;
}
inline bool TrafficLight::active() const {
  // @@protoc_insertion_point(field_get:infopack.TrafficLight.active)
  return active_;
}
inline void TrafficLight::set_active(bool value) {
  
  active_ = value;
  // @@protoc_insertion_point(field_set:infopack.TrafficLight.active)
}

// optional .infopack.TrafficLight.State state = 2;
inline void TrafficLight::clear_state() {
  state_ = 0;
}
inline ::infopack::TrafficLight_State TrafficLight::state() const {
  // @@protoc_insertion_point(field_get:infopack.TrafficLight.state)
  return static_cast< ::infopack::TrafficLight_State >(state_);
}
inline void TrafficLight::set_state(::infopack::TrafficLight_State value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:infopack.TrafficLight.state)
}

// optional double remaining_time = 3;
inline void TrafficLight::clear_remaining_time() {
  remaining_time_ = 0;
}
inline double TrafficLight::remaining_time() const {
  // @@protoc_insertion_point(field_get:infopack.TrafficLight.remaining_time)
  return remaining_time_;
}
inline void TrafficLight::set_remaining_time(double value) {
  
  remaining_time_ = value;
  // @@protoc_insertion_point(field_set:infopack.TrafficLight.remaining_time)
}

// optional double lane_length_before_intersection = 4;
inline void TrafficLight::clear_lane_length_before_intersection() {
  lane_length_before_intersection_ = 0;
}
inline double TrafficLight::lane_length_before_intersection() const {
  // @@protoc_insertion_point(field_get:infopack.TrafficLight.lane_length_before_intersection)
  return lane_length_before_intersection_;
}
inline void TrafficLight::set_lane_length_before_intersection(double value) {
  
  lane_length_before_intersection_ = value;
  // @@protoc_insertion_point(field_set:infopack.TrafficLight.lane_length_before_intersection)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace infopack

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::infopack::TrafficLight_State> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::infopack::TrafficLight_State>() {
  return ::infopack::TrafficLight_State_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_traffic_5flight_2eproto__INCLUDED
