// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traffic_light.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "traffic_light.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace infopack {

namespace {

const ::google::protobuf::Descriptor* TrafficLight_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TrafficLight_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* TrafficLight_State_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_traffic_5flight_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_traffic_5flight_2eproto() {
  protobuf_AddDesc_traffic_5flight_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "traffic_light.proto");
  GOOGLE_CHECK(file != NULL);
  TrafficLight_descriptor_ = file->message_type(0);
  static const int TrafficLight_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrafficLight, active_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrafficLight, state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrafficLight, remaining_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrafficLight, lane_length_before_intersection_),
  };
  TrafficLight_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TrafficLight_descriptor_,
      TrafficLight::default_instance_,
      TrafficLight_offsets_,
      -1,
      -1,
      -1,
      sizeof(TrafficLight),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrafficLight, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrafficLight, _is_default_instance_));
  TrafficLight_State_descriptor_ = TrafficLight_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_traffic_5flight_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TrafficLight_descriptor_, &TrafficLight::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_traffic_5flight_2eproto() {
  delete TrafficLight::default_instance_;
  delete TrafficLight_reflection_;
}

void protobuf_AddDesc_traffic_5flight_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_traffic_5flight_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023traffic_light.proto\022\010infopack\"\307\001\n\014Traf"
    "ficLight\022\016\n\006active\030\001 \001(\010\022+\n\005state\030\002 \001(\0162"
    "\034.infopack.TrafficLight.State\022\026\n\016remaini"
    "ng_time\030\003 \001(\001\022\'\n\037lane_length_before_inte"
    "rsection\030\004 \001(\001\"9\n\005State\022\r\n\tRED_LIGHT\020\000\022\020"
    "\n\014YELLOW_LIGHT\020\001\022\017\n\013GREEN_LIGHT\020\002b\006proto"
    "3", 241);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "traffic_light.proto", &protobuf_RegisterTypes);
  TrafficLight::default_instance_ = new TrafficLight();
  TrafficLight::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_traffic_5flight_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_traffic_5flight_2eproto {
  StaticDescriptorInitializer_traffic_5flight_2eproto() {
    protobuf_AddDesc_traffic_5flight_2eproto();
  }
} static_descriptor_initializer_traffic_5flight_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* TrafficLight_State_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TrafficLight_State_descriptor_;
}
bool TrafficLight_State_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const TrafficLight_State TrafficLight::RED_LIGHT;
const TrafficLight_State TrafficLight::YELLOW_LIGHT;
const TrafficLight_State TrafficLight::GREEN_LIGHT;
const TrafficLight_State TrafficLight::State_MIN;
const TrafficLight_State TrafficLight::State_MAX;
const int TrafficLight::State_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TrafficLight::kActiveFieldNumber;
const int TrafficLight::kStateFieldNumber;
const int TrafficLight::kRemainingTimeFieldNumber;
const int TrafficLight::kLaneLengthBeforeIntersectionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TrafficLight::TrafficLight()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:infopack.TrafficLight)
}

void TrafficLight::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

TrafficLight::TrafficLight(const TrafficLight& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:infopack.TrafficLight)
}

void TrafficLight::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  active_ = false;
  state_ = 0;
  remaining_time_ = 0;
  lane_length_before_intersection_ = 0;
}

TrafficLight::~TrafficLight() {
  // @@protoc_insertion_point(destructor:infopack.TrafficLight)
  SharedDtor();
}

void TrafficLight::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TrafficLight::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TrafficLight::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TrafficLight_descriptor_;
}

const TrafficLight& TrafficLight::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_traffic_5flight_2eproto();
  return *default_instance_;
}

TrafficLight* TrafficLight::default_instance_ = NULL;

TrafficLight* TrafficLight::New(::google::protobuf::Arena* arena) const {
  TrafficLight* n = new TrafficLight;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TrafficLight::Clear() {
// @@protoc_insertion_point(message_clear_start:infopack.TrafficLight)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(TrafficLight, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<TrafficLight*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(active_, lane_length_before_intersection_);

#undef ZR_HELPER_
#undef ZR_

}

bool TrafficLight::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:infopack.TrafficLight)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool active = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &active_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_state;
        break;
      }

      // optional .infopack.TrafficLight.State state = 2;
      case 2: {
        if (tag == 16) {
         parse_state:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_state(static_cast< ::infopack::TrafficLight_State >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_remaining_time;
        break;
      }

      // optional double remaining_time = 3;
      case 3: {
        if (tag == 25) {
         parse_remaining_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &remaining_time_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_lane_length_before_intersection;
        break;
      }

      // optional double lane_length_before_intersection = 4;
      case 4: {
        if (tag == 33) {
         parse_lane_length_before_intersection:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &lane_length_before_intersection_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:infopack.TrafficLight)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:infopack.TrafficLight)
  return false;
#undef DO_
}

void TrafficLight::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:infopack.TrafficLight)
  // optional bool active = 1;
  if (this->active() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->active(), output);
  }

  // optional .infopack.TrafficLight.State state = 2;
  if (this->state() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->state(), output);
  }

  // optional double remaining_time = 3;
  if (this->remaining_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->remaining_time(), output);
  }

  // optional double lane_length_before_intersection = 4;
  if (this->lane_length_before_intersection() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->lane_length_before_intersection(), output);
  }

  // @@protoc_insertion_point(serialize_end:infopack.TrafficLight)
}

::google::protobuf::uint8* TrafficLight::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:infopack.TrafficLight)
  // optional bool active = 1;
  if (this->active() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->active(), target);
  }

  // optional .infopack.TrafficLight.State state = 2;
  if (this->state() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->state(), target);
  }

  // optional double remaining_time = 3;
  if (this->remaining_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->remaining_time(), target);
  }

  // optional double lane_length_before_intersection = 4;
  if (this->lane_length_before_intersection() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->lane_length_before_intersection(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:infopack.TrafficLight)
  return target;
}

int TrafficLight::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:infopack.TrafficLight)
  int total_size = 0;

  // optional bool active = 1;
  if (this->active() != 0) {
    total_size += 1 + 1;
  }

  // optional .infopack.TrafficLight.State state = 2;
  if (this->state() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->state());
  }

  // optional double remaining_time = 3;
  if (this->remaining_time() != 0) {
    total_size += 1 + 8;
  }

  // optional double lane_length_before_intersection = 4;
  if (this->lane_length_before_intersection() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TrafficLight::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:infopack.TrafficLight)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const TrafficLight* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const TrafficLight>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:infopack.TrafficLight)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:infopack.TrafficLight)
    MergeFrom(*source);
  }
}

void TrafficLight::MergeFrom(const TrafficLight& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:infopack.TrafficLight)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.active() != 0) {
    set_active(from.active());
  }
  if (from.state() != 0) {
    set_state(from.state());
  }
  if (from.remaining_time() != 0) {
    set_remaining_time(from.remaining_time());
  }
  if (from.lane_length_before_intersection() != 0) {
    set_lane_length_before_intersection(from.lane_length_before_intersection());
  }
}

void TrafficLight::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:infopack.TrafficLight)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TrafficLight::CopyFrom(const TrafficLight& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:infopack.TrafficLight)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrafficLight::IsInitialized() const {

  return true;
}

void TrafficLight::Swap(TrafficLight* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TrafficLight::InternalSwap(TrafficLight* other) {
  std::swap(active_, other->active_);
  std::swap(state_, other->state_);
  std::swap(remaining_time_, other->remaining_time_);
  std::swap(lane_length_before_intersection_, other->lane_length_before_intersection_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TrafficLight::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TrafficLight_descriptor_;
  metadata.reflection = TrafficLight_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TrafficLight

// optional bool active = 1;
void TrafficLight::clear_active() {
  active_ = false;
}
 bool TrafficLight::active() const {
  // @@protoc_insertion_point(field_get:infopack.TrafficLight.active)
  return active_;
}
 void TrafficLight::set_active(bool value) {
  
  active_ = value;
  // @@protoc_insertion_point(field_set:infopack.TrafficLight.active)
}

// optional .infopack.TrafficLight.State state = 2;
void TrafficLight::clear_state() {
  state_ = 0;
}
 ::infopack::TrafficLight_State TrafficLight::state() const {
  // @@protoc_insertion_point(field_get:infopack.TrafficLight.state)
  return static_cast< ::infopack::TrafficLight_State >(state_);
}
 void TrafficLight::set_state(::infopack::TrafficLight_State value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:infopack.TrafficLight.state)
}

// optional double remaining_time = 3;
void TrafficLight::clear_remaining_time() {
  remaining_time_ = 0;
}
 double TrafficLight::remaining_time() const {
  // @@protoc_insertion_point(field_get:infopack.TrafficLight.remaining_time)
  return remaining_time_;
}
 void TrafficLight::set_remaining_time(double value) {
  
  remaining_time_ = value;
  // @@protoc_insertion_point(field_set:infopack.TrafficLight.remaining_time)
}

// optional double lane_length_before_intersection = 4;
void TrafficLight::clear_lane_length_before_intersection() {
  lane_length_before_intersection_ = 0;
}
 double TrafficLight::lane_length_before_intersection() const {
  // @@protoc_insertion_point(field_get:infopack.TrafficLight.lane_length_before_intersection)
  return lane_length_before_intersection_;
}
 void TrafficLight::set_lane_length_before_intersection(double value) {
  
  lane_length_before_intersection_ = value;
  // @@protoc_insertion_point(field_set:infopack.TrafficLight.lane_length_before_intersection)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace infopack

// @@protoc_insertion_point(global_scope)
