// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imu.proto

#ifndef PROTOBUF_INCLUDED_imu_2eproto
#define PROTOBUF_INCLUDED_imu_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_imu_2eproto 

namespace protobuf_imu_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_imu_2eproto
namespace IMU {
class Imu;
class ImuDefaultTypeInternal;
extern ImuDefaultTypeInternal _Imu_default_instance_;
}  // namespace IMU
namespace google {
namespace protobuf {
template<> ::IMU::Imu* Arena::CreateMaybeMessage<::IMU::Imu>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace IMU {

// ===================================================================

class Imu : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:IMU.Imu) */ {
 public:
  Imu();
  virtual ~Imu();

  Imu(const Imu& from);

  inline Imu& operator=(const Imu& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Imu(Imu&& from) noexcept
    : Imu() {
    *this = ::std::move(from);
  }

  inline Imu& operator=(Imu&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Imu& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Imu* internal_default_instance() {
    return reinterpret_cast<const Imu*>(
               &_Imu_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Imu* other);
  friend void swap(Imu& a, Imu& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Imu* New() const final {
    return CreateMaybeMessage<Imu>(NULL);
  }

  Imu* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Imu>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Imu& from);
  void MergeFrom(const Imu& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Imu* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double longitude = 1;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 1;
  double longitude() const;
  void set_longitude(double value);

  // double latitude = 2;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 2;
  double latitude() const;
  void set_latitude(double value);

  // double gaussX = 3;
  void clear_gaussx();
  static const int kGaussXFieldNumber = 3;
  double gaussx() const;
  void set_gaussx(double value);

  // double gaussY = 4;
  void clear_gaussy();
  static const int kGaussYFieldNumber = 4;
  double gaussy() const;
  void set_gaussy(double value);

  // double time = 6;
  void clear_time();
  static const int kTimeFieldNumber = 6;
  double time() const;
  void set_time(double value);

  // double velocity = 7;
  void clear_velocity();
  static const int kVelocityFieldNumber = 7;
  double velocity() const;
  void set_velocity(double value);

  // double yaw = 8;
  void clear_yaw();
  static const int kYawFieldNumber = 8;
  double yaw() const;
  void set_yaw(double value);

  // int64 ltime = 9;
  void clear_ltime();
  static const int kLtimeFieldNumber = 9;
  ::google::protobuf::int64 ltime() const;
  void set_ltime(::google::protobuf::int64 value);

  // double velocityEast = 10;
  void clear_velocityeast();
  static const int kVelocityEastFieldNumber = 10;
  double velocityeast() const;
  void set_velocityeast(double value);

  // double velocityNorth = 11;
  void clear_velocitynorth();
  static const int kVelocityNorthFieldNumber = 11;
  double velocitynorth() const;
  void set_velocitynorth(double value);

  // double velocityUp = 12;
  void clear_velocityup();
  static const int kVelocityUpFieldNumber = 12;
  double velocityup() const;
  void set_velocityup(double value);

  // double gyroX = 13;
  void clear_gyrox();
  static const int kGyroXFieldNumber = 13;
  double gyrox() const;
  void set_gyrox(double value);

  // double gyroY = 14;
  void clear_gyroy();
  static const int kGyroYFieldNumber = 14;
  double gyroy() const;
  void set_gyroy(double value);

  // double gyroZ = 15;
  void clear_gyroz();
  static const int kGyroZFieldNumber = 15;
  double gyroz() const;
  void set_gyroz(double value);

  // double accX = 16;
  void clear_accx();
  static const int kAccXFieldNumber = 16;
  double accx() const;
  void set_accx(double value);

  // double accY = 17;
  void clear_accy();
  static const int kAccYFieldNumber = 17;
  double accy() const;
  void set_accy(double value);

  // double accZ = 18;
  void clear_accz();
  static const int kAccZFieldNumber = 18;
  double accz() const;
  void set_accz(double value);

  // double pjatime = 19;
  void clear_pjatime();
  static const int kPjatimeFieldNumber = 19;
  double pjatime() const;
  void set_pjatime(double value);

  // double pitch = 20;
  void clear_pitch();
  static const int kPitchFieldNumber = 20;
  double pitch() const;
  void set_pitch(double value);

  // double roll = 21;
  void clear_roll();
  static const int kRollFieldNumber = 21;
  double roll() const;
  void set_roll(double value);

  // int32 gpsValid = 5;
  void clear_gpsvalid();
  static const int kGpsValidFieldNumber = 5;
  ::google::protobuf::int32 gpsvalid() const;
  void set_gpsvalid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:IMU.Imu)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double longitude_;
  double latitude_;
  double gaussx_;
  double gaussy_;
  double time_;
  double velocity_;
  double yaw_;
  ::google::protobuf::int64 ltime_;
  double velocityeast_;
  double velocitynorth_;
  double velocityup_;
  double gyrox_;
  double gyroy_;
  double gyroz_;
  double accx_;
  double accy_;
  double accz_;
  double pjatime_;
  double pitch_;
  double roll_;
  ::google::protobuf::int32 gpsvalid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_imu_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Imu

// double longitude = 1;
inline void Imu::clear_longitude() {
  longitude_ = 0;
}
inline double Imu::longitude() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.longitude)
  return longitude_;
}
inline void Imu::set_longitude(double value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.longitude)
}

// double latitude = 2;
inline void Imu::clear_latitude() {
  latitude_ = 0;
}
inline double Imu::latitude() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.latitude)
  return latitude_;
}
inline void Imu::set_latitude(double value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.latitude)
}

// double gaussX = 3;
inline void Imu::clear_gaussx() {
  gaussx_ = 0;
}
inline double Imu::gaussx() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.gaussX)
  return gaussx_;
}
inline void Imu::set_gaussx(double value) {
  
  gaussx_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.gaussX)
}

// double gaussY = 4;
inline void Imu::clear_gaussy() {
  gaussy_ = 0;
}
inline double Imu::gaussy() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.gaussY)
  return gaussy_;
}
inline void Imu::set_gaussy(double value) {
  
  gaussy_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.gaussY)
}

// int32 gpsValid = 5;
inline void Imu::clear_gpsvalid() {
  gpsvalid_ = 0;
}
inline ::google::protobuf::int32 Imu::gpsvalid() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.gpsValid)
  return gpsvalid_;
}
inline void Imu::set_gpsvalid(::google::protobuf::int32 value) {
  
  gpsvalid_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.gpsValid)
}

// double time = 6;
inline void Imu::clear_time() {
  time_ = 0;
}
inline double Imu::time() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.time)
  return time_;
}
inline void Imu::set_time(double value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.time)
}

// double velocity = 7;
inline void Imu::clear_velocity() {
  velocity_ = 0;
}
inline double Imu::velocity() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.velocity)
  return velocity_;
}
inline void Imu::set_velocity(double value) {
  
  velocity_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.velocity)
}

// double yaw = 8;
inline void Imu::clear_yaw() {
  yaw_ = 0;
}
inline double Imu::yaw() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.yaw)
  return yaw_;
}
inline void Imu::set_yaw(double value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.yaw)
}

// int64 ltime = 9;
inline void Imu::clear_ltime() {
  ltime_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Imu::ltime() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.ltime)
  return ltime_;
}
inline void Imu::set_ltime(::google::protobuf::int64 value) {
  
  ltime_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.ltime)
}

// double velocityEast = 10;
inline void Imu::clear_velocityeast() {
  velocityeast_ = 0;
}
inline double Imu::velocityeast() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.velocityEast)
  return velocityeast_;
}
inline void Imu::set_velocityeast(double value) {
  
  velocityeast_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.velocityEast)
}

// double velocityNorth = 11;
inline void Imu::clear_velocitynorth() {
  velocitynorth_ = 0;
}
inline double Imu::velocitynorth() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.velocityNorth)
  return velocitynorth_;
}
inline void Imu::set_velocitynorth(double value) {
  
  velocitynorth_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.velocityNorth)
}

// double velocityUp = 12;
inline void Imu::clear_velocityup() {
  velocityup_ = 0;
}
inline double Imu::velocityup() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.velocityUp)
  return velocityup_;
}
inline void Imu::set_velocityup(double value) {
  
  velocityup_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.velocityUp)
}

// double gyroX = 13;
inline void Imu::clear_gyrox() {
  gyrox_ = 0;
}
inline double Imu::gyrox() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.gyroX)
  return gyrox_;
}
inline void Imu::set_gyrox(double value) {
  
  gyrox_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.gyroX)
}

// double gyroY = 14;
inline void Imu::clear_gyroy() {
  gyroy_ = 0;
}
inline double Imu::gyroy() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.gyroY)
  return gyroy_;
}
inline void Imu::set_gyroy(double value) {
  
  gyroy_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.gyroY)
}

// double gyroZ = 15;
inline void Imu::clear_gyroz() {
  gyroz_ = 0;
}
inline double Imu::gyroz() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.gyroZ)
  return gyroz_;
}
inline void Imu::set_gyroz(double value) {
  
  gyroz_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.gyroZ)
}

// double accX = 16;
inline void Imu::clear_accx() {
  accx_ = 0;
}
inline double Imu::accx() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.accX)
  return accx_;
}
inline void Imu::set_accx(double value) {
  
  accx_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.accX)
}

// double accY = 17;
inline void Imu::clear_accy() {
  accy_ = 0;
}
inline double Imu::accy() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.accY)
  return accy_;
}
inline void Imu::set_accy(double value) {
  
  accy_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.accY)
}

// double accZ = 18;
inline void Imu::clear_accz() {
  accz_ = 0;
}
inline double Imu::accz() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.accZ)
  return accz_;
}
inline void Imu::set_accz(double value) {
  
  accz_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.accZ)
}

// double pjatime = 19;
inline void Imu::clear_pjatime() {
  pjatime_ = 0;
}
inline double Imu::pjatime() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.pjatime)
  return pjatime_;
}
inline void Imu::set_pjatime(double value) {
  
  pjatime_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.pjatime)
}

// double pitch = 20;
inline void Imu::clear_pitch() {
  pitch_ = 0;
}
inline double Imu::pitch() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.pitch)
  return pitch_;
}
inline void Imu::set_pitch(double value) {
  
  pitch_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.pitch)
}

// double roll = 21;
inline void Imu::clear_roll() {
  roll_ = 0;
}
inline double Imu::roll() const {
  // @@protoc_insertion_point(field_get:IMU.Imu.roll)
  return roll_;
}
inline void Imu::set_roll(double value) {
  
  roll_ = value;
  // @@protoc_insertion_point(field_set:IMU.Imu.roll)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace IMU

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_imu_2eproto
