// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imu.proto

#include "imu.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace IMU {
class ImuDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Imu>
      _instance;
} _Imu_default_instance_;
}  // namespace IMU
namespace protobuf_imu_2eproto {
static void InitDefaultsImu() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::IMU::_Imu_default_instance_;
    new (ptr) ::IMU::Imu();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::IMU::Imu::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Imu =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsImu}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Imu.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, longitude_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, latitude_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, gaussx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, gaussy_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, gpsvalid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, velocity_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, yaw_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, ltime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, velocityeast_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, velocitynorth_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, velocityup_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, gyrox_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, gyroy_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, gyroz_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, accx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, accy_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, accz_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, pjatime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, pitch_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::IMU::Imu, roll_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::IMU::Imu)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::IMU::_Imu_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "imu.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\timu.proto\022\003IMU\"\336\002\n\003Imu\022\021\n\tlongitude\030\001 "
      "\001(\001\022\020\n\010latitude\030\002 \001(\001\022\016\n\006gaussX\030\003 \001(\001\022\016\n"
      "\006gaussY\030\004 \001(\001\022\020\n\010gpsValid\030\005 \001(\005\022\014\n\004time\030"
      "\006 \001(\001\022\020\n\010velocity\030\007 \001(\001\022\013\n\003yaw\030\010 \001(\001\022\r\n\005"
      "ltime\030\t \001(\003\022\024\n\014velocityEast\030\n \001(\001\022\025\n\rvel"
      "ocityNorth\030\013 \001(\001\022\022\n\nvelocityUp\030\014 \001(\001\022\r\n\005"
      "gyroX\030\r \001(\001\022\r\n\005gyroY\030\016 \001(\001\022\r\n\005gyroZ\030\017 \001("
      "\001\022\014\n\004accX\030\020 \001(\001\022\014\n\004accY\030\021 \001(\001\022\014\n\004accZ\030\022 "
      "\001(\001\022\017\n\007pjatime\030\023 \001(\001\022\r\n\005pitch\030\024 \001(\001\022\014\n\004r"
      "oll\030\025 \001(\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 377);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "imu.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_imu_2eproto
namespace IMU {

// ===================================================================

void Imu::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Imu::kLongitudeFieldNumber;
const int Imu::kLatitudeFieldNumber;
const int Imu::kGaussXFieldNumber;
const int Imu::kGaussYFieldNumber;
const int Imu::kGpsValidFieldNumber;
const int Imu::kTimeFieldNumber;
const int Imu::kVelocityFieldNumber;
const int Imu::kYawFieldNumber;
const int Imu::kLtimeFieldNumber;
const int Imu::kVelocityEastFieldNumber;
const int Imu::kVelocityNorthFieldNumber;
const int Imu::kVelocityUpFieldNumber;
const int Imu::kGyroXFieldNumber;
const int Imu::kGyroYFieldNumber;
const int Imu::kGyroZFieldNumber;
const int Imu::kAccXFieldNumber;
const int Imu::kAccYFieldNumber;
const int Imu::kAccZFieldNumber;
const int Imu::kPjatimeFieldNumber;
const int Imu::kPitchFieldNumber;
const int Imu::kRollFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Imu::Imu()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_imu_2eproto::scc_info_Imu.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:IMU.Imu)
}
Imu::Imu(const Imu& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&longitude_, &from.longitude_,
    static_cast<size_t>(reinterpret_cast<char*>(&gpsvalid_) -
    reinterpret_cast<char*>(&longitude_)) + sizeof(gpsvalid_));
  // @@protoc_insertion_point(copy_constructor:IMU.Imu)
}

void Imu::SharedCtor() {
  ::memset(&longitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&gpsvalid_) -
      reinterpret_cast<char*>(&longitude_)) + sizeof(gpsvalid_));
}

Imu::~Imu() {
  // @@protoc_insertion_point(destructor:IMU.Imu)
  SharedDtor();
}

void Imu::SharedDtor() {
}

void Imu::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Imu::descriptor() {
  ::protobuf_imu_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_imu_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Imu& Imu::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_imu_2eproto::scc_info_Imu.base);
  return *internal_default_instance();
}


void Imu::Clear() {
// @@protoc_insertion_point(message_clear_start:IMU.Imu)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&longitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&gpsvalid_) -
      reinterpret_cast<char*>(&longitude_)) + sizeof(gpsvalid_));
  _internal_metadata_.Clear();
}

bool Imu::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:IMU.Imu)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double longitude = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &longitude_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double latitude = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &latitude_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double gaussX = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &gaussx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double gaussY = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &gaussy_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 gpsValid = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &gpsvalid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double time = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(49u /* 49 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double velocity = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(57u /* 57 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &velocity_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double yaw = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(65u /* 65 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &yaw_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 ltime = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &ltime_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double velocityEast = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(81u /* 81 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &velocityeast_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double velocityNorth = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(89u /* 89 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &velocitynorth_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double velocityUp = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(97u /* 97 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &velocityup_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double gyroX = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(105u /* 105 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &gyrox_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double gyroY = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(113u /* 113 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &gyroy_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double gyroZ = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(121u /* 121 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &gyroz_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double accX = 16;
      case 16: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(129u /* 129 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &accx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double accY = 17;
      case 17: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(137u /* 137 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &accy_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double accZ = 18;
      case 18: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(145u /* 145 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &accz_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double pjatime = 19;
      case 19: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(153u /* 153 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &pjatime_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double pitch = 20;
      case 20: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(161u /* 161 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &pitch_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double roll = 21;
      case 21: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(169u /* 169 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &roll_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:IMU.Imu)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:IMU.Imu)
  return false;
#undef DO_
}

void Imu::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:IMU.Imu)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double longitude = 1;
  if (this->longitude() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->longitude(), output);
  }

  // double latitude = 2;
  if (this->latitude() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->latitude(), output);
  }

  // double gaussX = 3;
  if (this->gaussx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->gaussx(), output);
  }

  // double gaussY = 4;
  if (this->gaussy() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->gaussy(), output);
  }

  // int32 gpsValid = 5;
  if (this->gpsvalid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->gpsvalid(), output);
  }

  // double time = 6;
  if (this->time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->time(), output);
  }

  // double velocity = 7;
  if (this->velocity() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->velocity(), output);
  }

  // double yaw = 8;
  if (this->yaw() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->yaw(), output);
  }

  // int64 ltime = 9;
  if (this->ltime() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(9, this->ltime(), output);
  }

  // double velocityEast = 10;
  if (this->velocityeast() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->velocityeast(), output);
  }

  // double velocityNorth = 11;
  if (this->velocitynorth() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(11, this->velocitynorth(), output);
  }

  // double velocityUp = 12;
  if (this->velocityup() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(12, this->velocityup(), output);
  }

  // double gyroX = 13;
  if (this->gyrox() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(13, this->gyrox(), output);
  }

  // double gyroY = 14;
  if (this->gyroy() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(14, this->gyroy(), output);
  }

  // double gyroZ = 15;
  if (this->gyroz() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(15, this->gyroz(), output);
  }

  // double accX = 16;
  if (this->accx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(16, this->accx(), output);
  }

  // double accY = 17;
  if (this->accy() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(17, this->accy(), output);
  }

  // double accZ = 18;
  if (this->accz() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(18, this->accz(), output);
  }

  // double pjatime = 19;
  if (this->pjatime() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(19, this->pjatime(), output);
  }

  // double pitch = 20;
  if (this->pitch() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(20, this->pitch(), output);
  }

  // double roll = 21;
  if (this->roll() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(21, this->roll(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:IMU.Imu)
}

::google::protobuf::uint8* Imu::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:IMU.Imu)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double longitude = 1;
  if (this->longitude() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->longitude(), target);
  }

  // double latitude = 2;
  if (this->latitude() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->latitude(), target);
  }

  // double gaussX = 3;
  if (this->gaussx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->gaussx(), target);
  }

  // double gaussY = 4;
  if (this->gaussy() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->gaussy(), target);
  }

  // int32 gpsValid = 5;
  if (this->gpsvalid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->gpsvalid(), target);
  }

  // double time = 6;
  if (this->time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->time(), target);
  }

  // double velocity = 7;
  if (this->velocity() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->velocity(), target);
  }

  // double yaw = 8;
  if (this->yaw() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->yaw(), target);
  }

  // int64 ltime = 9;
  if (this->ltime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(9, this->ltime(), target);
  }

  // double velocityEast = 10;
  if (this->velocityeast() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->velocityeast(), target);
  }

  // double velocityNorth = 11;
  if (this->velocitynorth() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(11, this->velocitynorth(), target);
  }

  // double velocityUp = 12;
  if (this->velocityup() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(12, this->velocityup(), target);
  }

  // double gyroX = 13;
  if (this->gyrox() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(13, this->gyrox(), target);
  }

  // double gyroY = 14;
  if (this->gyroy() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(14, this->gyroy(), target);
  }

  // double gyroZ = 15;
  if (this->gyroz() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(15, this->gyroz(), target);
  }

  // double accX = 16;
  if (this->accx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(16, this->accx(), target);
  }

  // double accY = 17;
  if (this->accy() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(17, this->accy(), target);
  }

  // double accZ = 18;
  if (this->accz() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(18, this->accz(), target);
  }

  // double pjatime = 19;
  if (this->pjatime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(19, this->pjatime(), target);
  }

  // double pitch = 20;
  if (this->pitch() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(20, this->pitch(), target);
  }

  // double roll = 21;
  if (this->roll() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(21, this->roll(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IMU.Imu)
  return target;
}

size_t Imu::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IMU.Imu)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // double longitude = 1;
  if (this->longitude() != 0) {
    total_size += 1 + 8;
  }

  // double latitude = 2;
  if (this->latitude() != 0) {
    total_size += 1 + 8;
  }

  // double gaussX = 3;
  if (this->gaussx() != 0) {
    total_size += 1 + 8;
  }

  // double gaussY = 4;
  if (this->gaussy() != 0) {
    total_size += 1 + 8;
  }

  // double time = 6;
  if (this->time() != 0) {
    total_size += 1 + 8;
  }

  // double velocity = 7;
  if (this->velocity() != 0) {
    total_size += 1 + 8;
  }

  // double yaw = 8;
  if (this->yaw() != 0) {
    total_size += 1 + 8;
  }

  // int64 ltime = 9;
  if (this->ltime() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->ltime());
  }

  // double velocityEast = 10;
  if (this->velocityeast() != 0) {
    total_size += 1 + 8;
  }

  // double velocityNorth = 11;
  if (this->velocitynorth() != 0) {
    total_size += 1 + 8;
  }

  // double velocityUp = 12;
  if (this->velocityup() != 0) {
    total_size += 1 + 8;
  }

  // double gyroX = 13;
  if (this->gyrox() != 0) {
    total_size += 1 + 8;
  }

  // double gyroY = 14;
  if (this->gyroy() != 0) {
    total_size += 1 + 8;
  }

  // double gyroZ = 15;
  if (this->gyroz() != 0) {
    total_size += 1 + 8;
  }

  // double accX = 16;
  if (this->accx() != 0) {
    total_size += 2 + 8;
  }

  // double accY = 17;
  if (this->accy() != 0) {
    total_size += 2 + 8;
  }

  // double accZ = 18;
  if (this->accz() != 0) {
    total_size += 2 + 8;
  }

  // double pjatime = 19;
  if (this->pjatime() != 0) {
    total_size += 2 + 8;
  }

  // double pitch = 20;
  if (this->pitch() != 0) {
    total_size += 2 + 8;
  }

  // double roll = 21;
  if (this->roll() != 0) {
    total_size += 2 + 8;
  }

  // int32 gpsValid = 5;
  if (this->gpsvalid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->gpsvalid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Imu::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:IMU.Imu)
  GOOGLE_DCHECK_NE(&from, this);
  const Imu* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Imu>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:IMU.Imu)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:IMU.Imu)
    MergeFrom(*source);
  }
}

void Imu::MergeFrom(const Imu& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:IMU.Imu)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.longitude() != 0) {
    set_longitude(from.longitude());
  }
  if (from.latitude() != 0) {
    set_latitude(from.latitude());
  }
  if (from.gaussx() != 0) {
    set_gaussx(from.gaussx());
  }
  if (from.gaussy() != 0) {
    set_gaussy(from.gaussy());
  }
  if (from.time() != 0) {
    set_time(from.time());
  }
  if (from.velocity() != 0) {
    set_velocity(from.velocity());
  }
  if (from.yaw() != 0) {
    set_yaw(from.yaw());
  }
  if (from.ltime() != 0) {
    set_ltime(from.ltime());
  }
  if (from.velocityeast() != 0) {
    set_velocityeast(from.velocityeast());
  }
  if (from.velocitynorth() != 0) {
    set_velocitynorth(from.velocitynorth());
  }
  if (from.velocityup() != 0) {
    set_velocityup(from.velocityup());
  }
  if (from.gyrox() != 0) {
    set_gyrox(from.gyrox());
  }
  if (from.gyroy() != 0) {
    set_gyroy(from.gyroy());
  }
  if (from.gyroz() != 0) {
    set_gyroz(from.gyroz());
  }
  if (from.accx() != 0) {
    set_accx(from.accx());
  }
  if (from.accy() != 0) {
    set_accy(from.accy());
  }
  if (from.accz() != 0) {
    set_accz(from.accz());
  }
  if (from.pjatime() != 0) {
    set_pjatime(from.pjatime());
  }
  if (from.pitch() != 0) {
    set_pitch(from.pitch());
  }
  if (from.roll() != 0) {
    set_roll(from.roll());
  }
  if (from.gpsvalid() != 0) {
    set_gpsvalid(from.gpsvalid());
  }
}

void Imu::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:IMU.Imu)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Imu::CopyFrom(const Imu& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IMU.Imu)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Imu::IsInitialized() const {
  return true;
}

void Imu::Swap(Imu* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Imu::InternalSwap(Imu* other) {
  using std::swap;
  swap(longitude_, other->longitude_);
  swap(latitude_, other->latitude_);
  swap(gaussx_, other->gaussx_);
  swap(gaussy_, other->gaussy_);
  swap(time_, other->time_);
  swap(velocity_, other->velocity_);
  swap(yaw_, other->yaw_);
  swap(ltime_, other->ltime_);
  swap(velocityeast_, other->velocityeast_);
  swap(velocitynorth_, other->velocitynorth_);
  swap(velocityup_, other->velocityup_);
  swap(gyrox_, other->gyrox_);
  swap(gyroy_, other->gyroy_);
  swap(gyroz_, other->gyroz_);
  swap(accx_, other->accx_);
  swap(accy_, other->accy_);
  swap(accz_, other->accz_);
  swap(pjatime_, other->pjatime_);
  swap(pitch_, other->pitch_);
  swap(roll_, other->roll_);
  swap(gpsvalid_, other->gpsvalid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Imu::GetMetadata() const {
  protobuf_imu_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_imu_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace IMU
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::IMU::Imu* Arena::CreateMaybeMessage< ::IMU::Imu >(Arena* arena) {
  return Arena::CreateInternal< ::IMU::Imu >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
