// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imu.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "imu.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pc {

namespace {

const ::google::protobuf::Descriptor* Imu_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Imu_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_imu_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_imu_2eproto() {
  protobuf_AddDesc_imu_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "imu.proto");
  GOOGLE_CHECK(file != NULL);
  Imu_descriptor_ = file->message_type(0);
  static const int Imu_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Imu, longitude_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Imu, latitude_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Imu, gaussx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Imu, gaussy_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Imu, gpsvalid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Imu, time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Imu, velocity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Imu, yaw_),
  };
  Imu_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Imu_descriptor_,
      Imu::default_instance_,
      Imu_offsets_,
      -1,
      -1,
      -1,
      sizeof(Imu),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Imu, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Imu, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_imu_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Imu_descriptor_, &Imu::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_imu_2eproto() {
  delete Imu::default_instance_;
  delete Imu_reflection_;
}

void protobuf_AddDesc_imu_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_imu_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\timu.proto\022\002pc\"\211\001\n\003Imu\022\021\n\tlongitude\030\001 \001"
    "(\001\022\020\n\010latitude\030\002 \001(\001\022\016\n\006gaussX\030\003 \001(\001\022\016\n\006"
    "gaussY\030\004 \001(\001\022\020\n\010gpsValid\030\005 \001(\005\022\014\n\004time\030\006"
    " \001(\001\022\020\n\010velocity\030\007 \001(\001\022\013\n\003yaw\030\010 \001(\001b\006pro"
    "to3", 163);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "imu.proto", &protobuf_RegisterTypes);
  Imu::default_instance_ = new Imu();
  Imu::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_imu_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_imu_2eproto {
  StaticDescriptorInitializer_imu_2eproto() {
    protobuf_AddDesc_imu_2eproto();
  }
} static_descriptor_initializer_imu_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Imu::kLongitudeFieldNumber;
const int Imu::kLatitudeFieldNumber;
const int Imu::kGaussXFieldNumber;
const int Imu::kGaussYFieldNumber;
const int Imu::kGpsValidFieldNumber;
const int Imu::kTimeFieldNumber;
const int Imu::kVelocityFieldNumber;
const int Imu::kYawFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Imu::Imu()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pc.Imu)
}

void Imu::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Imu::Imu(const Imu& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pc.Imu)
}

void Imu::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  longitude_ = 0;
  latitude_ = 0;
  gaussx_ = 0;
  gaussy_ = 0;
  gpsvalid_ = 0;
  time_ = 0;
  velocity_ = 0;
  yaw_ = 0;
}

Imu::~Imu() {
  // @@protoc_insertion_point(destructor:pc.Imu)
  SharedDtor();
}

void Imu::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Imu::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Imu::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Imu_descriptor_;
}

const Imu& Imu::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_imu_2eproto();
  return *default_instance_;
}

Imu* Imu::default_instance_ = NULL;

Imu* Imu::New(::google::protobuf::Arena* arena) const {
  Imu* n = new Imu;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Imu::Clear() {
// @@protoc_insertion_point(message_clear_start:pc.Imu)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Imu, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Imu*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(longitude_, gpsvalid_);

#undef ZR_HELPER_
#undef ZR_

}

bool Imu::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pc.Imu)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double longitude = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &longitude_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_latitude;
        break;
      }

      // optional double latitude = 2;
      case 2: {
        if (tag == 17) {
         parse_latitude:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &latitude_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_gaussX;
        break;
      }

      // optional double gaussX = 3;
      case 3: {
        if (tag == 25) {
         parse_gaussX:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &gaussx_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_gaussY;
        break;
      }

      // optional double gaussY = 4;
      case 4: {
        if (tag == 33) {
         parse_gaussY:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &gaussy_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_gpsValid;
        break;
      }

      // optional int32 gpsValid = 5;
      case 5: {
        if (tag == 40) {
         parse_gpsValid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &gpsvalid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(49)) goto parse_time;
        break;
      }

      // optional double time = 6;
      case 6: {
        if (tag == 49) {
         parse_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &time_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(57)) goto parse_velocity;
        break;
      }

      // optional double velocity = 7;
      case 7: {
        if (tag == 57) {
         parse_velocity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &velocity_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(65)) goto parse_yaw;
        break;
      }

      // optional double yaw = 8;
      case 8: {
        if (tag == 65) {
         parse_yaw:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &yaw_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pc.Imu)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pc.Imu)
  return false;
#undef DO_
}

void Imu::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pc.Imu)
  // optional double longitude = 1;
  if (this->longitude() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->longitude(), output);
  }

  // optional double latitude = 2;
  if (this->latitude() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->latitude(), output);
  }

  // optional double gaussX = 3;
  if (this->gaussx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->gaussx(), output);
  }

  // optional double gaussY = 4;
  if (this->gaussy() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->gaussy(), output);
  }

  // optional int32 gpsValid = 5;
  if (this->gpsvalid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->gpsvalid(), output);
  }

  // optional double time = 6;
  if (this->time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->time(), output);
  }

  // optional double velocity = 7;
  if (this->velocity() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->velocity(), output);
  }

  // optional double yaw = 8;
  if (this->yaw() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->yaw(), output);
  }

  // @@protoc_insertion_point(serialize_end:pc.Imu)
}

::google::protobuf::uint8* Imu::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pc.Imu)
  // optional double longitude = 1;
  if (this->longitude() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->longitude(), target);
  }

  // optional double latitude = 2;
  if (this->latitude() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->latitude(), target);
  }

  // optional double gaussX = 3;
  if (this->gaussx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->gaussx(), target);
  }

  // optional double gaussY = 4;
  if (this->gaussy() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->gaussy(), target);
  }

  // optional int32 gpsValid = 5;
  if (this->gpsvalid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->gpsvalid(), target);
  }

  // optional double time = 6;
  if (this->time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->time(), target);
  }

  // optional double velocity = 7;
  if (this->velocity() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->velocity(), target);
  }

  // optional double yaw = 8;
  if (this->yaw() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->yaw(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:pc.Imu)
  return target;
}

int Imu::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:pc.Imu)
  int total_size = 0;

  // optional double longitude = 1;
  if (this->longitude() != 0) {
    total_size += 1 + 8;
  }

  // optional double latitude = 2;
  if (this->latitude() != 0) {
    total_size += 1 + 8;
  }

  // optional double gaussX = 3;
  if (this->gaussx() != 0) {
    total_size += 1 + 8;
  }

  // optional double gaussY = 4;
  if (this->gaussy() != 0) {
    total_size += 1 + 8;
  }

  // optional int32 gpsValid = 5;
  if (this->gpsvalid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->gpsvalid());
  }

  // optional double time = 6;
  if (this->time() != 0) {
    total_size += 1 + 8;
  }

  // optional double velocity = 7;
  if (this->velocity() != 0) {
    total_size += 1 + 8;
  }

  // optional double yaw = 8;
  if (this->yaw() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Imu::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pc.Imu)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Imu* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Imu>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pc.Imu)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pc.Imu)
    MergeFrom(*source);
  }
}

void Imu::MergeFrom(const Imu& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pc.Imu)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.longitude() != 0) {
    set_longitude(from.longitude());
  }
  if (from.latitude() != 0) {
    set_latitude(from.latitude());
  }
  if (from.gaussx() != 0) {
    set_gaussx(from.gaussx());
  }
  if (from.gaussy() != 0) {
    set_gaussy(from.gaussy());
  }
  if (from.gpsvalid() != 0) {
    set_gpsvalid(from.gpsvalid());
  }
  if (from.time() != 0) {
    set_time(from.time());
  }
  if (from.velocity() != 0) {
    set_velocity(from.velocity());
  }
  if (from.yaw() != 0) {
    set_yaw(from.yaw());
  }
}

void Imu::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pc.Imu)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Imu::CopyFrom(const Imu& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pc.Imu)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Imu::IsInitialized() const {

  return true;
}

void Imu::Swap(Imu* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Imu::InternalSwap(Imu* other) {
  std::swap(longitude_, other->longitude_);
  std::swap(latitude_, other->latitude_);
  std::swap(gaussx_, other->gaussx_);
  std::swap(gaussy_, other->gaussy_);
  std::swap(gpsvalid_, other->gpsvalid_);
  std::swap(time_, other->time_);
  std::swap(velocity_, other->velocity_);
  std::swap(yaw_, other->yaw_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Imu::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Imu_descriptor_;
  metadata.reflection = Imu_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Imu

// optional double longitude = 1;
void Imu::clear_longitude() {
  longitude_ = 0;
}
 double Imu::longitude() const {
  // @@protoc_insertion_point(field_get:pc.Imu.longitude)
  return longitude_;
}
 void Imu::set_longitude(double value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:pc.Imu.longitude)
}

// optional double latitude = 2;
void Imu::clear_latitude() {
  latitude_ = 0;
}
 double Imu::latitude() const {
  // @@protoc_insertion_point(field_get:pc.Imu.latitude)
  return latitude_;
}
 void Imu::set_latitude(double value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:pc.Imu.latitude)
}

// optional double gaussX = 3;
void Imu::clear_gaussx() {
  gaussx_ = 0;
}
 double Imu::gaussx() const {
  // @@protoc_insertion_point(field_get:pc.Imu.gaussX)
  return gaussx_;
}
 void Imu::set_gaussx(double value) {
  
  gaussx_ = value;
  // @@protoc_insertion_point(field_set:pc.Imu.gaussX)
}

// optional double gaussY = 4;
void Imu::clear_gaussy() {
  gaussy_ = 0;
}
 double Imu::gaussy() const {
  // @@protoc_insertion_point(field_get:pc.Imu.gaussY)
  return gaussy_;
}
 void Imu::set_gaussy(double value) {
  
  gaussy_ = value;
  // @@protoc_insertion_point(field_set:pc.Imu.gaussY)
}

// optional int32 gpsValid = 5;
void Imu::clear_gpsvalid() {
  gpsvalid_ = 0;
}
 ::google::protobuf::int32 Imu::gpsvalid() const {
  // @@protoc_insertion_point(field_get:pc.Imu.gpsValid)
  return gpsvalid_;
}
 void Imu::set_gpsvalid(::google::protobuf::int32 value) {
  
  gpsvalid_ = value;
  // @@protoc_insertion_point(field_set:pc.Imu.gpsValid)
}

// optional double time = 6;
void Imu::clear_time() {
  time_ = 0;
}
 double Imu::time() const {
  // @@protoc_insertion_point(field_get:pc.Imu.time)
  return time_;
}
 void Imu::set_time(double value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:pc.Imu.time)
}

// optional double velocity = 7;
void Imu::clear_velocity() {
  velocity_ = 0;
}
 double Imu::velocity() const {
  // @@protoc_insertion_point(field_get:pc.Imu.velocity)
  return velocity_;
}
 void Imu::set_velocity(double value) {
  
  velocity_ = value;
  // @@protoc_insertion_point(field_set:pc.Imu.velocity)
}

// optional double yaw = 8;
void Imu::clear_yaw() {
  yaw_ = 0;
}
 double Imu::yaw() const {
  // @@protoc_insertion_point(field_get:pc.Imu.yaw)
  return yaw_;
}
 void Imu::set_yaw(double value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:pc.Imu.yaw)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pc

// @@protoc_insertion_point(global_scope)
