// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlanningMsg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PlanningMsg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Planning {

namespace {

const ::google::protobuf::Descriptor* TrajectoryPoint_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TrajectoryPoint_reflection_ = NULL;
const ::google::protobuf::Descriptor* TrajectoryPointVec_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TrajectoryPointVec_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_PlanningMsg_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_PlanningMsg_2eproto() {
  protobuf_AddDesc_PlanningMsg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "PlanningMsg.proto");
  GOOGLE_CHECK(file != NULL);
  TrajectoryPoint_descriptor_ = file->message_type(0);
  static const int TrajectoryPoint_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrajectoryPoint, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrajectoryPoint, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrajectoryPoint, theta_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrajectoryPoint, speed_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrajectoryPoint, curvature_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrajectoryPoint, s_),
  };
  TrajectoryPoint_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TrajectoryPoint_descriptor_,
      TrajectoryPoint::default_instance_,
      TrajectoryPoint_offsets_,
      -1,
      -1,
      -1,
      sizeof(TrajectoryPoint),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrajectoryPoint, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrajectoryPoint, _is_default_instance_));
  TrajectoryPointVec_descriptor_ = file->message_type(1);
  static const int TrajectoryPointVec_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrajectoryPointVec, trajectorypoints_),
  };
  TrajectoryPointVec_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      TrajectoryPointVec_descriptor_,
      TrajectoryPointVec::default_instance_,
      TrajectoryPointVec_offsets_,
      -1,
      -1,
      -1,
      sizeof(TrajectoryPointVec),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrajectoryPointVec, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrajectoryPointVec, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_PlanningMsg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TrajectoryPoint_descriptor_, &TrajectoryPoint::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      TrajectoryPointVec_descriptor_, &TrajectoryPointVec::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_PlanningMsg_2eproto() {
  delete TrajectoryPoint::default_instance_;
  delete TrajectoryPoint_reflection_;
  delete TrajectoryPointVec::default_instance_;
  delete TrajectoryPointVec_reflection_;
}

void protobuf_AddDesc_PlanningMsg_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_PlanningMsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021PlanningMsg.proto\022\010Planning\"c\n\017Traject"
    "oryPoint\022\t\n\001X\030\001 \001(\001\022\t\n\001Y\030\002 \001(\001\022\r\n\005Theta\030"
    "\003 \001(\001\022\r\n\005Speed\030\004 \001(\001\022\021\n\tCurvature\030\005 \001(\001\022"
    "\t\n\001S\030\006 \001(\001\"I\n\022TrajectoryPointVec\0223\n\020Traj"
    "ectoryPoints\030\001 \003(\0132\031.Planning.Trajectory"
    "Pointb\006proto3", 213);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PlanningMsg.proto", &protobuf_RegisterTypes);
  TrajectoryPoint::default_instance_ = new TrajectoryPoint();
  TrajectoryPointVec::default_instance_ = new TrajectoryPointVec();
  TrajectoryPoint::default_instance_->InitAsDefaultInstance();
  TrajectoryPointVec::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PlanningMsg_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PlanningMsg_2eproto {
  StaticDescriptorInitializer_PlanningMsg_2eproto() {
    protobuf_AddDesc_PlanningMsg_2eproto();
  }
} static_descriptor_initializer_PlanningMsg_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TrajectoryPoint::kXFieldNumber;
const int TrajectoryPoint::kYFieldNumber;
const int TrajectoryPoint::kThetaFieldNumber;
const int TrajectoryPoint::kSpeedFieldNumber;
const int TrajectoryPoint::kCurvatureFieldNumber;
const int TrajectoryPoint::kSFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TrajectoryPoint::TrajectoryPoint()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Planning.TrajectoryPoint)
}

void TrajectoryPoint::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

TrajectoryPoint::TrajectoryPoint(const TrajectoryPoint& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Planning.TrajectoryPoint)
}

void TrajectoryPoint::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  x_ = 0;
  y_ = 0;
  theta_ = 0;
  speed_ = 0;
  curvature_ = 0;
  s_ = 0;
}

TrajectoryPoint::~TrajectoryPoint() {
  // @@protoc_insertion_point(destructor:Planning.TrajectoryPoint)
  SharedDtor();
}

void TrajectoryPoint::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TrajectoryPoint::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TrajectoryPoint::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TrajectoryPoint_descriptor_;
}

const TrajectoryPoint& TrajectoryPoint::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PlanningMsg_2eproto();
  return *default_instance_;
}

TrajectoryPoint* TrajectoryPoint::default_instance_ = NULL;

TrajectoryPoint* TrajectoryPoint::New(::google::protobuf::Arena* arena) const {
  TrajectoryPoint* n = new TrajectoryPoint;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TrajectoryPoint::Clear() {
// @@protoc_insertion_point(message_clear_start:Planning.TrajectoryPoint)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(TrajectoryPoint, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<TrajectoryPoint*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(x_, s_);

#undef ZR_HELPER_
#undef ZR_

}

bool TrajectoryPoint::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Planning.TrajectoryPoint)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double X = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_Y;
        break;
      }

      // optional double Y = 2;
      case 2: {
        if (tag == 17) {
         parse_Y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_Theta;
        break;
      }

      // optional double Theta = 3;
      case 3: {
        if (tag == 25) {
         parse_Theta:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &theta_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_Speed;
        break;
      }

      // optional double Speed = 4;
      case 4: {
        if (tag == 33) {
         parse_Speed:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &speed_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(41)) goto parse_Curvature;
        break;
      }

      // optional double Curvature = 5;
      case 5: {
        if (tag == 41) {
         parse_Curvature:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &curvature_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(49)) goto parse_S;
        break;
      }

      // optional double S = 6;
      case 6: {
        if (tag == 49) {
         parse_S:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &s_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Planning.TrajectoryPoint)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Planning.TrajectoryPoint)
  return false;
#undef DO_
}

void TrajectoryPoint::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Planning.TrajectoryPoint)
  // optional double X = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->x(), output);
  }

  // optional double Y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->y(), output);
  }

  // optional double Theta = 3;
  if (this->theta() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->theta(), output);
  }

  // optional double Speed = 4;
  if (this->speed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->speed(), output);
  }

  // optional double Curvature = 5;
  if (this->curvature() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->curvature(), output);
  }

  // optional double S = 6;
  if (this->s() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->s(), output);
  }

  // @@protoc_insertion_point(serialize_end:Planning.TrajectoryPoint)
}

::google::protobuf::uint8* TrajectoryPoint::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Planning.TrajectoryPoint)
  // optional double X = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->x(), target);
  }

  // optional double Y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->y(), target);
  }

  // optional double Theta = 3;
  if (this->theta() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->theta(), target);
  }

  // optional double Speed = 4;
  if (this->speed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->speed(), target);
  }

  // optional double Curvature = 5;
  if (this->curvature() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->curvature(), target);
  }

  // optional double S = 6;
  if (this->s() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->s(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Planning.TrajectoryPoint)
  return target;
}

int TrajectoryPoint::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Planning.TrajectoryPoint)
  int total_size = 0;

  // optional double X = 1;
  if (this->x() != 0) {
    total_size += 1 + 8;
  }

  // optional double Y = 2;
  if (this->y() != 0) {
    total_size += 1 + 8;
  }

  // optional double Theta = 3;
  if (this->theta() != 0) {
    total_size += 1 + 8;
  }

  // optional double Speed = 4;
  if (this->speed() != 0) {
    total_size += 1 + 8;
  }

  // optional double Curvature = 5;
  if (this->curvature() != 0) {
    total_size += 1 + 8;
  }

  // optional double S = 6;
  if (this->s() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TrajectoryPoint::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Planning.TrajectoryPoint)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const TrajectoryPoint* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const TrajectoryPoint>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Planning.TrajectoryPoint)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Planning.TrajectoryPoint)
    MergeFrom(*source);
  }
}

void TrajectoryPoint::MergeFrom(const TrajectoryPoint& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Planning.TrajectoryPoint)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.theta() != 0) {
    set_theta(from.theta());
  }
  if (from.speed() != 0) {
    set_speed(from.speed());
  }
  if (from.curvature() != 0) {
    set_curvature(from.curvature());
  }
  if (from.s() != 0) {
    set_s(from.s());
  }
}

void TrajectoryPoint::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Planning.TrajectoryPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TrajectoryPoint::CopyFrom(const TrajectoryPoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Planning.TrajectoryPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrajectoryPoint::IsInitialized() const {

  return true;
}

void TrajectoryPoint::Swap(TrajectoryPoint* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TrajectoryPoint::InternalSwap(TrajectoryPoint* other) {
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(theta_, other->theta_);
  std::swap(speed_, other->speed_);
  std::swap(curvature_, other->curvature_);
  std::swap(s_, other->s_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TrajectoryPoint::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TrajectoryPoint_descriptor_;
  metadata.reflection = TrajectoryPoint_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TrajectoryPoint

// optional double X = 1;
void TrajectoryPoint::clear_x() {
  x_ = 0;
}
 double TrajectoryPoint::x() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.X)
  return x_;
}
 void TrajectoryPoint::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.X)
}

// optional double Y = 2;
void TrajectoryPoint::clear_y() {
  y_ = 0;
}
 double TrajectoryPoint::y() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.Y)
  return y_;
}
 void TrajectoryPoint::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.Y)
}

// optional double Theta = 3;
void TrajectoryPoint::clear_theta() {
  theta_ = 0;
}
 double TrajectoryPoint::theta() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.Theta)
  return theta_;
}
 void TrajectoryPoint::set_theta(double value) {
  
  theta_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.Theta)
}

// optional double Speed = 4;
void TrajectoryPoint::clear_speed() {
  speed_ = 0;
}
 double TrajectoryPoint::speed() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.Speed)
  return speed_;
}
 void TrajectoryPoint::set_speed(double value) {
  
  speed_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.Speed)
}

// optional double Curvature = 5;
void TrajectoryPoint::clear_curvature() {
  curvature_ = 0;
}
 double TrajectoryPoint::curvature() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.Curvature)
  return curvature_;
}
 void TrajectoryPoint::set_curvature(double value) {
  
  curvature_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.Curvature)
}

// optional double S = 6;
void TrajectoryPoint::clear_s() {
  s_ = 0;
}
 double TrajectoryPoint::s() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.S)
  return s_;
}
 void TrajectoryPoint::set_s(double value) {
  
  s_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.S)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TrajectoryPointVec::kTrajectoryPointsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TrajectoryPointVec::TrajectoryPointVec()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Planning.TrajectoryPointVec)
}

void TrajectoryPointVec::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

TrajectoryPointVec::TrajectoryPointVec(const TrajectoryPointVec& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Planning.TrajectoryPointVec)
}

void TrajectoryPointVec::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

TrajectoryPointVec::~TrajectoryPointVec() {
  // @@protoc_insertion_point(destructor:Planning.TrajectoryPointVec)
  SharedDtor();
}

void TrajectoryPointVec::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TrajectoryPointVec::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TrajectoryPointVec::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TrajectoryPointVec_descriptor_;
}

const TrajectoryPointVec& TrajectoryPointVec::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PlanningMsg_2eproto();
  return *default_instance_;
}

TrajectoryPointVec* TrajectoryPointVec::default_instance_ = NULL;

TrajectoryPointVec* TrajectoryPointVec::New(::google::protobuf::Arena* arena) const {
  TrajectoryPointVec* n = new TrajectoryPointVec;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TrajectoryPointVec::Clear() {
// @@protoc_insertion_point(message_clear_start:Planning.TrajectoryPointVec)
  trajectorypoints_.Clear();
}

bool TrajectoryPointVec::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Planning.TrajectoryPointVec)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Planning.TrajectoryPoint TrajectoryPoints = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_TrajectoryPoints:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_trajectorypoints()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_TrajectoryPoints;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Planning.TrajectoryPointVec)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Planning.TrajectoryPointVec)
  return false;
#undef DO_
}

void TrajectoryPointVec::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Planning.TrajectoryPointVec)
  // repeated .Planning.TrajectoryPoint TrajectoryPoints = 1;
  for (unsigned int i = 0, n = this->trajectorypoints_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->trajectorypoints(i), output);
  }

  // @@protoc_insertion_point(serialize_end:Planning.TrajectoryPointVec)
}

::google::protobuf::uint8* TrajectoryPointVec::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Planning.TrajectoryPointVec)
  // repeated .Planning.TrajectoryPoint TrajectoryPoints = 1;
  for (unsigned int i = 0, n = this->trajectorypoints_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->trajectorypoints(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Planning.TrajectoryPointVec)
  return target;
}

int TrajectoryPointVec::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Planning.TrajectoryPointVec)
  int total_size = 0;

  // repeated .Planning.TrajectoryPoint TrajectoryPoints = 1;
  total_size += 1 * this->trajectorypoints_size();
  for (int i = 0; i < this->trajectorypoints_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->trajectorypoints(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TrajectoryPointVec::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Planning.TrajectoryPointVec)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const TrajectoryPointVec* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const TrajectoryPointVec>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Planning.TrajectoryPointVec)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Planning.TrajectoryPointVec)
    MergeFrom(*source);
  }
}

void TrajectoryPointVec::MergeFrom(const TrajectoryPointVec& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Planning.TrajectoryPointVec)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  trajectorypoints_.MergeFrom(from.trajectorypoints_);
}

void TrajectoryPointVec::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Planning.TrajectoryPointVec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TrajectoryPointVec::CopyFrom(const TrajectoryPointVec& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Planning.TrajectoryPointVec)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrajectoryPointVec::IsInitialized() const {

  return true;
}

void TrajectoryPointVec::Swap(TrajectoryPointVec* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TrajectoryPointVec::InternalSwap(TrajectoryPointVec* other) {
  trajectorypoints_.UnsafeArenaSwap(&other->trajectorypoints_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TrajectoryPointVec::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TrajectoryPointVec_descriptor_;
  metadata.reflection = TrajectoryPointVec_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// TrajectoryPointVec

// repeated .Planning.TrajectoryPoint TrajectoryPoints = 1;
int TrajectoryPointVec::trajectorypoints_size() const {
  return trajectorypoints_.size();
}
void TrajectoryPointVec::clear_trajectorypoints() {
  trajectorypoints_.Clear();
}
const ::Planning::TrajectoryPoint& TrajectoryPointVec::trajectorypoints(int index) const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPointVec.TrajectoryPoints)
  return trajectorypoints_.Get(index);
}
::Planning::TrajectoryPoint* TrajectoryPointVec::mutable_trajectorypoints(int index) {
  // @@protoc_insertion_point(field_mutable:Planning.TrajectoryPointVec.TrajectoryPoints)
  return trajectorypoints_.Mutable(index);
}
::Planning::TrajectoryPoint* TrajectoryPointVec::add_trajectorypoints() {
  // @@protoc_insertion_point(field_add:Planning.TrajectoryPointVec.TrajectoryPoints)
  return trajectorypoints_.Add();
}
::google::protobuf::RepeatedPtrField< ::Planning::TrajectoryPoint >*
TrajectoryPointVec::mutable_trajectorypoints() {
  // @@protoc_insertion_point(field_mutable_list:Planning.TrajectoryPointVec.TrajectoryPoints)
  return &trajectorypoints_;
}
const ::google::protobuf::RepeatedPtrField< ::Planning::TrajectoryPoint >&
TrajectoryPointVec::trajectorypoints() const {
  // @@protoc_insertion_point(field_list:Planning.TrajectoryPointVec.TrajectoryPoints)
  return trajectorypoints_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Planning

// @@protoc_insertion_point(global_scope)
