// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlanningMsg.proto

#ifndef PROTOBUF_PlanningMsg_2eproto__INCLUDED
#define PROTOBUF_PlanningMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Planning {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_PlanningMsg_2eproto();
void protobuf_AssignDesc_PlanningMsg_2eproto();
void protobuf_ShutdownFile_PlanningMsg_2eproto();

class TrajectoryPoint;
class TrajectoryPointVec;

// ===================================================================

class TrajectoryPoint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Planning.TrajectoryPoint) */ {
 public:
  TrajectoryPoint();
  virtual ~TrajectoryPoint();

  TrajectoryPoint(const TrajectoryPoint& from);

  inline TrajectoryPoint& operator=(const TrajectoryPoint& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrajectoryPoint& default_instance();

  void Swap(TrajectoryPoint* other);

  // implements Message ----------------------------------------------

  inline TrajectoryPoint* New() const { return New(NULL); }

  TrajectoryPoint* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TrajectoryPoint& from);
  void MergeFrom(const TrajectoryPoint& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TrajectoryPoint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double X = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // optional double Y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // optional double Theta = 3;
  void clear_theta();
  static const int kThetaFieldNumber = 3;
  double theta() const;
  void set_theta(double value);

  // optional double Speed = 4;
  void clear_speed();
  static const int kSpeedFieldNumber = 4;
  double speed() const;
  void set_speed(double value);

  // optional double Curvature = 5;
  void clear_curvature();
  static const int kCurvatureFieldNumber = 5;
  double curvature() const;
  void set_curvature(double value);

  // optional double S = 6;
  void clear_s();
  static const int kSFieldNumber = 6;
  double s() const;
  void set_s(double value);

  // @@protoc_insertion_point(class_scope:Planning.TrajectoryPoint)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double x_;
  double y_;
  double theta_;
  double speed_;
  double curvature_;
  double s_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PlanningMsg_2eproto();
  friend void protobuf_AssignDesc_PlanningMsg_2eproto();
  friend void protobuf_ShutdownFile_PlanningMsg_2eproto();

  void InitAsDefaultInstance();
  static TrajectoryPoint* default_instance_;
};
// -------------------------------------------------------------------

class TrajectoryPointVec : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Planning.TrajectoryPointVec) */ {
 public:
  TrajectoryPointVec();
  virtual ~TrajectoryPointVec();

  TrajectoryPointVec(const TrajectoryPointVec& from);

  inline TrajectoryPointVec& operator=(const TrajectoryPointVec& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrajectoryPointVec& default_instance();

  void Swap(TrajectoryPointVec* other);

  // implements Message ----------------------------------------------

  inline TrajectoryPointVec* New() const { return New(NULL); }

  TrajectoryPointVec* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TrajectoryPointVec& from);
  void MergeFrom(const TrajectoryPointVec& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TrajectoryPointVec* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Planning.TrajectoryPoint TrajectoryPoints = 1;
  int trajectorypoints_size() const;
  void clear_trajectorypoints();
  static const int kTrajectoryPointsFieldNumber = 1;
  const ::Planning::TrajectoryPoint& trajectorypoints(int index) const;
  ::Planning::TrajectoryPoint* mutable_trajectorypoints(int index);
  ::Planning::TrajectoryPoint* add_trajectorypoints();
  ::google::protobuf::RepeatedPtrField< ::Planning::TrajectoryPoint >*
      mutable_trajectorypoints();
  const ::google::protobuf::RepeatedPtrField< ::Planning::TrajectoryPoint >&
      trajectorypoints() const;

  // @@protoc_insertion_point(class_scope:Planning.TrajectoryPointVec)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::Planning::TrajectoryPoint > trajectorypoints_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PlanningMsg_2eproto();
  friend void protobuf_AssignDesc_PlanningMsg_2eproto();
  friend void protobuf_ShutdownFile_PlanningMsg_2eproto();

  void InitAsDefaultInstance();
  static TrajectoryPointVec* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TrajectoryPoint

// optional double X = 1;
inline void TrajectoryPoint::clear_x() {
  x_ = 0;
}
inline double TrajectoryPoint::x() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.X)
  return x_;
}
inline void TrajectoryPoint::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.X)
}

// optional double Y = 2;
inline void TrajectoryPoint::clear_y() {
  y_ = 0;
}
inline double TrajectoryPoint::y() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.Y)
  return y_;
}
inline void TrajectoryPoint::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.Y)
}

// optional double Theta = 3;
inline void TrajectoryPoint::clear_theta() {
  theta_ = 0;
}
inline double TrajectoryPoint::theta() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.Theta)
  return theta_;
}
inline void TrajectoryPoint::set_theta(double value) {
  
  theta_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.Theta)
}

// optional double Speed = 4;
inline void TrajectoryPoint::clear_speed() {
  speed_ = 0;
}
inline double TrajectoryPoint::speed() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.Speed)
  return speed_;
}
inline void TrajectoryPoint::set_speed(double value) {
  
  speed_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.Speed)
}

// optional double Curvature = 5;
inline void TrajectoryPoint::clear_curvature() {
  curvature_ = 0;
}
inline double TrajectoryPoint::curvature() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.Curvature)
  return curvature_;
}
inline void TrajectoryPoint::set_curvature(double value) {
  
  curvature_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.Curvature)
}

// optional double S = 6;
inline void TrajectoryPoint::clear_s() {
  s_ = 0;
}
inline double TrajectoryPoint::s() const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPoint.S)
  return s_;
}
inline void TrajectoryPoint::set_s(double value) {
  
  s_ = value;
  // @@protoc_insertion_point(field_set:Planning.TrajectoryPoint.S)
}

// -------------------------------------------------------------------

// TrajectoryPointVec

// repeated .Planning.TrajectoryPoint TrajectoryPoints = 1;
inline int TrajectoryPointVec::trajectorypoints_size() const {
  return trajectorypoints_.size();
}
inline void TrajectoryPointVec::clear_trajectorypoints() {
  trajectorypoints_.Clear();
}
inline const ::Planning::TrajectoryPoint& TrajectoryPointVec::trajectorypoints(int index) const {
  // @@protoc_insertion_point(field_get:Planning.TrajectoryPointVec.TrajectoryPoints)
  return trajectorypoints_.Get(index);
}
inline ::Planning::TrajectoryPoint* TrajectoryPointVec::mutable_trajectorypoints(int index) {
  // @@protoc_insertion_point(field_mutable:Planning.TrajectoryPointVec.TrajectoryPoints)
  return trajectorypoints_.Mutable(index);
}
inline ::Planning::TrajectoryPoint* TrajectoryPointVec::add_trajectorypoints() {
  // @@protoc_insertion_point(field_add:Planning.TrajectoryPointVec.TrajectoryPoints)
  return trajectorypoints_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Planning::TrajectoryPoint >*
TrajectoryPointVec::mutable_trajectorypoints() {
  // @@protoc_insertion_point(field_mutable_list:Planning.TrajectoryPointVec.TrajectoryPoints)
  return &trajectorypoints_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Planning::TrajectoryPoint >&
TrajectoryPointVec::trajectorypoints() const {
  // @@protoc_insertion_point(field_list:Planning.TrajectoryPointVec.TrajectoryPoints)
  return trajectorypoints_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Planning

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PlanningMsg_2eproto__INCLUDED
