// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laneMsg.proto

#ifndef PROTOBUF_INCLUDED_laneMsg_2eproto
#define PROTOBUF_INCLUDED_laneMsg_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_laneMsg_2eproto 

namespace protobuf_laneMsg_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_laneMsg_2eproto
namespace lane {
class Lane;
class LaneDefaultTypeInternal;
extern LaneDefaultTypeInternal _Lane_default_instance_;
class LaneList;
class LaneListDefaultTypeInternal;
extern LaneListDefaultTypeInternal _LaneList_default_instance_;
class Point;
class PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
}  // namespace lane
namespace google {
namespace protobuf {
template<> ::lane::Lane* Arena::CreateMaybeMessage<::lane::Lane>(Arena*);
template<> ::lane::LaneList* Arena::CreateMaybeMessage<::lane::LaneList>(Arena*);
template<> ::lane::Point* Arena::CreateMaybeMessage<::lane::Point>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace lane {

// ===================================================================

class Point : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lane.Point) */ {
 public:
  Point();
  virtual ~Point();

  Point(const Point& from);

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(Point&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Point& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Point* other);
  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Point* New() const final {
    return CreateMaybeMessage<Point>(NULL);
  }

  Point* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Point& from);
  void MergeFrom(const Point& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // int32 y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:lane.Point)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_laneMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Lane : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lane.Lane) */ {
 public:
  Lane();
  virtual ~Lane();

  Lane(const Lane& from);

  inline Lane& operator=(const Lane& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Lane(Lane&& from) noexcept
    : Lane() {
    *this = ::std::move(from);
  }

  inline Lane& operator=(Lane&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Lane& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Lane* internal_default_instance() {
    return reinterpret_cast<const Lane*>(
               &_Lane_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Lane* other);
  friend void swap(Lane& a, Lane& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Lane* New() const final {
    return CreateMaybeMessage<Lane>(NULL);
  }

  Lane* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Lane>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Lane& from);
  void MergeFrom(const Lane& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Lane* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .lane.Point point = 1;
  int point_size() const;
  void clear_point();
  static const int kPointFieldNumber = 1;
  ::lane::Point* mutable_point(int index);
  ::google::protobuf::RepeatedPtrField< ::lane::Point >*
      mutable_point();
  const ::lane::Point& point(int index) const;
  ::lane::Point* add_point();
  const ::google::protobuf::RepeatedPtrField< ::lane::Point >&
      point() const;

  // @@protoc_insertion_point(class_scope:lane.Lane)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::lane::Point > point_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_laneMsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LaneList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lane.LaneList) */ {
 public:
  LaneList();
  virtual ~LaneList();

  LaneList(const LaneList& from);

  inline LaneList& operator=(const LaneList& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LaneList(LaneList&& from) noexcept
    : LaneList() {
    *this = ::std::move(from);
  }

  inline LaneList& operator=(LaneList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LaneList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LaneList* internal_default_instance() {
    return reinterpret_cast<const LaneList*>(
               &_LaneList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(LaneList* other);
  friend void swap(LaneList& a, LaneList& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LaneList* New() const final {
    return CreateMaybeMessage<LaneList>(NULL);
  }

  LaneList* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LaneList>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LaneList& from);
  void MergeFrom(const LaneList& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LaneList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .lane.Lane lane = 1;
  int lane_size() const;
  void clear_lane();
  static const int kLaneFieldNumber = 1;
  ::lane::Lane* mutable_lane(int index);
  ::google::protobuf::RepeatedPtrField< ::lane::Lane >*
      mutable_lane();
  const ::lane::Lane& lane(int index) const;
  ::lane::Lane* add_lane();
  const ::google::protobuf::RepeatedPtrField< ::lane::Lane >&
      lane() const;

  // @@protoc_insertion_point(class_scope:lane.LaneList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::lane::Lane > lane_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_laneMsg_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Point

// int32 x = 1;
inline void Point::clear_x() {
  x_ = 0;
}
inline ::google::protobuf::int32 Point::x() const {
  // @@protoc_insertion_point(field_get:lane.Point.x)
  return x_;
}
inline void Point::set_x(::google::protobuf::int32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:lane.Point.x)
}

// int32 y = 2;
inline void Point::clear_y() {
  y_ = 0;
}
inline ::google::protobuf::int32 Point::y() const {
  // @@protoc_insertion_point(field_get:lane.Point.y)
  return y_;
}
inline void Point::set_y(::google::protobuf::int32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:lane.Point.y)
}

// -------------------------------------------------------------------

// Lane

// repeated .lane.Point point = 1;
inline int Lane::point_size() const {
  return point_.size();
}
inline void Lane::clear_point() {
  point_.Clear();
}
inline ::lane::Point* Lane::mutable_point(int index) {
  // @@protoc_insertion_point(field_mutable:lane.Lane.point)
  return point_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::lane::Point >*
Lane::mutable_point() {
  // @@protoc_insertion_point(field_mutable_list:lane.Lane.point)
  return &point_;
}
inline const ::lane::Point& Lane::point(int index) const {
  // @@protoc_insertion_point(field_get:lane.Lane.point)
  return point_.Get(index);
}
inline ::lane::Point* Lane::add_point() {
  // @@protoc_insertion_point(field_add:lane.Lane.point)
  return point_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::lane::Point >&
Lane::point() const {
  // @@protoc_insertion_point(field_list:lane.Lane.point)
  return point_;
}

// -------------------------------------------------------------------

// LaneList

// repeated .lane.Lane lane = 1;
inline int LaneList::lane_size() const {
  return lane_.size();
}
inline void LaneList::clear_lane() {
  lane_.Clear();
}
inline ::lane::Lane* LaneList::mutable_lane(int index) {
  // @@protoc_insertion_point(field_mutable:lane.LaneList.lane)
  return lane_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::lane::Lane >*
LaneList::mutable_lane() {
  // @@protoc_insertion_point(field_mutable_list:lane.LaneList.lane)
  return &lane_;
}
inline const ::lane::Lane& LaneList::lane(int index) const {
  // @@protoc_insertion_point(field_get:lane.LaneList.lane)
  return lane_.Get(index);
}
inline ::lane::Lane* LaneList::add_lane() {
  // @@protoc_insertion_point(field_add:lane.LaneList.lane)
  return lane_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::lane::Lane >&
LaneList::lane() const {
  // @@protoc_insertion_point(field_list:lane.LaneList.lane)
  return lane_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace lane

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_laneMsg_2eproto
