// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ui.proto

#ifndef PROTOBUF_ui_2eproto__INCLUDED
#define PROTOBUF_ui_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ui {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ui_2eproto();
void protobuf_AssignDesc_ui_2eproto();
void protobuf_ShutdownFile_ui_2eproto();

class Cv;
class Gnss;
class Imu;
class Iov;
class Posture;
class UiPad2VData;
class UiV2PadData;

// ===================================================================

class UiPad2VData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ui.UiPad2VData) */ {
 public:
  UiPad2VData();
  virtual ~UiPad2VData();

  UiPad2VData(const UiPad2VData& from);

  inline UiPad2VData& operator=(const UiPad2VData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UiPad2VData& default_instance();

  void Swap(UiPad2VData* other);

  // implements Message ----------------------------------------------

  inline UiPad2VData* New() const { return New(NULL); }

  UiPad2VData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UiPad2VData& from);
  void MergeFrom(const UiPad2VData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UiPad2VData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool b_stopFlag = 1;
  void clear_b_stopflag();
  static const int kBStopFlagFieldNumber = 1;
  bool b_stopflag() const;
  void set_b_stopflag(bool value);

  // optional bool b_speedOff = 2;
  void clear_b_speedoff();
  static const int kBSpeedOffFieldNumber = 2;
  bool b_speedoff() const;
  void set_b_speedoff(bool value);

  // optional bool b_steeringOff = 3;
  void clear_b_steeringoff();
  static const int kBSteeringOffFieldNumber = 3;
  bool b_steeringoff() const;
  void set_b_steeringoff(bool value);

  // optional bool b_isValid = 4;
  void clear_b_isvalid();
  static const int kBIsValidFieldNumber = 4;
  bool b_isvalid() const;
  void set_b_isvalid(bool value);

  // optional bool b_config1 = 5;
  void clear_b_config1();
  static const int kBConfig1FieldNumber = 5;
  bool b_config1() const;
  void set_b_config1(bool value);

  // optional int32 s_targetPath = 6;
  void clear_s_targetpath();
  static const int kSTargetPathFieldNumber = 6;
  ::google::protobuf::int32 s_targetpath() const;
  void set_s_targetpath(::google::protobuf::int32 value);

  // optional bool b_isAlive = 7;
  void clear_b_isalive();
  static const int kBIsAliveFieldNumber = 7;
  bool b_isalive() const;
  void set_b_isalive(bool value);

  // @@protoc_insertion_point(class_scope:ui.UiPad2VData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  bool b_stopflag_;
  bool b_speedoff_;
  bool b_steeringoff_;
  bool b_isvalid_;
  ::google::protobuf::int32 s_targetpath_;
  bool b_config1_;
  bool b_isalive_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ui_2eproto();
  friend void protobuf_AssignDesc_ui_2eproto();
  friend void protobuf_ShutdownFile_ui_2eproto();

  void InitAsDefaultInstance();
  static UiPad2VData* default_instance_;
};
// -------------------------------------------------------------------

class Imu : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ui.Imu) */ {
 public:
  Imu();
  virtual ~Imu();

  Imu(const Imu& from);

  inline Imu& operator=(const Imu& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Imu& default_instance();

  void Swap(Imu* other);

  // implements Message ----------------------------------------------

  inline Imu* New() const { return New(NULL); }

  Imu* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Imu& from);
  void MergeFrom(const Imu& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Imu* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double time = 1;
  void clear_time();
  static const int kTimeFieldNumber = 1;
  double time() const;
  void set_time(double value);

  // optional double velocity = 2;
  void clear_velocity();
  static const int kVelocityFieldNumber = 2;
  double velocity() const;
  void set_velocity(double value);

  // optional double roll = 3;
  void clear_roll();
  static const int kRollFieldNumber = 3;
  double roll() const;
  void set_roll(double value);

  // optional double yaw = 4;
  void clear_yaw();
  static const int kYawFieldNumber = 4;
  double yaw() const;
  void set_yaw(double value);

  // optional double pitch = 5;
  void clear_pitch();
  static const int kPitchFieldNumber = 5;
  double pitch() const;
  void set_pitch(double value);

  // optional bool b_isValid = 6;
  void clear_b_isvalid();
  static const int kBIsValidFieldNumber = 6;
  bool b_isvalid() const;
  void set_b_isvalid(bool value);

  // optional bool b_gpsValid = 7;
  void clear_b_gpsvalid();
  static const int kBGpsValidFieldNumber = 7;
  bool b_gpsvalid() const;
  void set_b_gpsvalid(bool value);

  // optional double latitude = 8;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 8;
  double latitude() const;
  void set_latitude(double value);

  // optional double longitude = 9;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 9;
  double longitude() const;
  void set_longitude(double value);

  // optional double gaussX = 10;
  void clear_gaussx();
  static const int kGaussXFieldNumber = 10;
  double gaussx() const;
  void set_gaussx(double value);

  // optional double gaussY = 11;
  void clear_gaussy();
  static const int kGaussYFieldNumber = 11;
  double gaussy() const;
  void set_gaussy(double value);

  // optional double yawRate = 12;
  void clear_yawrate();
  static const int kYawRateFieldNumber = 12;
  double yawrate() const;
  void set_yawrate(double value);

  // optional bool b_isAlive = 13;
  void clear_b_isalive();
  static const int kBIsAliveFieldNumber = 13;
  bool b_isalive() const;
  void set_b_isalive(bool value);

  // @@protoc_insertion_point(class_scope:ui.Imu)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double time_;
  double velocity_;
  double roll_;
  double yaw_;
  double pitch_;
  double latitude_;
  double longitude_;
  double gaussx_;
  double gaussy_;
  double yawrate_;
  bool b_isvalid_;
  bool b_gpsvalid_;
  bool b_isalive_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ui_2eproto();
  friend void protobuf_AssignDesc_ui_2eproto();
  friend void protobuf_ShutdownFile_ui_2eproto();

  void InitAsDefaultInstance();
  static Imu* default_instance_;
};
// -------------------------------------------------------------------

class Gnss : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ui.Gnss) */ {
 public:
  Gnss();
  virtual ~Gnss();

  Gnss(const Gnss& from);

  inline Gnss& operator=(const Gnss& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Gnss& default_instance();

  void Swap(Gnss* other);

  // implements Message ----------------------------------------------

  inline Gnss* New() const { return New(NULL); }

  Gnss* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Gnss& from);
  void MergeFrom(const Gnss& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Gnss* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double longitude = 1;
  void clear_longitude();
  static const int kLongitudeFieldNumber = 1;
  double longitude() const;
  void set_longitude(double value);

  // optional double latitude = 2;
  void clear_latitude();
  static const int kLatitudeFieldNumber = 2;
  double latitude() const;
  void set_latitude(double value);

  // optional double gaussX = 3;
  void clear_gaussx();
  static const int kGaussXFieldNumber = 3;
  double gaussx() const;
  void set_gaussx(double value);

  // optional double gaussY = 4;
  void clear_gaussy();
  static const int kGaussYFieldNumber = 4;
  double gaussy() const;
  void set_gaussy(double value);

  // optional double yaw = 5;
  void clear_yaw();
  static const int kYawFieldNumber = 5;
  double yaw() const;
  void set_yaw(double value);

  // optional int32 gpsQuality = 6;
  void clear_gpsquality();
  static const int kGpsQualityFieldNumber = 6;
  ::google::protobuf::int32 gpsquality() const;
  void set_gpsquality(::google::protobuf::int32 value);

  // optional double utc_second = 7;
  void clear_utc_second();
  static const int kUtcSecondFieldNumber = 7;
  double utc_second() const;
  void set_utc_second(double value);

  // optional bool b_isValid = 8;
  void clear_b_isvalid();
  static const int kBIsValidFieldNumber = 8;
  bool b_isvalid() const;
  void set_b_isvalid(bool value);

  // optional bool b_isDiffitial = 9;
  void clear_b_isdiffitial();
  static const int kBIsDiffitialFieldNumber = 9;
  bool b_isdiffitial() const;
  void set_b_isdiffitial(bool value);

  // optional bool b_isAlive = 10;
  void clear_b_isalive();
  static const int kBIsAliveFieldNumber = 10;
  bool b_isalive() const;
  void set_b_isalive(bool value);

  // @@protoc_insertion_point(class_scope:ui.Gnss)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double longitude_;
  double latitude_;
  double gaussx_;
  double gaussy_;
  double yaw_;
  double utc_second_;
  ::google::protobuf::int32 gpsquality_;
  bool b_isvalid_;
  bool b_isdiffitial_;
  bool b_isalive_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ui_2eproto();
  friend void protobuf_AssignDesc_ui_2eproto();
  friend void protobuf_ShutdownFile_ui_2eproto();

  void InitAsDefaultInstance();
  static Gnss* default_instance_;
};
// -------------------------------------------------------------------

class Posture : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ui.Posture) */ {
 public:
  Posture();
  virtual ~Posture();

  Posture(const Posture& from);

  inline Posture& operator=(const Posture& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Posture& default_instance();

  void Swap(Posture* other);

  // implements Message ----------------------------------------------

  inline Posture* New() const { return New(NULL); }

  Posture* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Posture& from);
  void MergeFrom(const Posture& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Posture* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ui.Imu imu = 1;
  int imu_size() const;
  void clear_imu();
  static const int kImuFieldNumber = 1;
  const ::ui::Imu& imu(int index) const;
  ::ui::Imu* mutable_imu(int index);
  ::ui::Imu* add_imu();
  ::google::protobuf::RepeatedPtrField< ::ui::Imu >*
      mutable_imu();
  const ::google::protobuf::RepeatedPtrField< ::ui::Imu >&
      imu() const;

  // repeated .ui.Gnss gnss = 2;
  int gnss_size() const;
  void clear_gnss();
  static const int kGnssFieldNumber = 2;
  const ::ui::Gnss& gnss(int index) const;
  ::ui::Gnss* mutable_gnss(int index);
  ::ui::Gnss* add_gnss();
  ::google::protobuf::RepeatedPtrField< ::ui::Gnss >*
      mutable_gnss();
  const ::google::protobuf::RepeatedPtrField< ::ui::Gnss >&
      gnss() const;

  // optional bool b_isAlive = 3;
  void clear_b_isalive();
  static const int kBIsAliveFieldNumber = 3;
  bool b_isalive() const;
  void set_b_isalive(bool value);

  // @@protoc_insertion_point(class_scope:ui.Posture)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::ui::Imu > imu_;
  ::google::protobuf::RepeatedPtrField< ::ui::Gnss > gnss_;
  bool b_isalive_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ui_2eproto();
  friend void protobuf_AssignDesc_ui_2eproto();
  friend void protobuf_ShutdownFile_ui_2eproto();

  void InitAsDefaultInstance();
  static Posture* default_instance_;
};
// -------------------------------------------------------------------

class Iov : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ui.Iov) */ {
 public:
  Iov();
  virtual ~Iov();

  Iov(const Iov& from);

  inline Iov& operator=(const Iov& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Iov& default_instance();

  void Swap(Iov* other);

  // implements Message ----------------------------------------------

  inline Iov* New() const { return New(NULL); }

  Iov* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Iov& from);
  void MergeFrom(const Iov& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Iov* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool b_isValid = 1;
  void clear_b_isvalid();
  static const int kBIsValidFieldNumber = 1;
  bool b_isvalid() const;
  void set_b_isvalid(bool value);

  // optional bool b_isAlive = 2;
  void clear_b_isalive();
  static const int kBIsAliveFieldNumber = 2;
  bool b_isalive() const;
  void set_b_isalive(bool value);

  // optional bool b_vehicleValid = 3;
  void clear_b_vehiclevalid();
  static const int kBVehicleValidFieldNumber = 3;
  bool b_vehiclevalid() const;
  void set_b_vehiclevalid(bool value);

  // optional int32 vehicleId = 4;
  void clear_vehicleid();
  static const int kVehicleIdFieldNumber = 4;
  ::google::protobuf::int32 vehicleid() const;
  void set_vehicleid(::google::protobuf::int32 value);

  // optional int32 vehicleType = 5;
  void clear_vehicletype();
  static const int kVehicleTypeFieldNumber = 5;
  ::google::protobuf::int32 vehicletype() const;
  void set_vehicletype(::google::protobuf::int32 value);

  // optional double vehicleGaussX = 6;
  void clear_vehiclegaussx();
  static const int kVehicleGaussXFieldNumber = 6;
  double vehiclegaussx() const;
  void set_vehiclegaussx(double value);

  // optional double vehicleGaussY = 7;
  void clear_vehiclegaussy();
  static const int kVehicleGaussYFieldNumber = 7;
  double vehiclegaussy() const;
  void set_vehiclegaussy(double value);

  // optional double vehicleSpeed = 8;
  void clear_vehiclespeed();
  static const int kVehicleSpeedFieldNumber = 8;
  double vehiclespeed() const;
  void set_vehiclespeed(double value);

  // optional double vehicleTime = 9;
  void clear_vehicletime();
  static const int kVehicleTimeFieldNumber = 9;
  double vehicletime() const;
  void set_vehicletime(double value);

  // optional double vehicleAdvisedSpeed = 10;
  void clear_vehicleadvisedspeed();
  static const int kVehicleAdvisedSpeedFieldNumber = 10;
  double vehicleadvisedspeed() const;
  void set_vehicleadvisedspeed(double value);

  // optional bool b_lightValid = 11;
  void clear_b_lightvalid();
  static const int kBLightValidFieldNumber = 11;
  bool b_lightvalid() const;
  void set_b_lightvalid(bool value);

  // optional int32 lightPhase = 12;
  void clear_lightphase();
  static const int kLightPhaseFieldNumber = 12;
  ::google::protobuf::int32 lightphase() const;
  void set_lightphase(::google::protobuf::int32 value);

  // optional double lightTime = 13;
  void clear_lighttime();
  static const int kLightTimeFieldNumber = 13;
  double lighttime() const;
  void set_lighttime(double value);

  // optional double lightAdvisedSpeed = 14;
  void clear_lightadvisedspeed();
  static const int kLightAdvisedSpeedFieldNumber = 14;
  double lightadvisedspeed() const;
  void set_lightadvisedspeed(double value);

  // @@protoc_insertion_point(class_scope:ui.Iov)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 vehicleid_;
  bool b_isvalid_;
  bool b_isalive_;
  bool b_vehiclevalid_;
  bool b_lightvalid_;
  double vehiclegaussx_;
  double vehiclegaussy_;
  double vehiclespeed_;
  ::google::protobuf::int32 vehicletype_;
  ::google::protobuf::int32 lightphase_;
  double vehicletime_;
  double vehicleadvisedspeed_;
  double lighttime_;
  double lightadvisedspeed_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ui_2eproto();
  friend void protobuf_AssignDesc_ui_2eproto();
  friend void protobuf_ShutdownFile_ui_2eproto();

  void InitAsDefaultInstance();
  static Iov* default_instance_;
};
// -------------------------------------------------------------------

class Cv : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ui.Cv) */ {
 public:
  Cv();
  virtual ~Cv();

  Cv(const Cv& from);

  inline Cv& operator=(const Cv& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Cv& default_instance();

  void Swap(Cv* other);

  // implements Message ----------------------------------------------

  inline Cv* New() const { return New(NULL); }

  Cv* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Cv& from);
  void MergeFrom(const Cv& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Cv* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool b_isValid = 1;
  void clear_b_isvalid();
  static const int kBIsValidFieldNumber = 1;
  bool b_isvalid() const;
  void set_b_isvalid(bool value);

  // optional bool b_isAlive = 2;
  void clear_b_isalive();
  static const int kBIsAliveFieldNumber = 2;
  bool b_isalive() const;
  void set_b_isalive(bool value);

  // optional bool b_vehicleValid = 3;
  void clear_b_vehiclevalid();
  static const int kBVehicleValidFieldNumber = 3;
  bool b_vehiclevalid() const;
  void set_b_vehiclevalid(bool value);

  // optional int32 vehicleId = 4;
  void clear_vehicleid();
  static const int kVehicleIdFieldNumber = 4;
  ::google::protobuf::int32 vehicleid() const;
  void set_vehicleid(::google::protobuf::int32 value);

  // optional int32 vehicleType = 5;
  void clear_vehicletype();
  static const int kVehicleTypeFieldNumber = 5;
  ::google::protobuf::int32 vehicletype() const;
  void set_vehicletype(::google::protobuf::int32 value);

  // optional double vehicleGaussX = 6;
  void clear_vehiclegaussx();
  static const int kVehicleGaussXFieldNumber = 6;
  double vehiclegaussx() const;
  void set_vehiclegaussx(double value);

  // optional double vehicleGaussY = 7;
  void clear_vehiclegaussy();
  static const int kVehicleGaussYFieldNumber = 7;
  double vehiclegaussy() const;
  void set_vehiclegaussy(double value);

  // optional double vehicleSpeed = 8;
  void clear_vehiclespeed();
  static const int kVehicleSpeedFieldNumber = 8;
  double vehiclespeed() const;
  void set_vehiclespeed(double value);

  // optional double vehicleTime = 9;
  void clear_vehicletime();
  static const int kVehicleTimeFieldNumber = 9;
  double vehicletime() const;
  void set_vehicletime(double value);

  // optional double vehicleAdvisedSpeed = 10;
  void clear_vehicleadvisedspeed();
  static const int kVehicleAdvisedSpeedFieldNumber = 10;
  double vehicleadvisedspeed() const;
  void set_vehicleadvisedspeed(double value);

  // optional bool b_lightValid = 11;
  void clear_b_lightvalid();
  static const int kBLightValidFieldNumber = 11;
  bool b_lightvalid() const;
  void set_b_lightvalid(bool value);

  // optional int32 lightPhase = 12;
  void clear_lightphase();
  static const int kLightPhaseFieldNumber = 12;
  ::google::protobuf::int32 lightphase() const;
  void set_lightphase(::google::protobuf::int32 value);

  // optional double lightTime = 13;
  void clear_lighttime();
  static const int kLightTimeFieldNumber = 13;
  double lighttime() const;
  void set_lighttime(double value);

  // optional double lightAdvisedSpeed = 14;
  void clear_lightadvisedspeed();
  static const int kLightAdvisedSpeedFieldNumber = 14;
  double lightadvisedspeed() const;
  void set_lightadvisedspeed(double value);

  // @@protoc_insertion_point(class_scope:ui.Cv)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 vehicleid_;
  bool b_isvalid_;
  bool b_isalive_;
  bool b_vehiclevalid_;
  bool b_lightvalid_;
  double vehiclegaussx_;
  double vehiclegaussy_;
  double vehiclespeed_;
  ::google::protobuf::int32 vehicletype_;
  ::google::protobuf::int32 lightphase_;
  double vehicletime_;
  double vehicleadvisedspeed_;
  double lighttime_;
  double lightadvisedspeed_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ui_2eproto();
  friend void protobuf_AssignDesc_ui_2eproto();
  friend void protobuf_ShutdownFile_ui_2eproto();

  void InitAsDefaultInstance();
  static Cv* default_instance_;
};
// -------------------------------------------------------------------

class UiV2PadData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ui.UiV2PadData) */ {
 public:
  UiV2PadData();
  virtual ~UiV2PadData();

  UiV2PadData(const UiV2PadData& from);

  inline UiV2PadData& operator=(const UiV2PadData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UiV2PadData& default_instance();

  void Swap(UiV2PadData* other);

  // implements Message ----------------------------------------------

  inline UiV2PadData* New() const { return New(NULL); }

  UiV2PadData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UiV2PadData& from);
  void MergeFrom(const UiV2PadData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UiV2PadData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ui.Posture posture = 1;
  int posture_size() const;
  void clear_posture();
  static const int kPostureFieldNumber = 1;
  const ::ui::Posture& posture(int index) const;
  ::ui::Posture* mutable_posture(int index);
  ::ui::Posture* add_posture();
  ::google::protobuf::RepeatedPtrField< ::ui::Posture >*
      mutable_posture();
  const ::google::protobuf::RepeatedPtrField< ::ui::Posture >&
      posture() const;

  // repeated .ui.Iov iov = 2;
  int iov_size() const;
  void clear_iov();
  static const int kIovFieldNumber = 2;
  const ::ui::Iov& iov(int index) const;
  ::ui::Iov* mutable_iov(int index);
  ::ui::Iov* add_iov();
  ::google::protobuf::RepeatedPtrField< ::ui::Iov >*
      mutable_iov();
  const ::google::protobuf::RepeatedPtrField< ::ui::Iov >&
      iov() const;

  // repeated .ui.Cv cv = 3;
  int cv_size() const;
  void clear_cv();
  static const int kCvFieldNumber = 3;
  const ::ui::Cv& cv(int index) const;
  ::ui::Cv* mutable_cv(int index);
  ::ui::Cv* add_cv();
  ::google::protobuf::RepeatedPtrField< ::ui::Cv >*
      mutable_cv();
  const ::google::protobuf::RepeatedPtrField< ::ui::Cv >&
      cv() const;

  // @@protoc_insertion_point(class_scope:ui.UiV2PadData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::ui::Posture > posture_;
  ::google::protobuf::RepeatedPtrField< ::ui::Iov > iov_;
  ::google::protobuf::RepeatedPtrField< ::ui::Cv > cv_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ui_2eproto();
  friend void protobuf_AssignDesc_ui_2eproto();
  friend void protobuf_ShutdownFile_ui_2eproto();

  void InitAsDefaultInstance();
  static UiV2PadData* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// UiPad2VData

// optional bool b_stopFlag = 1;
inline void UiPad2VData::clear_b_stopflag() {
  b_stopflag_ = false;
}
inline bool UiPad2VData::b_stopflag() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.b_stopFlag)
  return b_stopflag_;
}
inline void UiPad2VData::set_b_stopflag(bool value) {
  
  b_stopflag_ = value;
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.b_stopFlag)
}

// optional bool b_speedOff = 2;
inline void UiPad2VData::clear_b_speedoff() {
  b_speedoff_ = false;
}
inline bool UiPad2VData::b_speedoff() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.b_speedOff)
  return b_speedoff_;
}
inline void UiPad2VData::set_b_speedoff(bool value) {
  
  b_speedoff_ = value;
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.b_speedOff)
}

// optional bool b_steeringOff = 3;
inline void UiPad2VData::clear_b_steeringoff() {
  b_steeringoff_ = false;
}
inline bool UiPad2VData::b_steeringoff() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.b_steeringOff)
  return b_steeringoff_;
}
inline void UiPad2VData::set_b_steeringoff(bool value) {
  
  b_steeringoff_ = value;
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.b_steeringOff)
}

// optional bool b_isValid = 4;
inline void UiPad2VData::clear_b_isvalid() {
  b_isvalid_ = false;
}
inline bool UiPad2VData::b_isvalid() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.b_isValid)
  return b_isvalid_;
}
inline void UiPad2VData::set_b_isvalid(bool value) {
  
  b_isvalid_ = value;
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.b_isValid)
}

// optional bool b_config1 = 5;
inline void UiPad2VData::clear_b_config1() {
  b_config1_ = false;
}
inline bool UiPad2VData::b_config1() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.b_config1)
  return b_config1_;
}
inline void UiPad2VData::set_b_config1(bool value) {
  
  b_config1_ = value;
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.b_config1)
}

// optional int32 s_targetPath = 6;
inline void UiPad2VData::clear_s_targetpath() {
  s_targetpath_ = 0;
}
inline ::google::protobuf::int32 UiPad2VData::s_targetpath() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.s_targetPath)
  return s_targetpath_;
}
inline void UiPad2VData::set_s_targetpath(::google::protobuf::int32 value) {
  
  s_targetpath_ = value;
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.s_targetPath)
}

// optional bool b_isAlive = 7;
inline void UiPad2VData::clear_b_isalive() {
  b_isalive_ = false;
}
inline bool UiPad2VData::b_isalive() const {
  // @@protoc_insertion_point(field_get:ui.UiPad2VData.b_isAlive)
  return b_isalive_;
}
inline void UiPad2VData::set_b_isalive(bool value) {
  
  b_isalive_ = value;
  // @@protoc_insertion_point(field_set:ui.UiPad2VData.b_isAlive)
}

// -------------------------------------------------------------------

// Imu

// optional double time = 1;
inline void Imu::clear_time() {
  time_ = 0;
}
inline double Imu::time() const {
  // @@protoc_insertion_point(field_get:ui.Imu.time)
  return time_;
}
inline void Imu::set_time(double value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:ui.Imu.time)
}

// optional double velocity = 2;
inline void Imu::clear_velocity() {
  velocity_ = 0;
}
inline double Imu::velocity() const {
  // @@protoc_insertion_point(field_get:ui.Imu.velocity)
  return velocity_;
}
inline void Imu::set_velocity(double value) {
  
  velocity_ = value;
  // @@protoc_insertion_point(field_set:ui.Imu.velocity)
}

// optional double roll = 3;
inline void Imu::clear_roll() {
  roll_ = 0;
}
inline double Imu::roll() const {
  // @@protoc_insertion_point(field_get:ui.Imu.roll)
  return roll_;
}
inline void Imu::set_roll(double value) {
  
  roll_ = value;
  // @@protoc_insertion_point(field_set:ui.Imu.roll)
}

// optional double yaw = 4;
inline void Imu::clear_yaw() {
  yaw_ = 0;
}
inline double Imu::yaw() const {
  // @@protoc_insertion_point(field_get:ui.Imu.yaw)
  return yaw_;
}
inline void Imu::set_yaw(double value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:ui.Imu.yaw)
}

// optional double pitch = 5;
inline void Imu::clear_pitch() {
  pitch_ = 0;
}
inline double Imu::pitch() const {
  // @@protoc_insertion_point(field_get:ui.Imu.pitch)
  return pitch_;
}
inline void Imu::set_pitch(double value) {
  
  pitch_ = value;
  // @@protoc_insertion_point(field_set:ui.Imu.pitch)
}

// optional bool b_isValid = 6;
inline void Imu::clear_b_isvalid() {
  b_isvalid_ = false;
}
inline bool Imu::b_isvalid() const {
  // @@protoc_insertion_point(field_get:ui.Imu.b_isValid)
  return b_isvalid_;
}
inline void Imu::set_b_isvalid(bool value) {
  
  b_isvalid_ = value;
  // @@protoc_insertion_point(field_set:ui.Imu.b_isValid)
}

// optional bool b_gpsValid = 7;
inline void Imu::clear_b_gpsvalid() {
  b_gpsvalid_ = false;
}
inline bool Imu::b_gpsvalid() const {
  // @@protoc_insertion_point(field_get:ui.Imu.b_gpsValid)
  return b_gpsvalid_;
}
inline void Imu::set_b_gpsvalid(bool value) {
  
  b_gpsvalid_ = value;
  // @@protoc_insertion_point(field_set:ui.Imu.b_gpsValid)
}

// optional double latitude = 8;
inline void Imu::clear_latitude() {
  latitude_ = 0;
}
inline double Imu::latitude() const {
  // @@protoc_insertion_point(field_get:ui.Imu.latitude)
  return latitude_;
}
inline void Imu::set_latitude(double value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:ui.Imu.latitude)
}

// optional double longitude = 9;
inline void Imu::clear_longitude() {
  longitude_ = 0;
}
inline double Imu::longitude() const {
  // @@protoc_insertion_point(field_get:ui.Imu.longitude)
  return longitude_;
}
inline void Imu::set_longitude(double value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:ui.Imu.longitude)
}

// optional double gaussX = 10;
inline void Imu::clear_gaussx() {
  gaussx_ = 0;
}
inline double Imu::gaussx() const {
  // @@protoc_insertion_point(field_get:ui.Imu.gaussX)
  return gaussx_;
}
inline void Imu::set_gaussx(double value) {
  
  gaussx_ = value;
  // @@protoc_insertion_point(field_set:ui.Imu.gaussX)
}

// optional double gaussY = 11;
inline void Imu::clear_gaussy() {
  gaussy_ = 0;
}
inline double Imu::gaussy() const {
  // @@protoc_insertion_point(field_get:ui.Imu.gaussY)
  return gaussy_;
}
inline void Imu::set_gaussy(double value) {
  
  gaussy_ = value;
  // @@protoc_insertion_point(field_set:ui.Imu.gaussY)
}

// optional double yawRate = 12;
inline void Imu::clear_yawrate() {
  yawrate_ = 0;
}
inline double Imu::yawrate() const {
  // @@protoc_insertion_point(field_get:ui.Imu.yawRate)
  return yawrate_;
}
inline void Imu::set_yawrate(double value) {
  
  yawrate_ = value;
  // @@protoc_insertion_point(field_set:ui.Imu.yawRate)
}

// optional bool b_isAlive = 13;
inline void Imu::clear_b_isalive() {
  b_isalive_ = false;
}
inline bool Imu::b_isalive() const {
  // @@protoc_insertion_point(field_get:ui.Imu.b_isAlive)
  return b_isalive_;
}
inline void Imu::set_b_isalive(bool value) {
  
  b_isalive_ = value;
  // @@protoc_insertion_point(field_set:ui.Imu.b_isAlive)
}

// -------------------------------------------------------------------

// Gnss

// optional double longitude = 1;
inline void Gnss::clear_longitude() {
  longitude_ = 0;
}
inline double Gnss::longitude() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.longitude)
  return longitude_;
}
inline void Gnss::set_longitude(double value) {
  
  longitude_ = value;
  // @@protoc_insertion_point(field_set:ui.Gnss.longitude)
}

// optional double latitude = 2;
inline void Gnss::clear_latitude() {
  latitude_ = 0;
}
inline double Gnss::latitude() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.latitude)
  return latitude_;
}
inline void Gnss::set_latitude(double value) {
  
  latitude_ = value;
  // @@protoc_insertion_point(field_set:ui.Gnss.latitude)
}

// optional double gaussX = 3;
inline void Gnss::clear_gaussx() {
  gaussx_ = 0;
}
inline double Gnss::gaussx() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.gaussX)
  return gaussx_;
}
inline void Gnss::set_gaussx(double value) {
  
  gaussx_ = value;
  // @@protoc_insertion_point(field_set:ui.Gnss.gaussX)
}

// optional double gaussY = 4;
inline void Gnss::clear_gaussy() {
  gaussy_ = 0;
}
inline double Gnss::gaussy() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.gaussY)
  return gaussy_;
}
inline void Gnss::set_gaussy(double value) {
  
  gaussy_ = value;
  // @@protoc_insertion_point(field_set:ui.Gnss.gaussY)
}

// optional double yaw = 5;
inline void Gnss::clear_yaw() {
  yaw_ = 0;
}
inline double Gnss::yaw() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.yaw)
  return yaw_;
}
inline void Gnss::set_yaw(double value) {
  
  yaw_ = value;
  // @@protoc_insertion_point(field_set:ui.Gnss.yaw)
}

// optional int32 gpsQuality = 6;
inline void Gnss::clear_gpsquality() {
  gpsquality_ = 0;
}
inline ::google::protobuf::int32 Gnss::gpsquality() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.gpsQuality)
  return gpsquality_;
}
inline void Gnss::set_gpsquality(::google::protobuf::int32 value) {
  
  gpsquality_ = value;
  // @@protoc_insertion_point(field_set:ui.Gnss.gpsQuality)
}

// optional double utc_second = 7;
inline void Gnss::clear_utc_second() {
  utc_second_ = 0;
}
inline double Gnss::utc_second() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.utc_second)
  return utc_second_;
}
inline void Gnss::set_utc_second(double value) {
  
  utc_second_ = value;
  // @@protoc_insertion_point(field_set:ui.Gnss.utc_second)
}

// optional bool b_isValid = 8;
inline void Gnss::clear_b_isvalid() {
  b_isvalid_ = false;
}
inline bool Gnss::b_isvalid() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.b_isValid)
  return b_isvalid_;
}
inline void Gnss::set_b_isvalid(bool value) {
  
  b_isvalid_ = value;
  // @@protoc_insertion_point(field_set:ui.Gnss.b_isValid)
}

// optional bool b_isDiffitial = 9;
inline void Gnss::clear_b_isdiffitial() {
  b_isdiffitial_ = false;
}
inline bool Gnss::b_isdiffitial() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.b_isDiffitial)
  return b_isdiffitial_;
}
inline void Gnss::set_b_isdiffitial(bool value) {
  
  b_isdiffitial_ = value;
  // @@protoc_insertion_point(field_set:ui.Gnss.b_isDiffitial)
}

// optional bool b_isAlive = 10;
inline void Gnss::clear_b_isalive() {
  b_isalive_ = false;
}
inline bool Gnss::b_isalive() const {
  // @@protoc_insertion_point(field_get:ui.Gnss.b_isAlive)
  return b_isalive_;
}
inline void Gnss::set_b_isalive(bool value) {
  
  b_isalive_ = value;
  // @@protoc_insertion_point(field_set:ui.Gnss.b_isAlive)
}

// -------------------------------------------------------------------

// Posture

// repeated .ui.Imu imu = 1;
inline int Posture::imu_size() const {
  return imu_.size();
}
inline void Posture::clear_imu() {
  imu_.Clear();
}
inline const ::ui::Imu& Posture::imu(int index) const {
  // @@protoc_insertion_point(field_get:ui.Posture.imu)
  return imu_.Get(index);
}
inline ::ui::Imu* Posture::mutable_imu(int index) {
  // @@protoc_insertion_point(field_mutable:ui.Posture.imu)
  return imu_.Mutable(index);
}
inline ::ui::Imu* Posture::add_imu() {
  // @@protoc_insertion_point(field_add:ui.Posture.imu)
  return imu_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ui::Imu >*
Posture::mutable_imu() {
  // @@protoc_insertion_point(field_mutable_list:ui.Posture.imu)
  return &imu_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ui::Imu >&
Posture::imu() const {
  // @@protoc_insertion_point(field_list:ui.Posture.imu)
  return imu_;
}

// repeated .ui.Gnss gnss = 2;
inline int Posture::gnss_size() const {
  return gnss_.size();
}
inline void Posture::clear_gnss() {
  gnss_.Clear();
}
inline const ::ui::Gnss& Posture::gnss(int index) const {
  // @@protoc_insertion_point(field_get:ui.Posture.gnss)
  return gnss_.Get(index);
}
inline ::ui::Gnss* Posture::mutable_gnss(int index) {
  // @@protoc_insertion_point(field_mutable:ui.Posture.gnss)
  return gnss_.Mutable(index);
}
inline ::ui::Gnss* Posture::add_gnss() {
  // @@protoc_insertion_point(field_add:ui.Posture.gnss)
  return gnss_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ui::Gnss >*
Posture::mutable_gnss() {
  // @@protoc_insertion_point(field_mutable_list:ui.Posture.gnss)
  return &gnss_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ui::Gnss >&
Posture::gnss() const {
  // @@protoc_insertion_point(field_list:ui.Posture.gnss)
  return gnss_;
}

// optional bool b_isAlive = 3;
inline void Posture::clear_b_isalive() {
  b_isalive_ = false;
}
inline bool Posture::b_isalive() const {
  // @@protoc_insertion_point(field_get:ui.Posture.b_isAlive)
  return b_isalive_;
}
inline void Posture::set_b_isalive(bool value) {
  
  b_isalive_ = value;
  // @@protoc_insertion_point(field_set:ui.Posture.b_isAlive)
}

// -------------------------------------------------------------------

// Iov

// optional bool b_isValid = 1;
inline void Iov::clear_b_isvalid() {
  b_isvalid_ = false;
}
inline bool Iov::b_isvalid() const {
  // @@protoc_insertion_point(field_get:ui.Iov.b_isValid)
  return b_isvalid_;
}
inline void Iov::set_b_isvalid(bool value) {
  
  b_isvalid_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.b_isValid)
}

// optional bool b_isAlive = 2;
inline void Iov::clear_b_isalive() {
  b_isalive_ = false;
}
inline bool Iov::b_isalive() const {
  // @@protoc_insertion_point(field_get:ui.Iov.b_isAlive)
  return b_isalive_;
}
inline void Iov::set_b_isalive(bool value) {
  
  b_isalive_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.b_isAlive)
}

// optional bool b_vehicleValid = 3;
inline void Iov::clear_b_vehiclevalid() {
  b_vehiclevalid_ = false;
}
inline bool Iov::b_vehiclevalid() const {
  // @@protoc_insertion_point(field_get:ui.Iov.b_vehicleValid)
  return b_vehiclevalid_;
}
inline void Iov::set_b_vehiclevalid(bool value) {
  
  b_vehiclevalid_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.b_vehicleValid)
}

// optional int32 vehicleId = 4;
inline void Iov::clear_vehicleid() {
  vehicleid_ = 0;
}
inline ::google::protobuf::int32 Iov::vehicleid() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleId)
  return vehicleid_;
}
inline void Iov::set_vehicleid(::google::protobuf::int32 value) {
  
  vehicleid_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleId)
}

// optional int32 vehicleType = 5;
inline void Iov::clear_vehicletype() {
  vehicletype_ = 0;
}
inline ::google::protobuf::int32 Iov::vehicletype() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleType)
  return vehicletype_;
}
inline void Iov::set_vehicletype(::google::protobuf::int32 value) {
  
  vehicletype_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleType)
}

// optional double vehicleGaussX = 6;
inline void Iov::clear_vehiclegaussx() {
  vehiclegaussx_ = 0;
}
inline double Iov::vehiclegaussx() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleGaussX)
  return vehiclegaussx_;
}
inline void Iov::set_vehiclegaussx(double value) {
  
  vehiclegaussx_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleGaussX)
}

// optional double vehicleGaussY = 7;
inline void Iov::clear_vehiclegaussy() {
  vehiclegaussy_ = 0;
}
inline double Iov::vehiclegaussy() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleGaussY)
  return vehiclegaussy_;
}
inline void Iov::set_vehiclegaussy(double value) {
  
  vehiclegaussy_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleGaussY)
}

// optional double vehicleSpeed = 8;
inline void Iov::clear_vehiclespeed() {
  vehiclespeed_ = 0;
}
inline double Iov::vehiclespeed() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleSpeed)
  return vehiclespeed_;
}
inline void Iov::set_vehiclespeed(double value) {
  
  vehiclespeed_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleSpeed)
}

// optional double vehicleTime = 9;
inline void Iov::clear_vehicletime() {
  vehicletime_ = 0;
}
inline double Iov::vehicletime() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleTime)
  return vehicletime_;
}
inline void Iov::set_vehicletime(double value) {
  
  vehicletime_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleTime)
}

// optional double vehicleAdvisedSpeed = 10;
inline void Iov::clear_vehicleadvisedspeed() {
  vehicleadvisedspeed_ = 0;
}
inline double Iov::vehicleadvisedspeed() const {
  // @@protoc_insertion_point(field_get:ui.Iov.vehicleAdvisedSpeed)
  return vehicleadvisedspeed_;
}
inline void Iov::set_vehicleadvisedspeed(double value) {
  
  vehicleadvisedspeed_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.vehicleAdvisedSpeed)
}

// optional bool b_lightValid = 11;
inline void Iov::clear_b_lightvalid() {
  b_lightvalid_ = false;
}
inline bool Iov::b_lightvalid() const {
  // @@protoc_insertion_point(field_get:ui.Iov.b_lightValid)
  return b_lightvalid_;
}
inline void Iov::set_b_lightvalid(bool value) {
  
  b_lightvalid_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.b_lightValid)
}

// optional int32 lightPhase = 12;
inline void Iov::clear_lightphase() {
  lightphase_ = 0;
}
inline ::google::protobuf::int32 Iov::lightphase() const {
  // @@protoc_insertion_point(field_get:ui.Iov.lightPhase)
  return lightphase_;
}
inline void Iov::set_lightphase(::google::protobuf::int32 value) {
  
  lightphase_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.lightPhase)
}

// optional double lightTime = 13;
inline void Iov::clear_lighttime() {
  lighttime_ = 0;
}
inline double Iov::lighttime() const {
  // @@protoc_insertion_point(field_get:ui.Iov.lightTime)
  return lighttime_;
}
inline void Iov::set_lighttime(double value) {
  
  lighttime_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.lightTime)
}

// optional double lightAdvisedSpeed = 14;
inline void Iov::clear_lightadvisedspeed() {
  lightadvisedspeed_ = 0;
}
inline double Iov::lightadvisedspeed() const {
  // @@protoc_insertion_point(field_get:ui.Iov.lightAdvisedSpeed)
  return lightadvisedspeed_;
}
inline void Iov::set_lightadvisedspeed(double value) {
  
  lightadvisedspeed_ = value;
  // @@protoc_insertion_point(field_set:ui.Iov.lightAdvisedSpeed)
}

// -------------------------------------------------------------------

// Cv

// optional bool b_isValid = 1;
inline void Cv::clear_b_isvalid() {
  b_isvalid_ = false;
}
inline bool Cv::b_isvalid() const {
  // @@protoc_insertion_point(field_get:ui.Cv.b_isValid)
  return b_isvalid_;
}
inline void Cv::set_b_isvalid(bool value) {
  
  b_isvalid_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.b_isValid)
}

// optional bool b_isAlive = 2;
inline void Cv::clear_b_isalive() {
  b_isalive_ = false;
}
inline bool Cv::b_isalive() const {
  // @@protoc_insertion_point(field_get:ui.Cv.b_isAlive)
  return b_isalive_;
}
inline void Cv::set_b_isalive(bool value) {
  
  b_isalive_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.b_isAlive)
}

// optional bool b_vehicleValid = 3;
inline void Cv::clear_b_vehiclevalid() {
  b_vehiclevalid_ = false;
}
inline bool Cv::b_vehiclevalid() const {
  // @@protoc_insertion_point(field_get:ui.Cv.b_vehicleValid)
  return b_vehiclevalid_;
}
inline void Cv::set_b_vehiclevalid(bool value) {
  
  b_vehiclevalid_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.b_vehicleValid)
}

// optional int32 vehicleId = 4;
inline void Cv::clear_vehicleid() {
  vehicleid_ = 0;
}
inline ::google::protobuf::int32 Cv::vehicleid() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleId)
  return vehicleid_;
}
inline void Cv::set_vehicleid(::google::protobuf::int32 value) {
  
  vehicleid_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleId)
}

// optional int32 vehicleType = 5;
inline void Cv::clear_vehicletype() {
  vehicletype_ = 0;
}
inline ::google::protobuf::int32 Cv::vehicletype() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleType)
  return vehicletype_;
}
inline void Cv::set_vehicletype(::google::protobuf::int32 value) {
  
  vehicletype_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleType)
}

// optional double vehicleGaussX = 6;
inline void Cv::clear_vehiclegaussx() {
  vehiclegaussx_ = 0;
}
inline double Cv::vehiclegaussx() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleGaussX)
  return vehiclegaussx_;
}
inline void Cv::set_vehiclegaussx(double value) {
  
  vehiclegaussx_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleGaussX)
}

// optional double vehicleGaussY = 7;
inline void Cv::clear_vehiclegaussy() {
  vehiclegaussy_ = 0;
}
inline double Cv::vehiclegaussy() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleGaussY)
  return vehiclegaussy_;
}
inline void Cv::set_vehiclegaussy(double value) {
  
  vehiclegaussy_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleGaussY)
}

// optional double vehicleSpeed = 8;
inline void Cv::clear_vehiclespeed() {
  vehiclespeed_ = 0;
}
inline double Cv::vehiclespeed() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleSpeed)
  return vehiclespeed_;
}
inline void Cv::set_vehiclespeed(double value) {
  
  vehiclespeed_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleSpeed)
}

// optional double vehicleTime = 9;
inline void Cv::clear_vehicletime() {
  vehicletime_ = 0;
}
inline double Cv::vehicletime() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleTime)
  return vehicletime_;
}
inline void Cv::set_vehicletime(double value) {
  
  vehicletime_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleTime)
}

// optional double vehicleAdvisedSpeed = 10;
inline void Cv::clear_vehicleadvisedspeed() {
  vehicleadvisedspeed_ = 0;
}
inline double Cv::vehicleadvisedspeed() const {
  // @@protoc_insertion_point(field_get:ui.Cv.vehicleAdvisedSpeed)
  return vehicleadvisedspeed_;
}
inline void Cv::set_vehicleadvisedspeed(double value) {
  
  vehicleadvisedspeed_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.vehicleAdvisedSpeed)
}

// optional bool b_lightValid = 11;
inline void Cv::clear_b_lightvalid() {
  b_lightvalid_ = false;
}
inline bool Cv::b_lightvalid() const {
  // @@protoc_insertion_point(field_get:ui.Cv.b_lightValid)
  return b_lightvalid_;
}
inline void Cv::set_b_lightvalid(bool value) {
  
  b_lightvalid_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.b_lightValid)
}

// optional int32 lightPhase = 12;
inline void Cv::clear_lightphase() {
  lightphase_ = 0;
}
inline ::google::protobuf::int32 Cv::lightphase() const {
  // @@protoc_insertion_point(field_get:ui.Cv.lightPhase)
  return lightphase_;
}
inline void Cv::set_lightphase(::google::protobuf::int32 value) {
  
  lightphase_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.lightPhase)
}

// optional double lightTime = 13;
inline void Cv::clear_lighttime() {
  lighttime_ = 0;
}
inline double Cv::lighttime() const {
  // @@protoc_insertion_point(field_get:ui.Cv.lightTime)
  return lighttime_;
}
inline void Cv::set_lighttime(double value) {
  
  lighttime_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.lightTime)
}

// optional double lightAdvisedSpeed = 14;
inline void Cv::clear_lightadvisedspeed() {
  lightadvisedspeed_ = 0;
}
inline double Cv::lightadvisedspeed() const {
  // @@protoc_insertion_point(field_get:ui.Cv.lightAdvisedSpeed)
  return lightadvisedspeed_;
}
inline void Cv::set_lightadvisedspeed(double value) {
  
  lightadvisedspeed_ = value;
  // @@protoc_insertion_point(field_set:ui.Cv.lightAdvisedSpeed)
}

// -------------------------------------------------------------------

// UiV2PadData

// repeated .ui.Posture posture = 1;
inline int UiV2PadData::posture_size() const {
  return posture_.size();
}
inline void UiV2PadData::clear_posture() {
  posture_.Clear();
}
inline const ::ui::Posture& UiV2PadData::posture(int index) const {
  // @@protoc_insertion_point(field_get:ui.UiV2PadData.posture)
  return posture_.Get(index);
}
inline ::ui::Posture* UiV2PadData::mutable_posture(int index) {
  // @@protoc_insertion_point(field_mutable:ui.UiV2PadData.posture)
  return posture_.Mutable(index);
}
inline ::ui::Posture* UiV2PadData::add_posture() {
  // @@protoc_insertion_point(field_add:ui.UiV2PadData.posture)
  return posture_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ui::Posture >*
UiV2PadData::mutable_posture() {
  // @@protoc_insertion_point(field_mutable_list:ui.UiV2PadData.posture)
  return &posture_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ui::Posture >&
UiV2PadData::posture() const {
  // @@protoc_insertion_point(field_list:ui.UiV2PadData.posture)
  return posture_;
}

// repeated .ui.Iov iov = 2;
inline int UiV2PadData::iov_size() const {
  return iov_.size();
}
inline void UiV2PadData::clear_iov() {
  iov_.Clear();
}
inline const ::ui::Iov& UiV2PadData::iov(int index) const {
  // @@protoc_insertion_point(field_get:ui.UiV2PadData.iov)
  return iov_.Get(index);
}
inline ::ui::Iov* UiV2PadData::mutable_iov(int index) {
  // @@protoc_insertion_point(field_mutable:ui.UiV2PadData.iov)
  return iov_.Mutable(index);
}
inline ::ui::Iov* UiV2PadData::add_iov() {
  // @@protoc_insertion_point(field_add:ui.UiV2PadData.iov)
  return iov_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ui::Iov >*
UiV2PadData::mutable_iov() {
  // @@protoc_insertion_point(field_mutable_list:ui.UiV2PadData.iov)
  return &iov_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ui::Iov >&
UiV2PadData::iov() const {
  // @@protoc_insertion_point(field_list:ui.UiV2PadData.iov)
  return iov_;
}

// repeated .ui.Cv cv = 3;
inline int UiV2PadData::cv_size() const {
  return cv_.size();
}
inline void UiV2PadData::clear_cv() {
  cv_.Clear();
}
inline const ::ui::Cv& UiV2PadData::cv(int index) const {
  // @@protoc_insertion_point(field_get:ui.UiV2PadData.cv)
  return cv_.Get(index);
}
inline ::ui::Cv* UiV2PadData::mutable_cv(int index) {
  // @@protoc_insertion_point(field_mutable:ui.UiV2PadData.cv)
  return cv_.Mutable(index);
}
inline ::ui::Cv* UiV2PadData::add_cv() {
  // @@protoc_insertion_point(field_add:ui.UiV2PadData.cv)
  return cv_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ui::Cv >*
UiV2PadData::mutable_cv() {
  // @@protoc_insertion_point(field_mutable_list:ui.UiV2PadData.cv)
  return &cv_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ui::Cv >&
UiV2PadData::cv() const {
  // @@protoc_insertion_point(field_list:ui.UiV2PadData.cv)
  return cv_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ui

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ui_2eproto__INCLUDED
